import { createHash } from "node:crypto";
import { getApps, initializeApp } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { FieldValue, getFirestore } from "firebase-admin/firestore";
import { HttpsError, onCall, type CallableRequest } from "firebase-functions/https";
import { reduceGame } from "../../../src/features/game/domain/lifecycle.js";
import { projectRoom, type CanonicalMember, type CanonicalRoom } from "../game.js";

if (!getApps().length) initializeApp();
const db = getFirestore();
const auth = getAuth();
const region = process.env.FUNCTIONS_REGION || "me-central2";
const callable = { region, enforceAppCheck: process.env.FUNCTIONS_EMULATOR !== "true" } as const;
const roles = ["super_admin", "content_admin", "reviewer", "game_ops", "viewer"] as const;
type Role = (typeof roles)[number];
type Capability = "session" | "questions.read" | "questions.write" | "reviews.read" | "reviews.decide" | "categories.read" | "categories.write" | "releases.read" | "releases.stage" | "rooms.read" | "rooms.act" | "users.read" | "users.write" | "audit.read" | "health.read" | "settings.read" | "settings.write";
const capabilities: Record<Role, readonly Capability[]> = {
  super_admin: ["session", "questions.read", "questions.write", "reviews.read", "reviews.decide", "categories.read", "categories.write", "releases.read", "releases.stage", "rooms.read", "rooms.act", "users.read", "users.write", "audit.read", "health.read", "settings.read", "settings.write"],
  content_admin: ["session", "questions.read", "questions.write", "reviews.read", "categories.read", "categories.write", "releases.read", "releases.stage", "audit.read", "health.read", "settings.read"],
  reviewer: ["session", "questions.read", "reviews.read", "reviews.decide", "categories.read", "audit.read", "health.read"],
  game_ops: ["session", "rooms.read", "rooms.act", "audit.read", "health.read"],
  viewer: ["session", "questions.read", "reviews.read", "categories.read", "releases.read", "rooms.read", "audit.read", "health.read", "settings.read"],
};
export function sameAdminAuthorization(liveRoles: readonly string[], claimRoles: readonly string[], liveVersion: number, claimVersion: unknown) {
  return liveVersion === claimVersion && liveRoles.length === claimRoles.length && liveRoles.every(role => claimRoles.includes(role));
}
const maxPageSize = 100;
const id = (value: unknown, name = "id") => {
  if (typeof value !== "string" || !/^[A-Za-z0-9_-]{1,128}$/.test(value)) throw new HttpsError("invalid-argument", `Invalid ${name}.`);
  return value;
};
const optionalId = (value: unknown, name = "id") => value === undefined ? undefined : id(value, name);
const text = (value: unknown, name: string, max = 4000) => {
  if (typeof value !== "string" || !value.trim() || value.length > max) throw new HttpsError("invalid-argument", `Invalid ${name}.`);
  return value.trim();
};
const integer = (value: unknown, name: string, min = 0, max = Number.MAX_SAFE_INTEGER) => {
  if (!Number.isInteger(value) || (value as number) < min || (value as number) > max) throw new HttpsError("invalid-argument", `Invalid ${name}.`);
  return value as number;
};
const object = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : (() => { throw new HttpsError("invalid-argument", "Expected an object."); })();
function only(data: Record<string, unknown>, keys: readonly string[]) {
  for (const key of Object.keys(data)) if (!keys.includes(key)) throw new HttpsError("invalid-argument", `Unsupported field: ${key}.`);
}
function listInput(value: unknown) {
  const data = object(value ?? {}); only(data, ["limit", "cursor", "status", "categoryId", "query"]);
  const limit = data.limit === undefined ? 25 : integer(data.limit, "limit", 1, maxPageSize);
  return { limit, cursor: optionalId(data.cursor, "cursor"), status: typeof data.status === "string" ? data.status.slice(0, 64) : undefined, categoryId: typeof data.categoryId === "string" ? id(data.categoryId, "categoryId") : undefined, query: typeof data.query === "string" ? data.query.trim().slice(0, 120) : undefined };
}
function mutationEnabled() { return process.env.FUNCTIONS_EMULATOR === "true" || process.env.ADMIN_MUTATIONS_ENABLED === "true"; }
function productionBlocked() { if (!mutationEnabled()) throw new HttpsError("failed-precondition", "Admin mutations are staged and disabled in this environment."); }
function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, entry]) => [key, canonicalize(entry)]),
    );
  }
  return value;
}
export function canonicalAdminHash(value: unknown) {
  return createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex");
}
type Principal = { uid: string; roles: Role[]; authzVersion: number; requestHash: string; categoryScopes?: string[]; reviewerScopes?: string[] };
async function principal(request: CallableRequest<unknown>, capability: Capability): Promise<Principal> {
  const uid = request.auth?.uid;
  const token = request.auth?.token as Record<string, unknown> | undefined;
  const provider = token?.firebase && typeof token.firebase === "object" ? (token.firebase as Record<string, unknown>).sign_in_provider : undefined;
  if (!uid || provider !== "google.com" || token?.email_verified !== true) throw new HttpsError("unauthenticated", "A verified Google identity is required for administration.");
  const snap = await db.doc(`adminPrincipals/${uid}`).get();
  const row = snap.data();
  if (!snap.exists || row?.enabled !== true || row.identityReady !== true || !Array.isArray(row.roles) || !Number.isInteger(row.authzVersion)) throw new HttpsError("permission-denied", "No synchronized enabled administrator registry record.");
  const liveRoles = row.roles.filter((role: unknown): role is Role => typeof role === "string" && (roles as readonly string[]).includes(role));
  const claimRoles = Array.isArray(token?.adminRoles) ? token.adminRoles.filter((role): role is Role => typeof role === "string" && (roles as readonly string[]).includes(role)) : [];
  if (!sameAdminAuthorization(liveRoles, claimRoles, row.authzVersion, token?.authzVersion)) throw new HttpsError("permission-denied", "Administrative authorization is stale. Refresh your Google session.");
  if (!liveRoles.some((role) => capabilities[role].includes(capability))) throw new HttpsError("permission-denied", "Missing administrative capability.");
  return { uid, roles: liveRoles, authzVersion: row.authzVersion, requestHash: canonicalAdminHash(request.data ?? {}), categoryScopes: Array.isArray(row.categoryScopes) ? row.categoryScopes.filter((v: unknown): v is string => typeof v === "string") : [], reviewerScopes: Array.isArray(row.reviewerScopes) ? row.reviewerScopes.filter((v: unknown): v is string => typeof v === "string") : [] };
}
function requireRole(actor: Principal, role: Role) { if (!actor.roles.includes(role)) throw new HttpsError("permission-denied", "This action requires super administrator authority."); }
function scopeCategory(actor: Principal, categoryId: string) { if (!actor.roles.includes("super_admin") && (!actor.categoryScopes?.includes(categoryId))) throw new HttpsError("permission-denied", "Category is outside your assigned scope."); }
function scopeReviewer(actor: Principal, categoryId: string, specialistRoles: unknown) { scopeCategory(actor, categoryId); if (actor.roles.includes("super_admin")) return; if (!actor.roles.includes("reviewer") || !Array.isArray(specialistRoles) || specialistRoles.some(role => typeof role !== "string" || !actor.reviewerScopes?.includes(role))) throw new HttpsError("permission-denied", "Reviewer qualifications do not cover this modality."); }
const specialistRolesByModality = {
  classic: ["fact_reviewer", "language_reviewer"],
  image: ["fact_reviewer", "language_reviewer", "image_rights_reviewer"],
  charades: ["fact_reviewer", "language_reviewer", "charades_performance_reviewer", "charades_originality_reviewer", "charades_cultural_suitability_reviewer"],
} as const;
const specialistRoleSet = new Set<string>(Object.values(specialistRolesByModality).flat());
function scopedIdList(value: unknown, name: string, reviewer = false) { if (!Array.isArray(value) || value.length > 100 || value.some(item => typeof item !== "string" || (reviewer ? !specialistRoleSet.has(item) : !/^[A-Za-z0-9_-]{1,128}$/.test(item)))) throw new HttpsError("invalid-argument", `Invalid ${name}.`); return [...new Set(value as string[])].sort(); }
export function validateAdminQuestionDraft(draft: Record<string, unknown>) {
  const modality = draft.modality;
  if (modality !== "classic" && modality !== "image" && modality !== "charades") throw new HttpsError("invalid-argument", "Invalid modality.");
  const requiredRoles = specialistRolesByModality[modality];
  if (!Array.isArray(draft.specialistRoles) || draft.specialistRoles.length !== requiredRoles.length || [...draft.specialistRoles].sort().join("|") !== [...requiredRoles].sort().join("|")) throw new HttpsError("invalid-argument", "specialistRoles must exactly match the v3.3 modality contract.");
  if (draft.sources !== undefined) {
    if (!Array.isArray(draft.sources) || draft.sources.length > 16) throw new HttpsError("invalid-argument", "sources must contain at most 16 records.");
    for (const rawSource of draft.sources) {
      const source = object(rawSource);
      only(source, ["sourceUrl", "publisher", "title", "sourceTier", "retrievedAt"]);
      const sourceUrl = text(source.sourceUrl, "sourceUrl", 2048);
      let parsed: URL;
      try { parsed = new URL(sourceUrl); } catch { throw new HttpsError("invalid-argument", "sourceUrl must be a valid HTTPS URL."); }
      if (parsed.protocol !== "https:" || parsed.username || parsed.password) throw new HttpsError("invalid-argument", "sourceUrl must be a credential-free HTTPS URL.");
      text(source.publisher, "publisher", 240);
      text(source.title, "title", 500);
      text(source.sourceTier, "sourceTier", 64);
      if (source.retrievedAt !== undefined && (typeof source.retrievedAt !== "string" || !/^\d{4}-\d{2}-\d{2}T/.test(source.retrievedAt) || Number.isNaN(Date.parse(source.retrievedAt)))) throw new HttpsError("invalid-argument", "retrievedAt must be an ISO timestamp.");
    }
  }
}
export function questionReviewBinding(value: Record<string, unknown>, revision: number) {
  return canonicalAdminHash({ revision, authorUid: value.authorUid, categoryId: value.categoryId, modality: value.modality, headerAr: value.headerAr, promptAr: value.promptAr, canonicalAnswer: value.canonicalAnswer, acceptedAnswers: value.acceptedAnswers, specialistRoles: value.specialistRoles, sources: value.sources ?? [] });
}
export function reviewMatchesQuestion(review: Record<string, unknown>, question: Record<string, unknown>) { return review.status === "in_review" && question.status === "in_review" && question.revision === review.questionRevision && questionReviewBinding(question, Number(review.questionRevision)) === review.questionHash; }
export function isArchivableQuestionStatus(status: unknown) { return status === "draft" || status === "ready_for_review" || status === "changes_requested"; }
export function adminRoomDto(id: string, data: Record<string, unknown>, includeMembers = false) { const game = data.game && typeof data.game === "object" ? data.game as Record<string, unknown> : {}; const config = data.config && typeof data.config === "object" ? data.config as Record<string, unknown> : {}; const lifecycle = data.lifecycle ?? game.lifecycle; return { id, revision: data.revision, lifecycle, memberCount: data.memberCount ?? (Array.isArray(data.members) ? data.members.filter(member => member && typeof member === "object" && (member as Record<string, unknown>).active === true).length : undefined), createdAt: data.createdAt ?? null, updatedAt: data.updatedAt ?? null, releaseId: data.releaseId ?? config.releaseId, roomCode: data.roomCode, paused: lifecycle === "PAUSED", closed: data.closed === true, currentRound: data.currentRound ?? game.currentRound, questionScores: data.questionScores ?? game.questionScores, teams: data.teams ?? config.teams, ...(includeMembers && Array.isArray(data.members) ? { members: data.members.map(member => { const value = object(member); return { uid: value.uid, displayName: value.displayName, role: value.role, team: value.team, ready: value.ready === true, active: value.active === true }; }) } : {}) }; }
function writeRoomAdminViews(tx: FirebaseFirestore.Transaction, roomId: string, room: CanonicalRoom, members: CanonicalMember[]) {
  tx.set(db.doc(`rooms/${roomId}/projections/audience`), projectRoom(roomId, room, members, "audience", undefined, Date.now()));
  for (const member of members) { if (!member.active) continue; if (member.role === "host") tx.set(db.doc(`rooms/${roomId}/projections/host`), projectRoom(roomId, room, members, "host", member.uid, Date.now())); if (member.role === "player") tx.set(db.doc(`rooms/${roomId}/projections/player_${member.uid}`), projectRoom(roomId, room, members, "player", member.uid, Date.now())); }
  tx.set(db.doc(`adminRoomSummaries/${roomId}`), { revision: room.revision, roomCode: room.roomCode, lifecycle: room.game.lifecycle, releaseId: room.config.releaseId, memberCount: members.filter(member => member.active).length, closed: Boolean((room as CanonicalRoom & { closedAt?: unknown }).closedAt), currentRound: room.game.currentRound, questionScores: room.game.questionScores, teams: room.config.teams, members: members.map(member => ({ uid: member.uid, displayName: member.displayName, role: member.role, team: member.team ?? null, ready: member.ready, active: member.active })), updatedAt: FieldValue.serverTimestamp() });
}
async function page(collection: string, input: ReturnType<typeof listInput>, filters: Record<string, unknown> = {}, allowedCategories?: readonly string[]) {
  let query: FirebaseFirestore.Query = db.collection(collection);
  if (allowedCategories) {
    if (!allowedCategories.length) return { items: [], nextCursor: null };
    if (input.categoryId && !allowedCategories.includes(input.categoryId)) throw new HttpsError("permission-denied", "Category is outside your assigned scope.");
    if (!input.categoryId) {
      if (allowedCategories.length > 30) throw new HttpsError("failed-precondition", "Select one assigned category to page this inventory.");
      query = query.where("categoryId", "in", allowedCategories);
    }
  }
  for (const [field, value] of Object.entries(filters)) if (value !== undefined) query = query.where(field, "==", value);
  query = query.orderBy("updatedAt", "desc").limit(input.limit + 1);
  if (input.cursor) { const cursor = await db.doc(`${collection}/${input.cursor}`).get(); if (cursor.exists) { if (allowedCategories && !allowedCategories.includes(String(cursor.data()?.categoryId))) throw new HttpsError("permission-denied", "Cursor is outside your assigned scope."); query = query.startAfter(cursor); } }
  const rows = await query.get(); const docs = rows.docs.slice(0, input.limit);
  return { items: docs.map((doc) => ({ id: doc.id, ...doc.data() })), nextCursor: rows.docs.length > input.limit ? docs.at(-1)?.id : null };
}
async function pageBy(collection: string, input: ReturnType<typeof listInput>, field: string, filters: Record<string, unknown> = {}) {
  let query: FirebaseFirestore.Query = db.collection(collection);
  for (const [filterField, value] of Object.entries(filters)) if (value !== undefined) query = query.where(filterField, "==", value);
  query = query.orderBy(field, "desc").limit(input.limit + 1);
  if (input.cursor) { const cursor = await db.doc(`${collection}/${input.cursor}`).get(); if (cursor.exists) query = query.startAfter(cursor); }
  const rows = await query.get(); const docs = rows.docs.slice(0, input.limit);
  return { items: docs.map((doc) => ({ id: doc.id, ...doc.data() })), nextCursor: rows.docs.length > input.limit ? docs.at(-1)?.id : null };
}
async function pageIds(collection: string, input: ReturnType<typeof listInput>) {
  let query: FirebaseFirestore.Query = db.collection(collection).orderBy("__name__").limit(input.limit + 1);
  if (input.cursor) { const cursor = await db.doc(`${collection}/${input.cursor}`).get(); if (cursor.exists) query = query.startAfter(cursor); }
  const rows = await query.get(); const docs = rows.docs.slice(0, input.limit);
  return { items: docs.map(doc => ({ id: doc.id, ...doc.data() })), nextCursor: rows.docs.length > input.limit ? docs.at(-1)?.id ?? null : null };
}
async function mutate(actor: Principal, operationId: string, action: string, target: string, expectedRevision: number, fn: (tx: FirebaseFirestore.Transaction, operation: FirebaseFirestore.DocumentReference) => Promise<{ revision: number; status?: string }>) {
  productionBlocked();
  const operationRef = db.doc(`adminOperations/${operationId}`);
  return db.runTransaction(async (tx) => {
    // A category move or archive must be authorized against the stored record as
    // well as the submitted target category. Keeping this at the mutation
    // boundary prevents compressed handlers from accidentally bypassing it.
    if (action === "question.save" || action === "question.archive") {
      const stored = await tx.get(db.doc(`adminQuestionDrafts/${target}`));
      if (stored.exists) scopeCategory(actor, String(stored.data()!.categoryId));
    }
    const prior = await tx.get(operationRef);
    if (prior.exists) { const data = prior.data()!; if (data.actorUid !== actor.uid || data.action !== action || data.target !== target || data.requestHash !== actor.requestHash) throw new HttpsError("already-exists", "operationId was previously used for a different mutation payload."); return { operationId, revision: data.revision, replayed: true, serverTime: data.serverTime ?? null }; }
    const result = await fn(tx, operationRef);
    const serverTime = new Date().toISOString();
    const status = result.status ?? (action.startsWith("user.") ? "registry_committed" : "completed");
    if (action.startsWith("user.")) tx.set(db.doc(`adminPrincipals/${target}`), { identityReady: false, identityUpdatedAt: FieldValue.serverTimestamp() }, { merge: true });
    tx.create(operationRef, { actorUid: actor.uid, actorRoles: actor.roles, action, target, expectedRevision, revision: result.revision, status, serverTime, requestHash: actor.requestHash });
    tx.create(db.collection("adminAudit").doc(), { actorUid: actor.uid, actorRoles: actor.roles, operationId, action, target, expectedRevision, resultRevision: result.revision, result: status, requestHash: actor.requestHash, createdAt: FieldValue.serverTimestamp() });
    return { operationId, revision: result.revision, replayed: false, serverTime };
  });
}
async function enforceRateLimit(uid: string) { const now = Date.now(); const bucket = Math.floor(now / 60_000); const ref = db.doc(`adminRateLimits/${uid}_${bucket}`); await db.runTransaction(async tx => { const snap = await tx.get(ref); const count = Number(snap.data()?.count ?? 0); if (count >= 120) throw new HttpsError("resource-exhausted", "Administrative request rate exceeded."); tx.set(ref, { uid, bucket, count: count + 1, expiresAt: new Date(now + 5 * 60_000) }, { merge: true }); }); }
function call(capability: Capability, handler: (request: CallableRequest<unknown>, actor: Principal) => Promise<unknown>) { return onCall(callable, async request => { if (Buffer.byteLength(JSON.stringify(request.data ?? {}), "utf8") > 64 * 1024) throw new HttpsError("invalid-argument", "Administrative request is too large."); const actor = await principal(request, capability); await enforceRateLimit(actor.uid); return handler(request, actor); }); }

export const adminGetSession = call("session", async (_request, actor) => ({ uid: actor.uid, roles: actor.roles, authzVersion: actor.authzVersion, capabilities: [...new Set(actor.roles.flatMap(role => capabilities[role]))], mutationMode: mutationEnabled() ? "enabled" : "staged" }));
export const adminGetOverview = call("session", async (_request, actor) => { const inventory: Record<string, number> = {}; const globalViewer = actor.roles.includes("super_admin") || actor.roles.includes("viewer"); const scopedCount = async (collection: string) => { const scopes = actor.categoryScopes ?? []; if (!scopes.length) return 0; if (scopes.length <= 30) return (await db.collection(collection).where("categoryId", "in", scopes).count().get()).data().count; const counts = await Promise.all(scopes.map(async categoryId => (await db.collection(collection).where("categoryId", "==", categoryId).count().get()).data().count)); return counts.reduce((sum, count) => sum + count, 0); }; if (globalViewer) { const names = ["adminQuestionDrafts", "adminReviewRequests", "adminRoomSummaries", "adminOperations"]; const counts = await Promise.all(names.map(async name => (await db.collection(name).count().get()).data().count)); names.forEach((name, index) => { inventory[name] = counts[index]; }); } else { if (actor.roles.some(role => role === "content_admin" || role === "reviewer")) { inventory.adminQuestionDrafts = await scopedCount("adminQuestionDrafts"); inventory.adminReviewRequests = await scopedCount("adminReviewRequests"); } if (actor.roles.includes("game_ops")) inventory.adminRoomSummaries = (await db.collection("adminRoomSummaries").count().get()).data().count; } return { inventory, mutationMode: mutationEnabled() ? "enabled" : "staged", actor: { uid: actor.uid, roles: actor.roles } }; });

export const adminListQuestions = call("questions.read", async (request, actor) => { const input = listInput(request.data); const result = await page("adminQuestionDrafts", input, { status: input.status, categoryId: input.categoryId }, actor.roles.includes("super_admin") ? undefined : actor.categoryScopes); const items = (result.items as Record<string, unknown>[]).map(item => ({ id: item.id, revision: item.revision, status: item.status, categoryId: item.categoryId, modality: item.modality, headerAr: item.headerAr, updatedAt: item.updatedAt })); return { ...result, items }; });
export const adminGetQuestion = call("questions.read", async (request, actor) => { const data = object(request.data); only(data, ["id"]); const snap = await db.doc(`adminQuestionDrafts/${id(data.id)}`).get(); if (!snap.exists) throw new HttpsError("not-found", "Question draft not found."); scopeCategory(actor, String(snap.data()!.categoryId)); return { id: snap.id, ...snap.data() }; });
export const adminSaveQuestion = call("questions.write", async (request, actor) => { const data = object(request.data); only(data, ["id", "operationId", "expectedRevision", "draft"]); const draft = object(data.draft); only(draft, ["categoryId", "modality", "headerAr", "promptAr", "canonicalAnswer", "acceptedAnswers", "specialistRoles", "sources", "status"]); const questionId = id(data.id); const operationId = id(data.operationId, "operationId"); const expected = integer(data.expectedRevision, "expectedRevision", 0); const categoryId = id(draft.categoryId, "categoryId"); scopeCategory(actor, categoryId); validateAdminQuestionDraft(draft); if (draft.status !== undefined && draft.status !== "draft" && draft.status !== "ready_for_review") throw new HttpsError("invalid-argument", "Invalid draft status."); text(draft.headerAr, "headerAr", 240); text(draft.promptAr, "promptAr", 4000); text(draft.canonicalAnswer, "canonicalAnswer", 1000); if (!Array.isArray(draft.acceptedAnswers) || draft.acceptedAnswers.length < 1 || draft.acceptedAnswers.length > 32 || draft.acceptedAnswers.some(answer => typeof answer !== "string" || !answer.trim() || answer.length > 1000)) throw new HttpsError("invalid-argument", "acceptedAnswers must contain 1–32 Arabic answer variants."); return mutate(actor, operationId, "question.save", questionId, expected, async (tx) => { const ref = db.doc(`adminQuestionDrafts/${questionId}`); const prior = await tx.get(ref); const current = prior.exists ? prior.data()! : undefined; const revision = current?.revision ?? 0; if (revision !== expected) throw new HttpsError("aborted", "stale-revision"); if (["in_review", "approved", "exported", "released"].includes(String(current?.status))) throw new HttpsError("failed-precondition", "Immutable review work must be forked into a successor draft."); const next = { ...draft, status: draft.status ?? "draft", revision: revision + 1, authorUid: current?.authorUid ?? actor.uid, updatedAt: FieldValue.serverTimestamp(), createdAt: current?.createdAt ?? FieldValue.serverTimestamp() }; tx.set(ref, next); tx.create(ref.collection("revisions").doc(String(revision + 1).padStart(8, "0")), { ...draft, status: next.status, revision: revision + 1, immutable: true, createdBy: actor.uid, createdAt: FieldValue.serverTimestamp() }); return { revision: revision + 1 }; }); });
export const adminValidateQuestion = call("questions.write", async (request, actor) => { const data = object(request.data); only(data, ["id"]); const questionId = id(data.id); const snap = await db.doc(`adminQuestionDrafts/${questionId}`).get(); if (!snap.exists) throw new HttpsError("not-found", "Question draft not found."); const draft = snap.data()!; scopeCategory(actor, String(draft.categoryId)); const errors = ["headerAr", "promptAr", "canonicalAnswer", "specialistRoles"].filter(field => !draft[field] || (Array.isArray(draft[field]) && !draft[field].length)); return { id: questionId, valid: !errors.length, errors, state: draft.status }; });
export const adminSubmitQuestionReview = call("questions.write", async (request, actor) => { const data = object(request.data); only(data, ["id", "operationId", "expectedRevision"]); const questionId = id(data.id); const expected = integer(data.expectedRevision, "expectedRevision", 1); return mutate(actor, id(data.operationId, "operationId"), "question.submit-review", questionId, expected, async (tx) => { const ref = db.doc(`adminQuestionDrafts/${questionId}`); const snap = await tx.get(ref); if (!snap.exists) throw new HttpsError("not-found", "Question draft not found."); const value = snap.data()!; scopeCategory(actor, String(value.categoryId)); if (value.revision !== expected || value.status !== "ready_for_review") throw new HttpsError("aborted", "stale-or-illegal-question-state"); const reviewRef = db.collection("adminReviewRequests").doc(questionId); const existing = await tx.get(reviewRef); if (existing.exists && existing.data()!.status === "in_review") throw new HttpsError("failed-precondition", "A review is already in progress."); const submittedRevision = expected + 1; const submittedValue = { ...value, status: "in_review", revision: submittedRevision }; tx.update(ref, { status: "in_review", revision: submittedRevision, updatedAt: FieldValue.serverTimestamp() }); tx.create(ref.collection("revisions").doc(String(submittedRevision).padStart(8, "0")), { ...submittedValue, immutable: true, createdBy: actor.uid, createdAt: FieldValue.serverTimestamp() }); tx.set(reviewRef, { questionId, categoryId: value.categoryId, authorUid: value.authorUid, specialistRoles: value.specialistRoles, questionRevision: submittedRevision, questionHash: questionReviewBinding(submittedValue, submittedRevision), status: "in_review", revision: Number(existing.data()?.revision ?? 0) + 1, updatedAt: FieldValue.serverTimestamp(), createdAt: existing.data()?.createdAt ?? FieldValue.serverTimestamp() }); return { revision: submittedRevision }; }); });
export const adminArchiveQuestion = call("questions.write", async (request, actor) => { const data = object(request.data); only(data, ["id", "operationId", "expectedRevision"]); const questionId = id(data.id); const expected = integer(data.expectedRevision, "expectedRevision", 1); return mutate(actor, id(data.operationId, "operationId"), "question.archive", questionId, expected, async tx => { const ref = db.doc(`adminQuestionDrafts/${questionId}`); const snap = await tx.get(ref); if (!snap.exists) throw new HttpsError("not-found", "Question draft not found."); const current = snap.data()!; scopeCategory(actor, String(current.categoryId)); if (current.revision !== expected) throw new HttpsError("aborted", "stale-revision"); if (!["draft", "ready_for_review", "changes_requested"].includes(String(current.status))) throw new HttpsError("failed-precondition", "Only mutable draft states may be archived."); tx.update(ref, { status: "archived", revision: expected + 1, updatedAt: FieldValue.serverTimestamp() }); tx.create(ref.collection("revisions").doc(String(expected + 1).padStart(8, "0")), { ...current, status: "archived", revision: expected + 1, immutable: true, createdBy: actor.uid, createdAt: FieldValue.serverTimestamp() }); return { revision: expected + 1 }; }); });

export const adminListReviews = call("reviews.read", async (request, actor) => { const input = listInput(request.data); const result = await page("adminReviewRequests", input, { status: input.status, categoryId: input.categoryId }, actor.roles.includes("super_admin") ? undefined : actor.categoryScopes); const items = (result.items as Record<string, unknown>[]).map(item => ({ id: item.id, questionId: item.questionId, categoryId: item.categoryId, status: item.status, revision: item.revision, updatedAt: item.updatedAt })); return { ...result, items }; });
export const adminGetReview = call("reviews.read", async (request, actor) => { const data = object(request.data); only(data, ["id"]); const snap = await db.doc(`adminReviewRequests/${id(data.id)}`).get(); if (!snap.exists) throw new HttpsError("not-found", "Review not found."); scopeCategory(actor, String(snap.data()!.categoryId)); return { id: snap.id, ...snap.data() }; });
export const adminDecideReview = call("reviews.decide", async (request, actor) => { const data = object(request.data); only(data, ["id", "operationId", "expectedRevision", "decision", "reason"]); const reviewId = id(data.id); const expected = integer(data.expectedRevision, "expectedRevision", 1); const decision = data.decision === "approved" || data.decision === "changes_requested" ? data.decision : (() => { throw new HttpsError("invalid-argument", "Invalid decision."); })(); if (decision === "approved") throw new HttpsError("failed-precondition", "Approval is staged: signing keys and receipt verification are unavailable."); const reason = text(data.reason, "reason", 2000); return mutate(actor, id(data.operationId, "operationId"), "review.decide", reviewId, expected, async tx => { const reviewRef = db.doc(`adminReviewRequests/${reviewId}`); const review = await tx.get(reviewRef); if (!review.exists) throw new HttpsError("not-found", "Review not found."); const value = review.data()!; if (value.revision !== expected || value.status !== "in_review" || value.authorUid === actor.uid) throw new HttpsError("permission-denied", "The review is stale, completed, or self-authored."); const questionRef = db.doc(`adminQuestionDrafts/${value.questionId}`); const question = await tx.get(questionRef); if (!question.exists) throw new HttpsError("not-found", "Question draft not found."); const questionValue = question.data()!; if (questionValue.status !== "in_review" || questionValue.revision !== value.questionRevision || questionReviewBinding(questionValue, Number(value.questionRevision)) !== value.questionHash) throw new HttpsError("aborted", "Review binding is stale or the submitted revision changed."); scopeReviewer(actor, String(questionValue.categoryId), questionValue.specialistRoles); const nextQuestionRevision = Number(questionValue.revision) + 1; tx.update(reviewRef, { status: decision, revision: expected + 1, decidedBy: actor.uid, reason, updatedAt: FieldValue.serverTimestamp() }); tx.update(questionRef, { status: decision, revision: nextQuestionRevision, updatedAt: FieldValue.serverTimestamp() }); tx.create(questionRef.collection("revisions").doc(String(nextQuestionRevision).padStart(8, "0")), { ...questionValue, status: decision, revision: nextQuestionRevision, immutable: true, createdBy: actor.uid, createdAt: FieldValue.serverTimestamp() }); return { revision: expected + 1 }; }); });

export const adminListCategories = call("categories.read", async (request, actor) => { const input = listInput(request.data); if (actor.roles.includes("super_admin")) return page("adminCategoryMetadata", input); const scoped = [...new Set(actor.categoryScopes ?? [])].sort(); if (input.categoryId && !scoped.includes(input.categoryId)) throw new HttpsError("permission-denied", "Category is outside your assigned scope."); const selected = input.categoryId ? [input.categoryId] : scoped; const start = input.cursor ? selected.indexOf(input.cursor) + 1 : 0; if (input.cursor && start === 0) throw new HttpsError("permission-denied", "Cursor is outside your assigned scope."); const ids = selected.slice(start, start + input.limit + 1); if (!ids.length) return { items: [], nextCursor: null }; const snapshots = await db.getAll(...ids.map(categoryId => db.doc(`adminCategoryMetadata/${categoryId}`))); const visible = snapshots.filter(snapshot => snapshot.exists).slice(0, input.limit); return { items: visible.map(snapshot => ({ id: snapshot.id, ...snapshot.data() })), nextCursor: ids.length > input.limit ? ids[input.limit - 1] : null }; });
export const adminGetCategory = call("categories.read", async (request, actor) => { const data = object(request.data); only(data, ["id"]); const categoryId = id(data.id); scopeCategory(actor, categoryId); const snap = await db.doc(`adminCategoryMetadata/${categoryId}`).get(); if (!snap.exists) throw new HttpsError("not-found", "Category not found."); return { id: snap.id, ...snap.data() }; });
export const adminUpdateCategory = call("categories.write", async (request, actor) => { const data = object(request.data); only(data, ["id", "operationId", "expectedRevision", "metadata"]); const categoryId = id(data.id); scopeCategory(actor, categoryId); const metadata = object(data.metadata); only(metadata, ["titleAr", "descriptionAr", "enabled"]); if (metadata.titleAr !== undefined) text(metadata.titleAr, "titleAr", 160); if (metadata.descriptionAr !== undefined) text(metadata.descriptionAr, "descriptionAr", 1000); if (metadata.enabled !== undefined && typeof metadata.enabled !== "boolean") throw new HttpsError("invalid-argument", "enabled must be boolean."); const expected = integer(data.expectedRevision, "expectedRevision", 0); return mutate(actor, id(data.operationId, "operationId"), "category.update", categoryId, expected, async tx => { const ref = db.doc(`adminCategoryMetadata/${categoryId}`); const prior = await tx.get(ref); const revision = prior.exists ? Number(prior.data()!.revision ?? 0) : 0; if (revision !== expected) throw new HttpsError("aborted", "stale-revision"); tx.set(ref, { ...metadata, revision: revision + 1, updatedAt: FieldValue.serverTimestamp(), createdAt: prior.data()?.createdAt ?? FieldValue.serverTimestamp() }, { merge: true }); return { revision: revision + 1 }; }); });

export const adminListReleases = call("releases.read", async request => pageIds("releases", listInput(request.data)));
export const adminGetRelease = call("releases.read", async request => { const data = object(request.data); only(data, ["id"]); const snap = await db.doc(`releases/${id(data.id)}`).get(); if (!snap.exists) throw new HttpsError("not-found", "Release not found."); return { id: snap.id, ...snap.data() }; });
export const adminAuditRelease = call("releases.read", async request => { const data = object(request.data); only(data, ["id"]); const releaseId = id(data.id); const snap = await db.doc(`releases/${releaseId}`).get(); return { releaseId, exists: snap.exists, immutable: snap.data()?.immutable === true, publication: "Use the existing plan/prepare/exact-verify/single-use barrier/activation workflow; this endpoint never publishes." }; });
export const adminStageRelease = call("releases.stage", async (request, actor) => { const data = object(request.data); only(data, ["id", "operationId", "expectedRevision"]); const releaseId = id(data.id); return mutate(actor, id(data.operationId, "operationId"), "release.stage", releaseId, integer(data.expectedRevision, "expectedRevision", 0), async () => ({ revision: 0, status: "blocked" })); });
const staged = (capability: Capability, action: string) => call(capability, async request => { const data = object(request.data); only(data, ["id", "operationId", "expectedRevision"]); return { state: "blocked", reason: `${action} is intentionally unavailable until the immutable release pipeline prerequisites are verified.`, operationId: optionalId(data.operationId, "operationId") }; });
export const adminCreateQuestion = adminSaveQuestion;
export const adminImportPreview = staged("questions.write", "Question import preview");
export const adminImportCommit = staged("questions.write", "Question import commit");
export const adminCreateExportJob = staged("releases.stage", "Question export");
export const adminCreateMediaUploadSession = staged("questions.write", "Media upload session");
export const adminFinalizeMediaUpload = staged("questions.write", "Media upload finalization");
export const adminRemoveUnreferencedMedia = staged("questions.write", "Media removal");
export const adminAssignReview = staged("reviews.decide", "Review assignment");
export const adminRequestReviewChanges = staged("reviews.decide", "Review change request");
export const adminPrepareRelease = staged("releases.stage", "Release prepare");
export const adminVerifyRelease = staged("releases.stage", "Release verify");
export const adminActivateRelease = staged("releases.stage", "Release activation");
export const adminRollbackRelease = staged("releases.stage", "Release rollback");

export const adminListRooms = call("rooms.read", async request => { const result = await page("adminRoomSummaries", listInput(request.data)); return { ...result, items: result.items.map(item => adminRoomDto(String(item.id), item)) }; });
export const adminGetRoom = call("rooms.act", async request => { const data = object(request.data); only(data, ["id"]); const roomId = id(data.id); const snap = await db.doc(`adminRoomSummaries/${roomId}`).get(); if (!snap.exists) throw new HttpsError("not-found", "Room summary not found."); return adminRoomDto(snap.id, snap.data()!, true); });
export const adminRoomAction = call("rooms.act", async (request, actor) => { const data = object(request.data); only(data, ["id", "operationId", "expectedRevision", "action", "reason", "memberUid"]); const roomId = id(data.id); const action = data.action === "pause" || data.action === "resume" || data.action === "close" || data.action === "remove_member" ? data.action : (() => { throw new HttpsError("invalid-argument", "Invalid room action."); })(); const reason = text(data.reason, "reason", 1000); const memberUid = action === "remove_member" ? id(data.memberUid, "memberUid") : undefined; const expected = integer(data.expectedRevision, "expectedRevision", 1); return mutate(actor, id(data.operationId, "operationId"), `room.${action}`, roomId, expected, async tx => { const ref = db.doc(`rooms/${roomId}`); const snap = await tx.get(ref); const membersSnap = await tx.get(ref.collection("members")); if (!snap.exists) throw new HttpsError("not-found", "Room not found."); const room = snap.data() as CanonicalRoom; if (room.revision !== expected || (room as unknown as { closedAt?: unknown }).closedAt) throw new HttpsError("aborted", "stale-or-closed-room"); const targetMember = memberUid ? membersSnap.docs.map(doc => doc.data() as CanonicalMember).find(member => member.uid === memberUid) : undefined; if (memberUid && (!targetMember || targetMember.role === "host" || targetMember.active !== true)) throw new HttpsError("failed-precondition", "Only an active non-host participant may be removed."); const game = action === "pause" || action === "resume" ? reduceGame(room.game, { type: action === "pause" ? "PAUSE" : "RESUME" }) : room.game; const timer = action === "pause" && room.timer ? { deadlineMs: 0, buzzOpen: false, remainingMs: Math.max(0, room.timer.deadlineMs - Date.now()), pausedBuzzOpen: room.timer.buzzOpen } : action === "resume" && room.timer?.remainingMs !== undefined ? { deadlineMs: Date.now() + room.timer.remainingMs, buzzOpen: Boolean(room.timer.pausedBuzzOpen) } : room.timer; const next = { ...room, game, timer, revision: expected + 1, updatedAt: FieldValue.serverTimestamp(), ...(action === "close" ? { closedAt: FieldValue.serverTimestamp() } : {}) } as CanonicalRoom; const members = membersSnap.docs.map(doc => doc.data() as CanonicalMember).map(member => memberUid && member.uid === memberUid ? { ...member, active: false } : member); if (memberUid) tx.update(ref.collection("members").doc(memberUid), { active: false, removedBy: actor.uid, removedReason: reason, updatedAt: FieldValue.serverTimestamp() }); tx.update(ref, next); tx.create(ref.collection("events").doc(String(next.revision).padStart(12, "0")), { type: `ADMIN_${action.toUpperCase()}`, actorUid: actor.uid, reason, revision: next.revision, createdAt: FieldValue.serverTimestamp() }); writeRoomAdminViews(tx, roomId, next, members); return { revision: next.revision }; }); });

export const adminLookupUser = call("users.read", async request => { const data = object(request.data); only(data, ["uid", "email"]); if ((data.uid === undefined) === (data.email === undefined)) throw new HttpsError("invalid-argument", "Provide exactly one UID or email."); const user = data.uid !== undefined ? await auth.getUser(id(data.uid, "uid")) : await auth.getUserByEmail(text(data.email, "email", 320).toLowerCase()); const registry = await db.doc(`adminPrincipals/${user.uid}`).get(); return { uid: user.uid, displayName: user.displayName ?? null, email: user.email ?? null, providerIds: user.providerData.map(provider => provider.providerId), emailVerified: user.emailVerified, disabled: user.disabled, admin: registry.exists ? { enabled: registry.data()!.enabled === true, identityReady: registry.data()!.identityReady === true, roles: registry.data()!.roles ?? [], categoryScopes: registry.data()!.categoryScopes ?? [], reviewerScopes: registry.data()!.reviewerScopes ?? [], authzVersion: registry.data()!.authzVersion ?? 0 } : null }; });
async function synchronizeClaims(targetUid: string) { const [user, registry] = await Promise.all([auth.getUser(targetUid), db.doc(`adminPrincipals/${targetUid}`).get()]); const row = registry.data()!; if (!user.emailVerified || !user.providerData.some(provider => provider.providerId === "google.com") || (row.enabled === true && user.disabled)) throw new HttpsError("failed-precondition", "Target must be a verified, usable Google identity before administrative activation."); await auth.setCustomUserClaims(targetUid, { ...(user.customClaims ?? {}), adminRoles: row.enabled === true ? row.roles : [], authzVersion: row.authzVersion }); await auth.revokeRefreshTokens(targetUid); }
async function recordIdentityOutcome(actor: Principal, operationId: string, action: string, targetUid: string, result: "identity_synced" | "identity_sync_failed") {
  const batch = db.batch();
  batch.set(db.doc(`adminOperations/${operationId}`), { status: result, identityUpdatedAt: FieldValue.serverTimestamp() }, { merge: true });
  batch.set(db.doc(`adminPrincipals/${targetUid}`), { identityReady: result === "identity_synced", identityUpdatedAt: FieldValue.serverTimestamp() }, { merge: true });
  batch.create(db.collection("adminAudit").doc(), { actorUid: actor.uid, actorRoles: actor.roles, operationId, action: `${action}.${result}`, target: targetUid, result, requestHash: actor.requestHash, createdAt: FieldValue.serverTimestamp() });
  await batch.commit();
}
async function synchronizeIdentity(actor: Principal, operationId: string, action: string, targetUid: string, work: () => Promise<void>) {
  let result: "identity_synced" | "identity_sync_failed" = "identity_synced";
  try { await work(); } catch { result = "identity_sync_failed"; }
  await recordIdentityOutcome(actor, operationId, action, targetUid, result);
  if (result === "identity_sync_failed") throw new HttpsError("failed-precondition", "Firebase Auth synchronization failed; registry authorization remains fail-closed.");
}
export function wouldOrphanSuperAdmin(currentlySuper: boolean, remainsSuper: boolean, otherActiveSuperAdmins: number) {
  return currentlySuper && !remainsSuper && otherActiveSuperAdmins < 1;
}
export function wouldLockOutLastSuperAdmin(currentlyUsableSuper: boolean, otherUsableSuperAdmins: number) { return currentlyUsableSuper && otherUsableSuperAdmins < 1; }
async function protectLastSuperAdmin(tx: FirebaseFirestore.Transaction, targetUid: string, current: Record<string, unknown> | undefined, nextEnabled: boolean, nextRoles: readonly Role[]) {
  const currentlySuper = current?.enabled === true && current.identityReady === true && Array.isArray(current.roles) && current.roles.includes("super_admin");
  const remainsSuper = nextEnabled && nextRoles.includes("super_admin");
  if (!currentlySuper) return;
  const lockRef = db.doc("adminAuthzInvariants/superAdmins");
  await tx.get(lockRef);
  const enabledSuperAdmins = await tx.get(db.collection("adminPrincipals").where("enabled", "==", true).where("identityReady", "==", true).where("roles", "array-contains", "super_admin"));
  const otherUsable = enabledSuperAdmins.docs.filter(doc => doc.id !== targetUid).length;
  if (wouldOrphanSuperAdmin(currentlySuper, remainsSuper, otherUsable) || wouldLockOutLastSuperAdmin(currentlySuper, otherUsable)) throw new HttpsError("failed-precondition", "A second synchronized super administrator is required before changing the final one.");
  tx.set(lockRef, { revision: FieldValue.increment(1), updatedAt: FieldValue.serverTimestamp() }, { merge: true });
}
export const adminUpdateUserRole = call("users.write", async (request, actor) => { requireRole(actor, "super_admin"); const data = object(request.data); only(data, ["uid", "operationId", "expectedRevision", "roles", "enabled", "categoryScopes", "reviewerScopes"]); const targetUid = id(data.uid, "uid"); if (!Array.isArray(data.roles) || !data.roles.length || data.roles.some(role => typeof role !== "string" || !(roles as readonly string[]).includes(role))) throw new HttpsError("invalid-argument", "Invalid roles."); if (typeof data.enabled !== "boolean") throw new HttpsError("invalid-argument", "enabled is required."); const nextRoles = [...new Set(data.roles as Role[])].sort(); const categoryScopes = scopedIdList(data.categoryScopes ?? [], "categoryScopes"); const reviewerScopes = scopedIdList(data.reviewerScopes ?? [], "reviewerScopes", true); if (nextRoles.includes("reviewer") && (!categoryScopes.length || !reviewerScopes.length)) throw new HttpsError("invalid-argument", "Reviewers require category and specialist qualification scopes."); const expected = integer(data.expectedRevision, "expectedRevision", 0); const result = await mutate(actor, id(data.operationId, "operationId"), "user.role", targetUid, expected, async tx => { const ref = db.doc(`adminPrincipals/${targetUid}`); const current = await tx.get(ref); const existing = current.data(); const revision = Number(existing?.authzVersion ?? 0); if (revision !== expected) throw new HttpsError("aborted", "stale-authorization-version"); await protectLastSuperAdmin(tx, targetUid, existing, data.enabled as boolean, nextRoles); tx.set(ref, { enabled: data.enabled, roles: nextRoles, categoryScopes, reviewerScopes, authzVersion: revision + 1, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); return { revision: revision + 1 }; }); await synchronizeIdentity(actor, result.operationId, "user.role", targetUid, () => synchronizeClaims(targetUid)); return result; });
export const adminSetUserStatus = call("users.write", async (request, actor) => { requireRole(actor, "super_admin"); const data = object(request.data); only(data, ["uid", "operationId", "expectedRevision", "disabled"]); const targetUid = id(data.uid, "uid"); if (typeof data.disabled !== "boolean") throw new HttpsError("invalid-argument", "disabled is required."); const expected = integer(data.expectedRevision, "expectedRevision", 0); const result = await mutate(actor, id(data.operationId, "operationId"), "user.status", targetUid, expected, async tx => { const ref = db.doc(`adminPrincipals/${targetUid}`); const snap = await tx.get(ref); const current = snap.data(); const version = Number(current?.authzVersion ?? 0); if (version !== expected) throw new HttpsError("aborted", "stale-authorization-version"); const currentRoles = Array.isArray(current?.roles) ? current.roles.filter((role): role is Role => typeof role === "string" && (roles as readonly string[]).includes(role)) : []; await protectLastSuperAdmin(tx, targetUid, current, !data.disabled, currentRoles); tx.set(ref, { enabled: !data.disabled, authzVersion: version + 1, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); return { revision: version + 1 }; }); await synchronizeIdentity(actor, result.operationId, "user.status", targetUid, async () => { await auth.updateUser(targetUid, { disabled: data.disabled as boolean }); await synchronizeClaims(targetUid); }); return result; });
export const adminRevokeUserSessions = call("users.write", async (request, actor) => { requireRole(actor, "super_admin"); const data = object(request.data); only(data, ["uid", "operationId", "expectedRevision"]); const targetUid = id(data.uid, "uid"); const expected = integer(data.expectedRevision, "expectedRevision", 0); const result = await mutate(actor, id(data.operationId, "operationId"), "user.revoke", targetUid, expected, async (tx) => { const ref = db.doc(`adminPrincipals/${targetUid}`); const snap = await tx.get(ref); const current = snap.data(); const version = Number(current?.authzVersion ?? 0); if (version !== expected) throw new HttpsError("aborted", "stale-authorization-version"); const currentRoles = Array.isArray(current?.roles) ? current.roles.filter((role): role is Role => typeof role === "string" && (roles as readonly string[]).includes(role)) : []; await protectLastSuperAdmin(tx, targetUid, current, current?.enabled === true, currentRoles); tx.set(ref, { authzVersion: version + 1, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); return { revision: version + 1 }; }); await synchronizeIdentity(actor, result.operationId, "user.revoke", targetUid, () => synchronizeClaims(targetUid)); return result; });
export const adminListAudit = call("audit.read", async (request, actor) => { const result = await pageBy("adminAudit", listInput(request.data), "createdAt", actor.roles.includes("super_admin") ? {} : { actorUid: actor.uid }); return { ...result, items: (result.items as Record<string, unknown>[]).map(item => ({ id: item.id, actorUid: item.actorUid, actorRoles: item.actorRoles, operationId: item.operationId, action: item.action, target: item.target, expectedRevision: item.expectedRevision, resultRevision: item.resultRevision, result: item.result, createdAt: item.createdAt })) }; });
function runtimeSettingsDto(value: Record<string, unknown>) { return { schemaVersion: value.schemaVersion ?? 1, revision: value.revision ?? 0, maintenanceMode: value.maintenanceMode === true, maintenanceMessageAr: typeof value.maintenanceMessageAr === "string" ? value.maintenanceMessageAr : "", roomCreationEnabled: value.roomCreationEnabled !== false, defaultQuestionTimerSeconds: value.defaultQuestionTimerSeconds ?? 30, defaultOpponentTimerSeconds: value.defaultOpponentTimerSeconds ?? 10, roomRetentionDays: value.roomRetentionDays ?? 30 }; }
export const adminGetHealth = call("health.read", async () => { const [settings, activeRelease, failedJobs, staleRooms] = await Promise.all([db.doc("adminSettings/runtime").get(), db.doc("runtime/activeRelease").get(), db.collection("adminOperations").where("status", "in", ["failed", "identity_sync_failed", "claim_sync_failed"]).count().get(), db.collection("adminRoomSummaries").where("updatedAt", "<", new Date(Date.now() - 24 * 60 * 60 * 1000)).count().get()]); return { components: { auth: "configured", functions: "reachable", firestore: "reachable", storage: "staged", appCheck: callable.enforceAppCheck ? "enforced" : "emulator_disabled" }, activeReleaseId: activeRelease.data()?.releaseId ?? null, failedJobs: failedJobs.data().count, staleRooms: staleRooms.data().count, deploymentVersion: process.env.K_REVISION ?? "local", runtimeRevision: runtimeSettingsDto(settings.data() ?? {}).revision, mutationMode: mutationEnabled() ? "enabled" : "staged", signing: "blocked_missing_signing_key" }; });
export const adminGetSettings = call("settings.read", async () => { const snap = await db.doc("adminSettings/runtime").get(); return { runtime: runtimeSettingsDto(snap.data() ?? {}), immutableNotice: "Production publication settings are not editable from the browser." }; });
export const adminUpdateSettings = call("settings.write", async (request, actor) => { requireRole(actor, "super_admin"); const data = object(request.data); only(data, ["operationId", "expectedRevision", "settings"]); const settings = object(data.settings); only(settings, ["maintenanceMode", "maintenanceMessageAr", "roomCreationEnabled", "defaultQuestionTimerSeconds", "defaultOpponentTimerSeconds", "roomRetentionDays"]); if (settings.maintenanceMode !== undefined && typeof settings.maintenanceMode !== "boolean") throw new HttpsError("invalid-argument", "maintenanceMode must be boolean."); if (settings.maintenanceMessageAr !== undefined && (typeof settings.maintenanceMessageAr !== "string" || settings.maintenanceMessageAr.length > 500)) throw new HttpsError("invalid-argument", "maintenanceMessageAr is invalid."); if (settings.roomCreationEnabled !== undefined && typeof settings.roomCreationEnabled !== "boolean") throw new HttpsError("invalid-argument", "roomCreationEnabled must be boolean."); if (settings.defaultQuestionTimerSeconds !== undefined) integer(settings.defaultQuestionTimerSeconds, "defaultQuestionTimerSeconds", 5, 600); if (settings.defaultOpponentTimerSeconds !== undefined) integer(settings.defaultOpponentTimerSeconds, "defaultOpponentTimerSeconds", 3, 300); if (settings.roomRetentionDays !== undefined) integer(settings.roomRetentionDays, "roomRetentionDays", 1, 365); const expected = integer(data.expectedRevision, "expectedRevision", 0); return mutate(actor, id(data.operationId, "operationId"), "settings.update", "runtime", expected, async tx => { const ref = db.doc("adminSettings/runtime"); const snap = await tx.get(ref); const revision = Number(snap.data()?.revision ?? 0); if (revision !== expected) throw new HttpsError("aborted", "stale-revision"); tx.set(ref, { ...settings, schemaVersion: 1, revision: revision + 1, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); return { revision: revision + 1 }; }); });
