import { expect, test, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';

const evidence = join(process.cwd(), 'output', 'playwright', 'visual-final');
async function capture(page: Page, name: string, width: number, height: number, keyControl?: ReturnType<Page['locator']>) {
  await page.setViewportSize({ width, height });
  await expect(page.locator('body')).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  if (keyControl) { await expect(keyControl).toBeVisible(); await keyControl.evaluate((control) => control.scrollIntoView({ block: 'center' })); const box = await keyControl.boundingBox(); expect(box).not.toBeNull(); expect(box!.x).toBeGreaterThanOrEqual(0); expect(box!.y).toBeGreaterThanOrEqual(0); expect(box!.x + box!.width).toBeLessThanOrEqual(width); expect(box!.y + box!.height).toBeLessThanOrEqual(height); }
  await page.screenshot({ path: join(evidence, `${name}-${width}x${height}.png`), fullPage: true, animations: 'disabled' });
}

async function capturePlayer(page: Page, name: string, width: 320 | 390, height: 568 | 844) {
  const buzzer = page.locator('.buzzer');
  await capture(page, name, width, height, buzzer);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true);
}

test('captures deterministic real-route visual evidence without treating screenshots as approval', async ({ browser, baseURL }) => {
  test.setTimeout(180_000); await mkdir(evidence, { recursive: true });
  const host = await browser.newContext(); const horizontal = await browser.newContext(); const vertical = await browser.newContext(); const audience = await browser.newContext();
  try {
    const hostPage = await host.newPage(); const awaitHost = (state: string) => expect(hostPage.locator(`.host-page[data-state="${state}"]`)).toBeVisible(); const selectCell = async (q: number) => { await awaitHost('CELL_SELECTION'); const cell = hostPage.locator(`.host-board .game-board__button:visible[data-testid="cell-${q}-0"]`); await cell.focus(); await hostPage.keyboard.press('Enter'); await awaitHost('QUESTION_READING'); };
    await hostPage.goto(`${baseURL}/`); await expect(hostPage.locator('.skip-link')).toHaveCount(1); await expect(hostPage.locator('[data-home-region]')).toHaveCount(5); await expect(hostPage.getByRole('link', { name: /^الحروف/ })).toHaveAttribute('href', '/host/new?kind=huroof&mode=classic'); await expect(hostPage.getByRole('link', { name: /^الفئات/ })).toHaveAttribute('href', '/host/new?kind=categories&mode=classic'); await expect(hostPage.locator('[data-home-region="offers-roadmap"] a, [data-home-region="offers-roadmap"] button')).toHaveCount(0); await capture(hostPage, 'entry-light-320', 320, 568); await capture(hostPage, 'entry-light-390', 390, 844); await capture(hostPage, 'entry-light-tablet', 768, 1024); await capture(hostPage, 'entry-light', 1440, 900, hostPage.getByRole('button', { name: 'انضم إلى غرفة' })); await hostPage.locator('.spatial-home__theme-details summary').click(); await hostPage.getByLabel('مظهر التطبيق').getByRole('radio', { name: 'داكن' }).check(); await capture(hostPage, 'entry-dark-mobile', 390, 844); await hostPage.getByLabel('مظهر التطبيق').getByRole('radio', { name: 'فاتح' }).check();
    await hostPage.goto(`${baseURL}/host/new?demo=1`); await capture(hostPage, 'setup-light', 1440, 900, hostPage.getByTestId('create-room'));
    await hostPage.getByLabel('مظهر التطبيق').getByRole('radio', { name: 'داكن' }).check(); await capture(hostPage, 'setup-dark', 1440, 900, hostPage.getByTestId('create-room')); await hostPage.getByLabel('مظهر التطبيق').getByRole('radio', { name: 'فاتح' }).check();
    await hostPage.getByTestId('create-room').click(); await expect(hostPage.getByRole('heading', { name: 'ردهة المباراة' })).toBeVisible();
    const code = (await hostPage.locator('bdi[dir="ltr"]').textContent())!; await capture(hostPage, 'lobby-empty', 1440, 900, hostPage.getByTestId('start-match'));
    const joinPlayer = async (context: typeof horizontal, name: string) => { const page = await context.newPage(); await page.goto(`${baseURL}/`); await page.getByLabel('رمز الغرفة').fill(code); await page.getByRole('button', { name: 'انضم إلى غرفة' }).click(); await page.getByLabel(/اسم اللاعب/).fill(name); await page.getByRole('button', { name: 'دخول الغرفة' }).click(); await page.getByTestId('ready').click(); return page; };
    const horizontalPage = await joinPlayer(horizontal, 'أفقي'); const verticalPage = await joinPlayer(vertical, 'عمودي'); await expect(hostPage.getByTestId('start-match')).toBeEnabled(); await capture(hostPage, 'lobby-ready', 1440, 900, hostPage.getByTestId('start-match')); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'dark'); document.documentElement.dataset.theme = 'dark'; }); await capture(hostPage, 'lobby-ready-dark', 1440, 900, hostPage.getByTestId('start-match')); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'light'); document.documentElement.dataset.theme = 'light'; });
    const audiencePage = await audience.newPage(); await audiencePage.goto(`${baseURL}/room/${code}/display`); await expect(audiencePage.locator('.stage')).toBeVisible();
    await hostPage.getByTestId('start-match').click(); await hostPage.goto(`${baseURL}/room/${code}/host`); await expect(hostPage.getByRole('button', { name: 'جهّز الجولة' })).toBeVisible(); await capture(hostPage, 'host-round-setup-390', 390, 844); await capture(hostPage, 'host-round-setup-768', 768, 1024, hostPage.getByRole('button', { name: 'جهّز الجولة' })); await capture(hostPage, 'host-round-setup-1024', 1024, 768, hostPage.getByRole('button', { name: 'جهّز الجولة' })); await capture(hostPage, 'host-round-setup-1280', 1280, 720, hostPage.getByRole('button', { name: 'جهّز الجولة' })); await capture(hostPage, 'host-round-setup-1920', 1920, 1080, hostPage.getByRole('button', { name: 'جهّز الجولة' })); await capture(hostPage, 'host-round-setup', 1440, 900, hostPage.getByRole('button', { name: 'جهّز الجولة' })); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'dark'); document.documentElement.dataset.theme = 'dark'; }); await capture(hostPage, 'host-round-setup-dark-768', 768, 1024, hostPage.getByRole('button', { name: 'جهّز الجولة' })); await capture(hostPage, 'host-round-setup-dark-1024', 1024, 768, hostPage.getByRole('button', { name: 'جهّز الجولة' })); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'light'); document.documentElement.dataset.theme = 'light'; }); await hostPage.evaluate(() => { document.documentElement.style.fontSize = '200%'; }); await capture(hostPage, 'host-200-percent', 1024, 768, hostPage.getByRole('button', { name: 'جهّز الجولة' })); await hostPage.evaluate(() => { document.documentElement.style.fontSize = ''; });
    await hostPage.getByRole('button', { name: 'جهّز الجولة' }).click(); await awaitHost('CELL_SELECTION'); await expect(audiencePage.getByText('بانتظار اختيار المضيف للخلية التالية')).toBeVisible(); await expect(audiencePage.locator('.question-band')).not.toBeVisible(); await capture(audiencePage, 'audience-selection-1024', 1024, 576, audiencePage.locator('.stage-board')); await capture(audiencePage, 'audience-selection', 1280, 720, audiencePage.locator('.stage-board')); await capture(audiencePage, 'audience-selection-1920', 1920, 1080, audiencePage.locator('.stage-board'));
    await horizontalPage.goto(`${baseURL}/room/${code}/play`); await verticalPage.goto(`${baseURL}/room/${code}/play`); await capturePlayer(horizontalPage, 'player-ready-320', 320, 568); await capturePlayer(horizontalPage, 'player-ready', 390, 844);
    await selectCell(0); await expect(hostPage.getByTestId('countdown')).toHaveText(/^\d{2}:\d{2}$/); await expect(audiencePage.getByTestId('countdown')).toHaveText(/^\d{2}:\d{2}$/); await expect.poll(() => audiencePage.getByTestId('countdown').textContent()).not.toBe('00:20'); await capture(hostPage, 'host-question-768', 768, 1024); await capture(hostPage, 'host-question-1024', 1024, 768, hostPage.getByRole('button', { name: 'إيقاف مؤقت' })); await capture(hostPage, 'host-question', 1440, 900, hostPage.getByRole('button', { name: 'إيقاف مؤقت' }));
    await capturePlayer(horizontalPage, 'player-open-320', 320, 568); await capturePlayer(horizontalPage, 'player-open', 390, 844); await horizontalPage.getByRole('button', { name: /اضغط الآن/ }).click(); await awaitHost('FIRST_ANSWER'); await expect(verticalPage.locator('.buzzer')).toHaveAttribute('data-state', 'locked'); await capturePlayer(horizontalPage, 'player-first-320', 320, 568); await capturePlayer(horizontalPage, 'player-first', 390, 844); await capturePlayer(verticalPage, 'player-locked-320', 320, 568); await capturePlayer(verticalPage, 'player-locked', 390, 844); await expect(audiencePage.locator('.question-band')).toBeVisible(); await capture(audiencePage, 'audience-question-1024', 1024, 576, audiencePage.locator('.question-band')); await capture(audiencePage, 'audience-question', 1280, 720, audiencePage.locator('.question-band')); await capture(audiencePage, 'audience-question-1920', 1920, 1080, audiencePage.locator('.question-band')); await hostPage.getByRole('button', { name: 'إجابة خاطئة' }).click(); await awaitHost('OPPONENT_CHANCE'); await expect(verticalPage.getByRole('button', { name: /اضغط الآن/ })).toBeEnabled(); await capturePlayer(verticalPage, 'player-opponent-320', 320, 568); await capturePlayer(verticalPage, 'player-opponent', 390, 844); await verticalPage.getByRole('button', { name: /اضغط الآن/ }).click(); await awaitHost('FIRST_ANSWER');
    await hostPage.getByRole('button', { name: 'إجابة صحيحة' }).click(); await awaitHost('CELL_SELECTION'); await capture(hostPage, 'host-judgment-768', 768, 1024); await capture(hostPage, 'host-judgment-1024', 1024, 768, hostPage.getByRole('button', { name: 'اختر حرفًا من اللوحة' })); await capture(hostPage, 'host-judgment', 1440, 900, hostPage.getByRole('button', { name: 'اختر حرفًا من اللوحة' })); await hostPage.getByTestId('correction-trigger').click(); const correction = hostPage.getByTestId('correction-dialog'); await correction.getByTestId('cell-0-0').click(); await correction.getByRole('textbox', { name: 'سبب التصحيح' }).fill('تحقق من أثر التصحيح'); await correction.getByRole('button', { name: 'معاينة التصحيح' }).click(); await expect(hostPage.getByTestId('correction-review')).toContainText('الأثر التابع'); await capture(hostPage, 'host-correction-768', 768, 1024); await capture(hostPage, 'host-correction-1024', 1024, 768, hostPage.getByRole('button', { name: 'تأكيد التصحيح' })); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'dark'); document.documentElement.dataset.theme = 'dark'; }); await capture(hostPage, 'host-correction-dark', 1440, 900, hostPage.getByRole('button', { name: 'تأكيد التصحيح' })); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'light'); document.documentElement.dataset.theme = 'light'; }); await hostPage.getByRole('button', { name: 'إلغاء التصحيح' }).click(); await awaitHost('CELL_SELECTION'); await hostPage.getByTestId('correction-trigger').click(); const confirmedCorrection = hostPage.getByTestId('correction-dialog'); await confirmedCorrection.getByTestId('cell-0-0').click(); await confirmedCorrection.getByTestId('correction-owner-horizontal').click(); await confirmedCorrection.getByRole('textbox', { name: 'سبب التصحيح' }).fill('تصحيح الملكية لمسار الجولة'); await confirmedCorrection.getByRole('button', { name: 'معاينة التصحيح' }).click(); await confirmedCorrection.getByRole('button', { name: 'تأكيد التصحيح' }).click(); await awaitHost('CELL_SELECTION'); await capture(audiencePage, 'audience-award-1024', 1024, 576, audiencePage.locator('.stage-board')); await capture(audiencePage, 'audience-award', 1280, 720, audiencePage.locator('.stage-board')); await capture(audiencePage, 'audience-award-1920', 1920, 1080, audiencePage.locator('.stage-board'));
    for (let q = 1; q < 5; q++) { await selectCell(q); await horizontalPage.getByRole('button', { name: /اضغط الآن/ }).click(); await awaitHost('FIRST_ANSWER'); await hostPage.getByRole('button', { name: 'إجابة صحيحة' }).click(); await awaitHost(q === 4 ? 'ROUND_COMPLETE' : 'CELL_SELECTION'); }
    await expect(audiencePage.locator('.stage[data-state="ROUND_COMPLETE"]')).toBeVisible(); await capture(audiencePage, 'audience-round-win-1024', 1024, 576, audiencePage.locator('.stage-board')); await capture(audiencePage, 'audience-round-win', 1280, 720, audiencePage.locator('.stage-board')); await audiencePage.evaluate(() => localStorage.setItem('huroof-theme', 'dark')); await audiencePage.reload(); await capture(audiencePage, 'audience-round-win-dark', 1920, 1080, audiencePage.locator('.stage-board'));
    await hostPage.goto(`${baseURL}/room/${code}/results`); await capture(hostPage, 'results-ongoing', 1440, 900, hostPage.getByRole('link', { name: 'العودة إلى لوحة المضيف' })); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'dark'); document.documentElement.dataset.theme = 'dark'; }); await capture(hostPage, 'results-ongoing-dark', 1440, 900, hostPage.getByRole('link', { name: 'العودة إلى لوحة المضيف' })); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'light'); document.documentElement.dataset.theme = 'light'; });
    await horizontal.setOffline(true); await expect(horizontalPage.getByRole('heading', { name: 'انقطع الاتصال' })).toBeVisible(); await capturePlayer(horizontalPage, 'player-offline-320', 320, 568); await capturePlayer(horizontalPage, 'player-offline', 390, 844); await horizontal.setOffline(false); await expect.poll(() => horizontalPage.evaluate(() => navigator.onLine)).toBe(true); await expect(horizontalPage.getByRole('heading', { name: 'انقطع الاتصال' })).not.toBeVisible(); await capturePlayer(horizontalPage, 'player-reconnected-320', 320, 568); await capturePlayer(horizontalPage, 'player-reconnected', 390, 844); await horizontalPage.evaluate(() => { localStorage.setItem('huroof-theme', 'dark'); document.documentElement.dataset.theme = 'dark'; }); await capturePlayer(horizontalPage, 'player-reconnected-dark-320', 320, 568);
    await hostPage.goto(`${baseURL}/how-to-play`); await capture(hostPage, 'rules', 1440, 900); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'dark'); document.documentElement.dataset.theme = 'dark'; }); await capture(hostPage, 'rules-dark', 1440, 900); await hostPage.evaluate(() => { localStorage.setItem('huroof-theme', 'light'); document.documentElement.dataset.theme = 'light'; }); await hostPage.goto(`${baseURL}/questions`); await expect(hostPage).toHaveURL(/\/admin\/questions$/); await expect(hostPage.getByRole('heading', { name: 'لا تملك صلاحية الوصول إلى الاستوديو الإداري.' })).toBeVisible(); await capture(hostPage, 'admin-access-unavailable-tablet', 1024, 768); await hostPage.goto(`${baseURL}/questions/new`); await expect(hostPage).toHaveURL(/\/admin\/questions\/new$/); await expect(hostPage.getByRole('heading', { name: 'لا تملك صلاحية الوصول إلى الاستوديو الإداري.' })).toBeVisible(); await capture(hostPage, 'admin-editor-access-unavailable', 1440, 900);
  } finally { await Promise.all([host.close(), horizontal.close(), vertical.close(), audience.close()]); }
});

test('captures current category phone and display states with loaded Arabic typography and reduced motion', async ({ browser, baseURL }) => {
  test.setTimeout(90_000); await mkdir(evidence, { recursive: true });
  const host = await browser.newContext(); const horizontal = await browser.newContext(); const vertical = await browser.newContext(); const audience = await browser.newContext();
  try {
    const hostPage = await host.newPage();
    await hostPage.goto(`${baseURL}/host/new?kind=categories&mode=classic&demo=1&category=tahadani-006&category=tahadani-007`);
    await expect.poll(() => hostPage.evaluate(() => document.fonts.check('400 16px "IBM Plex Sans Arabic"'))).toBe(true);
    await hostPage.getByTestId('create-room').click();
    await expect(hostPage.getByRole('heading', { name: 'ردهة المباراة' })).toBeVisible();
    const code = (await hostPage.locator('.lobby-room-code bdi').textContent())!;
    const join = async (context: typeof horizontal, name: string) => {
      const page = await context.newPage(); await page.goto(`${baseURL}/`); await page.getByLabel('رمز الغرفة').fill(code); await page.getByRole('button', { name: 'انضم إلى غرفة' }).click(); await page.getByLabel('اسم اللاعب').fill(name); await page.getByRole('button', { name: 'دخول الغرفة' }).click(); await page.getByTestId('ready').click(); return page;
    };
    const horizontalPage = await join(horizontal, 'الفريق الأخضر'); await join(vertical, 'الفريق الأحمر');
    const audiencePage = await audience.newPage(); await audiencePage.goto(`${baseURL}/room/${code}/display`); await expect(audiencePage.locator('.stage[data-state="LOBBY"]')).toBeVisible();
    await hostPage.getByTestId('start-match').click(); await hostPage.goto(`${baseURL}/room/${code}/host`); await hostPage.getByRole('button', { name: 'جهّز الجولة' }).click(); await expect(hostPage.locator('.host-page[data-state="CELL_SELECTION"]')).toBeVisible();
    await expect(hostPage.locator('.host-board .game-board__cell-label--category:visible').first()).toBeVisible();
    await capture(hostPage, 'category-host-selection-390', 390, 844, hostPage.getByRole('button', { name: 'تكبير اللوحة' }));
    await capture(audiencePage, 'category-audience-selection-1920', 1920, 1080, audiencePage.locator('.stage-board'));
    await hostPage.locator('.host-board .game-board__button:visible[data-testid="cell-0-0"]').click(); await expect(hostPage.locator('.host-page[data-state="QUESTION_READING"]')).toBeVisible();
    await expect(audiencePage.locator('.question-band')).toBeVisible(); await capture(audiencePage, 'category-audience-question-1920', 1920, 1080, audiencePage.locator('.question-band'));
    await horizontalPage.goto(`${baseURL}/room/${code}/play`); await horizontalPage.emulateMedia({ reducedMotion: 'reduce' }); await expect.poll(() => horizontalPage.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches)).toBe(true); await expect(horizontalPage.locator('.buzzer')).toHaveCSS('transition-duration', '0s'); await capturePlayer(horizontalPage, 'category-player-reduced-motion-390', 390, 844);
  } finally { await Promise.all([host.close(), horizontal.close(), vertical.close(), audience.close()]); }
});
