import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import Ajv2020 from 'ajv/dist/2020.js';
import { AUTHORING_VERSION, createReleaseManifest, indexedDuplicateClusters, makePolicies, makeSlots, partitionSlots, promoteDraft, readinessForPack, validateSlots, type ReviewReceipt, type V2Draft } from '../src/question-bank-v2.js';
import { simulateAuthoringPacks } from '../scripts/simulate-authoring-v2.js';
import { validateAuthoring } from '../scripts/authoring-v2.js';

const root = process.cwd();
const categories = (JSON.parse(await readFile(join(root, 'content/categories/categories.json'), 'utf8')) as { categories: Array<{ id: string; displayNameAr: string; sourceMode: string; sourcePolicy: string; classicCompatibility: string }> }).categories;
const policies = makePolicies(categories); const slots = makeSlots(categories); const parts = partitionSlots(slots);
test('v2 partitions every category exactly once with exactly 20,832 backlog slots', () => { assert.equal(categories.length, 62); assert.equal(policies.length, 62); assert.equal(parts.classic.length, 17_808); assert.equal(parts.image.length, 1_344); assert.equal(parts.charades.length, 1_680); assert.equal(slots.length, 20_832); assert.equal(new Set(policies.map((policy) => policy.categoryId)).size, 62); assert.deepEqual(validateSlots(slots, policies), []); });
test('classic and image slots are letter/difficulty balanced while charades have no target letter', () => { for (const categoryId of new Set(parts.classic.map((slot) => slot.categoryId))) { const scoped = parts.classic.filter((slot) => slot.categoryId === categoryId); assert.equal(scoped.length, 336); for (const letter of new Set(scoped.map((slot) => slot.targetLetter))) for (const difficulty of ['easy', 'medium', 'hard']) assert.equal(scoped.filter((slot) => slot.targetLetter === letter && slot.difficulty === difficulty).length, 4); } for (const slot of parts.image) assert.ok(slot.state === 'blocked_media' && !('promptAr' in slot)); for (const slot of parts.charades) assert.ok(!slot.targetLetter); });
test('slots cannot validate as v2 drafts and generated schemas constrain drafts to draft status', async () => { const draftSchema = JSON.parse(await readFile(join(root, 'content/question-bank-v2/schemas/classic-question-draft.v2.schema.json'), 'utf8')); const AjvConstructor = Ajv2020 as unknown as new (options: Record<string, unknown>) => { compile: (input: object) => (value: unknown) => boolean }; const validator = new AjvConstructor({ strict: false }).compile(draftSchema); assert.equal(validator(parts.classic[0]), false); const candidate = draft(); assert.equal(validator(candidate), true); assert.equal(validator({ ...candidate, status: 'approved' }), false); });
function draft(overrides: Partial<V2Draft> = {}): V2Draft { return { id: 'd1', schemaVersion: AUTHORING_VERSION, locale: 'ar-KW', categoryId: 'tahadani-006', targetLetter: 'ا', headerAr: 'اختبار', promptAr: 'ما الكوكب الثالث من الشمس؟', canonicalAnswer: 'الأرض', acceptedAnswers: ['الأرض'], acceptDefiniteArticle: true, difficulty: 'easy', questionType: 'text', explanationAr: null, status: 'draft', sourcePacketIds: ['p1'], temporal: { kind: 'stable', checkedAt: '2026-09-03', validUntil: null }, provenance: { runId: 'r', attemptId: 'a', templateVersion: 't', method: 'model_assisted', model: 'gpt' }, ...overrides }; }
const receipts: ReviewReceipt[] = ['fact', 'arabic', 'relevance', 'duplicate', 'temporal'].map((kind): ReviewReceipt => ({ receiptId: `r-${kind}`, itemId: 'd1', kind: kind as ReviewReceipt['kind'], reviewer: 'fixture', reviewedAt: '2026-09-03', policyVersion: AUTHORING_VERSION, verdict: 'pass', evidence: 'fixture' }));
test('only promotion creates approved records and it gates source, review and expiry', () => { const policy = policies.find((entry) => entry.categoryId === 'tahadani-006')!; assert.equal(promoteDraft(draft(), policy, [{ packetId: 'p1', checkedAt: '2026-09-03' }], receipts, '2026-09-03').approved.status, 'approved'); assert.throws(() => promoteDraft(draft({ sourcePacketIds: [] }), policy, [], receipts, '2026-09-03'), /Missing source/); assert.throws(() => promoteDraft(draft({ temporal: { kind: 'dated', checkedAt: '2026-09-01', validUntil: '2026-09-02' } }), policy, [{ packetId: 'p1', checkedAt: '2026-09-03' }], receipts, '2026-09-03'), /expired/); assert.throws(() => promoteDraft(draft(), policy, [{ packetId: 'p1', checkedAt: '2026-09-03' }], receipts.filter((r) => r.kind !== 'arabic'), '2026-09-03'), /arabic/); });
test('religious specialist and image rights policies are stronger gates', () => { const religious = policies.find((policy) => policy.categoryId === 'tahadani-057')!; const religiousDraft = draft({ categoryId: religious.categoryId, sourcePacketIds: ['p1', 'p2'] }); assert.equal(religious.review.specialist, true); assert.throws(() => promoteDraft(religiousDraft, religious, [{ packetId: 'p1', checkedAt: '2026-09-03' }, { packetId: 'p2', checkedAt: '2026-09-03' }], receipts, '2026-09-03'), /specialist/); const imagePolicies = policies.filter((policy) => policy.modality === 'image'); assert.equal(imagePolicies.length, 4); assert.ok(imagePolicies.every((policy) => policy.review.rights && policy.readiness.classicEligible === false)); });
test('release manifests reject unresolved duplicate clusters and ineligible items', () => { assert.throws(() => createReleaseManifest([], policies, 1, '2026-09-03'), /duplicate/); assert.throws(() => createReleaseManifest([{ id: 'bad', categoryId: 'tahadani-006', targetLetter: 'ا', modality: 'charades', status: 'approved', validUntil: null, policyVersion: AUTHORING_VERSION, schemaValid: true, policyValid: true }], policies, 0, '2026-09-03'), /ineligible/); });
test('indexed duplicate detection avoids all-pairs candidate generation', () => { const corpus = Array.from({ length: 2_000 }, (_, index) => ({ id: `d-${index}`, promptAr: `سؤال فريد رقم ${index} عن معلومة مختلفة`, canonicalAnswer: `جواب ${index}` })); const started = performance.now(); const result = indexedDuplicateClusters(corpus); assert.ok(performance.now() - started < 1_500); assert.ok(result.candidates.length < corpus.length * 10); });
test('runtime readiness is selected-pack scoped and excludes expired, blocked and global-only inventory', () => { const items = Array.from({ length: 28 * 8 }, (_, index) => ({ id: String(index), categoryId: 'tahadani-006', targetLetter: ['ا','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','ه','و','ي'][Math.floor(index / 8)] as V2Draft['targetLetter'], modality: 'classic' as const, status: 'approved' as const, validUntil: null, policyVersion: AUTHORING_VERSION, schemaValid: true, policyValid: true })); assert.equal(readinessForPack(items, ['tahadani-006'], '2026-09-03').playable, true); assert.equal(readinessForPack([...items, { ...items[0], id: 'expired', categoryId: 'tahadani-007', validUntil: '2026-09-02' }], ['tahadani-007'], '2026-09-03').playable, false); });
test('one thousand seeded selected-pack simulations keep non-classic and invalid inventory out', () => { assert.equal(simulateAuthoringPacks().rounds, 1_000); });
test('v2 plans and reports are deterministic across two validation runs', async () => { const slotPath = join(root, 'content/question-bank-v2/slots/classic.v2.jsonl'); const reportPath = join(root, 'content/question-bank-v2/reports/authoring-validation.v2.json'); const beforeSlots = await readFile(slotPath, 'utf8'); await validateAuthoring('2026-09-03'); const firstReport = await readFile(reportPath, 'utf8'); await validateAuthoring('2026-09-03'); assert.equal(await readFile(slotPath, 'utf8'), beforeSlots); assert.equal(await readFile(reportPath, 'utf8'), firstReport); });
