import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { approve, contentHash, simulateNonApprovedInventory, sourceHash, validateAutomatedReceipts, type Candidate, type ReviewReceipt } from '../scripts/question-bank-v3-review.js';
import { importCandidatesV3 } from '../scripts/import-question-candidates-v3.js';
import { reviewCandidatesV3 } from '../scripts/review-questions-v3.js';
import { readAcademyPackets, validateAcademyPackets } from '../scripts/academy-packets-v3-next.js';
import { readSpecializedPackets, validateSpecializedPackets } from '../scripts/specialized-packets-v3.js';
import { resolveV31Catalog, simulateActualApprovedCorpus, validateExtensionCatalog, validateV31CategoryArtifacts } from '../scripts/question-bank-v3.1.js';

function candidate(): Candidate { return { candidateId: 'v3-test', sourceVersion: 'v1', sourceId: 'draft-test', playable: { id: 'draft-test', promptAr: 'سؤال محدد', sources: [{ url: 'https://official.example/claim' }], explanationAr: null }, state: 'ready_for_human', disposition: 'ready_for_human', dispositionReason: 'test', provenance: { importedAt: '2026-09-04', sourcePath: 'test', sourceHash: 'source' } }; }
function receipt(item: Candidate, actorKind: ReviewReceipt['actorKind'] = 'human', principalId: string | null = 'auth:fake_12345678', createdAt = '2026-09-04') { return { receiptId: 'r', actorKind, principalId, itemId: item.candidateId, state: 'ready_for_human' as const, verdict: 'pass' as const, contentHash: contentHash(item), sourceHash: sourceHash(item), policyHash: 'caller-supplied-policy', createdAt, evidence: 'Caller-supplied evidence.' }; }
test('v3 imports all playable fields as 280 v1 plus four v2.1 candidates and corrects the specified revisions', async () => { const imported = await importCandidatesV3(); assert.equal(imported.length, 284); assert.equal(imported.filter((item) => item.sourceVersion === 'v1').length, 280); assert.equal(imported.filter((item) => item.sourceVersion === 'v2.1').length, 4); const wrong = imported.find((item) => item.sourceId === 'draft-037')!; assert.equal(wrong.disposition, 'needs_evidence'); assert.equal(wrong.playable.promptAr, 'ما اسم قوة الجاذبية المؤثرة في جسم؟'); assert.doesNotMatch(String(wrong.playable.promptAr), /مقاومة الجسم لتغيير حركته/); const geography = imported.find((item) => item.sourceId.includes('huroof-002'))!; assert.equal(geography.disposition, 'ready_for_human'); assert.equal(geography.playable.promptAr, 'ما اسم الاهتزاز الذي يحدث عندما تنزلق كتل من الأرض فجأة؟'); for (const id of ['draft-033','draft-035','draft-043','draft-046','draft-051','draft-071','draft-083','draft-117','draft-134','draft-136','draft-146','draft-163','draft-165','draft-182','draft-204','draft-225','draft-264','draft-266']) assert.ok(imported.find((item) => item.sourceId === id)); assert.equal(imported.find((item) => item.sourceId === 'draft-180')?.playable.canonicalAnswer, 'علم'); assert.equal(imported.find((item) => item.sourceId === 'draft-230')?.playable.canonicalAnswer, 'لعبة'); });
test('Academy cohort has exactly one persisted, hash-bound evidence packet per candidate and no mass template prompts', async () => { const imported = await importCandidatesV3(); const cohort = imported.filter((item) => ['tahadani-006', 'tahadani-013'].includes(String(item.playable.categoryId))); const packets = await readAcademyPackets(); assert.equal(cohort.length, 207); assert.equal(cohort.filter((item) => item.state === 'evidence_ready' && item.evidencePacketId).length, 207); assert.equal(packets.length, 207); assert.deepEqual(await validateAcademyPackets(imported, packets, '2026-09-04'), []); assert.equal(cohort.filter((item) => String(item.playable.promptAr).includes('ما المصطلح الذي يصف')).length, 0); assert.equal(cohort.filter((item) => item.playable.explanationAr !== null).length, 0); assert.equal(new Set(cohort.map((item) => item.playable.canonicalAnswer)).size, cohort.length); });
test('specialized cohort stores compact, offline-verifiable direct evidence before ready-for-human state', async () => { const imported = await importCandidatesV3(); const packets = await readSpecializedPackets(); const specialized = imported.filter((item) => !['tahadani-006', 'tahadani-013'].includes(String(item.playable.categoryId))); assert.equal(specialized.length, 77); assert.equal(specialized.filter((item) => item.state === 'ready_for_human').length, 77); assert.deepEqual(await validateSpecializedPackets(imported, packets, '2026-09-04'), []); assert.ok(packets.every((packet) => packet.httpStatus === 200 && packet.sourceExcerptBase64 && packet.sourceExcerptSha256)); assert.equal(imported.find((item) => item.sourceId === 'draft-103')?.playable.canonicalAnswer, 'زنبق'); assert.doesNotMatch(String(imported.find((item) => item.sourceId === 'draft-103')?.playable.promptAr), /زنبق/); assert.equal(imported.find((item) => item.sourceId === 'draft-044')?.playable.canonicalAnswer, 'جدار حماية'); assert.equal(imported.find((item) => item.sourceId === 'draft-127')?.playable.canonicalAnswer, 'شفرة تعمية'); assert.equal(imported.find((item) => item.sourceId === 'draft-169')?.playable.canonicalAnswer, 'ظربان'); });
test('all caller-supplied approval material fails closed without an authenticated adapter', () => { const item = candidate(); const evil = { ...item, playable: { ...item.playable, sources: [{ url: 'https://official-looking.evil.example/claim' }] } }; const stale = { ...receipt(item), contentHash: 'stale' }; const duplicated = [receipt(item), { ...receipt(item), actorKind: 'specialist' as const }, { ...receipt(item), actorKind: 'rights' as const }]; const attempts: Array<[Candidate, { requiresSpecialist: boolean; requiresRights: boolean }, ReviewReceipt[]]> = [[item, { requiresSpecialist: false, requiresRights: false }, [receipt(item)]], [evil, { requiresSpecialist: false, requiresRights: false }, [receipt(evil)]], [item, { requiresSpecialist: true, requiresRights: true }, duplicated], [item, { requiresSpecialist: false, requiresRights: false }, [stale, receipt(item, 'human', 'auth:fake_12345678', '1900-01-01')]]]; for (const [attempted, policy, receipts] of attempts) assert.throws(() => approve(attempted, policy, receipts), /authenticated review adapter not configured/); assert.equal(item.state, 'ready_for_human'); });
test('automated receipt artifacts are current, hash-bound, and reject duplicate or stale records', async () => { const candidates = await importCandidatesV3(); await reviewCandidatesV3(); const receipts = (await readFile(join(process.cwd(), 'content/question-bank-v3/reports/automated-receipts.v3.jsonl'), 'utf8')).trim().split(/\r?\n/).map((line) => JSON.parse(line) as ReviewReceipt); assert.deepEqual(validateAutomatedReceipts(candidates, receipts, '2026-09-04'), []); assert.ok(validateAutomatedReceipts(candidates, [{ ...receipts[0], createdAt: '1900-01-01' }, receipts[0], ...receipts.slice(1)], '2026-09-04').some((issue) => /duplicate|invalid/.test(issue))); });
test('review report derives zero approved/released from candidate state and records all dispositions', async () => { await importCandidatesV3(); const report = await reviewCandidatesV3(); assert.equal(report.imported, 284); assert.equal(report.approved, 0); assert.equal(report.receipts.human, 0); assert.equal(Object.values(report.dispositions).reduce((sum, value) => sum + value, 0), 284); const output = JSON.parse(await readFile(join(process.cwd(), 'content/question-bank-v3/reports/review.v3.json'), 'utf8')); assert.equal(output.released, 0); });
test('one thousand readiness samples never turn non-approved candidates into runtime inventory', async () => { const outcome = simulateNonApprovedInventory(await importCandidatesV3(), 1000); assert.deepEqual(outcome, { rounds: 1000, sampled: 1000, runtimeEligible: 0, seed: 0x6a09e667 }); });
test('offline packet validation rejects forged excerpt, expired evidence, and a rehashed evil canonical URL', async () => { const imported = await importCandidatesV3(); const packets = await readSpecializedPackets(); const packet = packets[0]!; assert.ok((await validateSpecializedPackets(imported, [{ ...packet, sourceExcerptBase64: Buffer.from('forged').toString('base64') }], '2026-09-04')).some((issue) => /invalid|coverage/.test(issue))); assert.ok((await validateSpecializedPackets(imported, [{ ...packet, temporal: { ...packet.temporal, validUntil: '1900-01-01' } }], '2026-09-04')).some((issue) => /invalid|coverage/.test(issue))); const { normalizedEvidenceSha256: discardedHash, ...evilUnsigned } = { ...packet, canonicalUrl: 'https://official-looking.evil.example/claim' }; void discardedHash; const evil = { ...evilUnsigned, normalizedEvidenceSha256: createHash('sha256').update(JSON.stringify(evilUnsigned)).digest('hex') }; assert.ok((await validateSpecializedPackets(imported, [evil], '2026-09-04')).some((issue) => /invalid|coverage/.test(issue))); });
test('v3.1 emits exactly one canonical file for each resolved category and its aggregate is the union', async () => { await importCandidatesV3(); const catalog = await resolveV31Catalog(); assert.equal(catalog.length, 66); assert.equal(new Set(catalog.map((item) => item.filename)).size, 66); assert.deepEqual(await validateV31CategoryArtifacts(), []); const aggregate = (await readFile(join(process.cwd(), 'content/question-bank-v3/aggregate.v3.1.jsonl'), 'utf8')).trim().split(/\r?\n/).map((line) => JSON.parse(line)); assert.equal(aggregate.length, 284); assert.ok(aggregate.every((item) => item.workflow.state !== 'approved' && item.workflow.state !== 'released')); assert.deepEqual(simulateActualApprovedCorpus(aggregate, 1000), { rounds: 1000, sampled: 1000, approvedInventory: 0, runtimePlayable: 0, seed: 0x9e3779b9 }); });
test('v3.1 serialization preserves nested candidate fields and rejects empty or forged workflow', async () => { const imported = await importCandidatesV3(); const source = imported.find((item) => item.sourceId === 'draft-001')!; const path = join(process.cwd(), 'content/question-bank-v3/categories/tahadani-006.jsonl'); const row = JSON.parse((await readFile(path, 'utf8')).split(/\r?\n/).find((line) => line.includes(source.candidateId))!); assert.deepEqual(row.workflow, { state: source.state, disposition: source.disposition, dispositionReason: source.dispositionReason }); assert.deepEqual(row.temporal, source.playable.temporal); assert.deepEqual(row.provenance, source.provenance); assert.deepEqual(row.legacySources, { authority: 'unverified_legacy_metadata', sources: source.playable.sources }); assert.deepEqual(row.difficultyRationale, source.difficultyRationale); const forged = { ...row, workflow: {} }; const original = await readFile(path, 'utf8'); const { writeFile } = await import('node:fs/promises'); try { await writeFile(path, JSON.stringify(forged) + '\n'); assert.ok((await validateV31CategoryArtifacts()).some((issue) => issue.includes('schema-invalid'))); } finally { await writeFile(path, original); } });
test('extension resolver rejects missing, extra, fifth, and malformed pinned extension records', async () => { const extension = JSON.parse(await readFile(join(process.cwd(), 'content/categories/extensions/huroof-v2.1.json'), 'utf8')); assert.equal(validateExtensionCatalog(extension).length, 4); assert.throws(() => validateExtensionCatalog({ ...extension, categories: extension.categories.slice(0, 3) })); assert.throws(() => validateExtensionCatalog({ ...extension, categories: [...extension.categories, extension.categories[0]] })); assert.throws(() => validateExtensionCatalog({ ...extension, categories: [{ ...extension.categories[0], id: 'huroof-005' }, ...extension.categories.slice(1)] })); assert.throws(() => validateExtensionCatalog({ ...extension, categories: [{ ...extension.categories[0], runtimeVisibility: true }, ...extension.categories.slice(1)] })); });
