import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { AUTHORING_V21, createReleaseManifestV21, indexedDuplicateClustersV21, isRealDate, makePoliciesV21, makeSlotsV21, partitionSlotsV21, promoteDraftV21, resolveCatalogs, runtimeCatalogV21, seededScenarioV21, simulateV21, validateDraftsV21, type CatalogCategory } from '../src/question-bank-v2.1.js';
import { realDrafts, sourcePackets } from '../scripts/v2.1-content.js';

const root = process.cwd();
const legacy = (JSON.parse(await readFile(join(root, 'content/categories/categories.json'), 'utf8')) as { categories: CatalogCategory[] }).categories;
const extension = (JSON.parse(await readFile(join(root, 'content/categories/extensions/huroof-v2.1.json'), 'utf8')) as { categories: CatalogCategory[] }).categories;
const catalogs = resolveCatalogs(legacy, extension); const policies = makePoliciesV21(catalogs.authoring); const slots = makeSlotsV21(catalogs.authoring); const packets = sourcePackets();
const registry = new Set(['nasa-solar-system','iau-nomenclature','usgs-earthquakes','noaa-ocean-service','wmo-weather','doha-historical-dictionary','arabic-academy-cairo','nccal-kuwait','unesco-kuwait-diwaniya','unesco-kuwait-ich']);

test('v2.1 leaves the 62 runtime catalog ordered and makes exactly four proposed authoring additions', () => {
  assert.equal(runtimeCatalogV21(legacy, extension).length, 62); assert.equal(catalogs.authoring.length, 66); assert.deepEqual(catalogs.runtime, legacy); assert.ok(catalogs.extension.every((category) => category.activation === 'authoring_only' && category.runtimeVisibility === false && category.catalogStatus === 'proposed' && category.origin === 'v2.1_extension' && !('legacyIndex' in category) && category.cover?.state === 'proposed' && category.cover.publishable === false));
});
test('v2.1 slots are append-only and partitions total 22,176', () => { const parts = partitionSlotsV21(slots); assert.equal(policies.length, 66); assert.equal(parts.classic.length, 19_152); assert.equal(parts.image.length, 1_344); assert.equal(parts.charades.length, 1_680); assert.equal(slots.length, 22_176); for (const id of ['huroof-001','huroof-002','huroof-003','huroof-004']) assert.equal(slots.filter((slot) => slot.categoryId === id).length, 336); });
test('each materialized sourced draft binds one compatible slot and its own checked evidence packet', () => { const drafts = realDrafts(); assert.equal(drafts.length, 4); for (const id of ['huroof-001','huroof-002','huroof-003','huroof-004']) assert.equal(drafts.filter((draft) => draft.categoryId === id).length, 1); assert.ok(packets.every((packet) => /^[a-f0-9]{64}$/.test(packet.contentHash) && packet.claimLocators.length === 1 && packet.claimLocators[0] === packet.sourceUrl)); assert.deepEqual(validateDraftsV21(drafts, slots, policies, packets, registry), []); });
test('real calendar dates reject impossible dates', () => { assert.equal(isRealDate('2026-02-30'), false); assert.equal(isRealDate('2026-09-03'), true); });
test('proposed categories cannot be promoted or released', () => { const draft = realDrafts()[0]; assert.throws(() => promoteDraftV21(draft, slots, policies, packets, registry, [], '2026-09-03'), /Proposed|Missing/); assert.throws(() => createReleaseManifestV21([], policies, '2026-09-03', { catalogHash: 'x', policyHash: 'x', receiptHash: 'x', sourceHash: 'x', mediaHash: 'x' }), /nonempty/); });
test('release hashes whole approved records and rejects malformed roots', () => { const item = { id: 'approved-v21-fixture', categoryId: 'tahadani-001', slotId: 'slot-fixture', targetLetter: 'ا' as const, modality: 'classic' as const, status: 'approved' as const, approvedAt: '2026-09-03', validUntil: null, policyVersion: AUTHORING_V21 as '2.1.0', schemaValid: true as const, policyValid: true as const, contentHash: 'a'.repeat(64), sourcePacketIds: ['packet'], reviewReceiptIds: ['fact'] }; const roots = { catalogHash: 'b'.repeat(64), policyHash: 'c'.repeat(64), receiptHash: 'd'.repeat(64), sourceHash: 'e'.repeat(64), mediaHash: 'f'.repeat(64) }; const first = createReleaseManifestV21([item], policies, '2026-09-03', roots); const mutated = createReleaseManifestV21([{ ...item, targetLetter: 'ب' }], policies, '2026-09-03', roots); assert.notEqual(first.approvedContentHash, mutated.approvedContentHash); assert.throws(() => createReleaseManifestV21([item], policies, '2026-09-03', { ...roots, sourceHash: 'bad' }), /roots/); });
test('duplicate index has a deterministic bounded hot bucket beyond the full planned catalog size', () => { const corpus = Array.from({ length: 20_832 }, (_, index) => ({ id: `d-${index}`, promptAr: `ما الاسم المتكرر المشترك للكشف ${index}`, canonicalAnswer: `جواب ${index}` })); const result = indexedDuplicateClustersV21(corpus); assert.equal(result.bucketCap, 50); assert.ok(result.candidates.length <= corpus.length * result.bucketCap); });
test('seeded v2.1 simulations vary and never make invalid inventory playable', () => { const first = seededScenarioV21(17); assert.deepEqual(first, seededScenarioV21(17)); assert.notDeepEqual(first, seededScenarioV21(18)); const result = simulateV21(); assert.equal(result.rounds, 1_000); assert.ok(result.distinctOutcomes > 1); assert.equal(result.invalidInventoryPlayable, false); assert.equal(AUTHORING_V21, '2.1.0'); });
