import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { applyQ4800Plan, buildQ4800Plan, decodeRestDocument, parseQ4800Markdown, Q4800_EXPECTED_SOURCE_SHA256, rollbackQ4800Plan, type Q4800ApplyAdapter, type Q4800GateApproval, type Q4800Plan, type Q4800TrustedInputs, type ReleaseDocument, type RestDocument } from "../scripts/q4800-owner-approved-release.js";
import { canonicalJson } from "../scripts/firestore-release-canonical.js";
import { createCategoryQuestionSelection, createMatchQuestionSelection } from "../src/features/game/runtime/question-selector.js";
import { normalizeArabic, SUPPORTED_LETTERS } from "../src/question-bank.js";

const source = "C:/Users/User/Downloads/ALL_QUESTIONS (2).md";
const live = "output/q4800-20260912/live-base.json";
const prior = "output/firebase-activation-20260911/approval-question-backup.json";
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const equal = (left: unknown, right: unknown) => canonicalJson(left) === canonicalJson(right);
/** Direct raw-source extractor kept separate from the production parser. */
function rawSourcePrompts(markdown: string) { const headings = [...markdown.matchAll(/^#### ([A-Za-z0-9_-]+)$/gmu)]; return new Map(headings.map((heading, index) => { const raw = markdown.slice(heading.index!, index + 1 < headings.length ? headings[index + 1]!.index! : markdown.length); const details = raw.indexOf("<details>"); if (details < 0) throw new Error(`raw fixture lacks details: ${heading[1]}`); return [heading[1]!, raw.slice(heading[0]!.length, details).trim()] as const; })); }
type Stored = { path: string; data: Record<string, unknown> };

class FixtureAdapter implements Q4800ApplyAdapter {
  readonly docs = new Map<string, Stored>(); readonly created: string[] = []; readonly batchSizes: number[] = []; blockPrefix?: string;
  target = { projectId: "huroof-a3ee7", databaseId: "(default)", locationId: "me-central2", type: "FIRESTORE_NATIVE" };
  async getTarget() { return this.target; }
  async read(paths: string[]) { return paths.map((path) => { const value = this.docs.get(path); return value ? { path, exists: true, data: value.data } : { path, exists: false }; }); }
  async create(documents: ReleaseDocument[]) { this.batchSizes.push(documents.length); if (this.blockPrefix && documents.some((document) => document.path.startsWith(this.blockPrefix!))) throw new Error(`fixture interruption ${this.blockPrefix}`); for (const document of documents) { if (this.docs.has(document.path)) throw new Error(`create collision ${document.path}`); this.docs.set(document.path, { path: document.path, data: document.data }); this.created.push(document.path); } }
  async listDescendants(prefix: string) { return [...this.docs.values()].filter((document) => document.path === prefix || document.path.startsWith(`${prefix}/`)).map((document) => ({ path: document.path, exists: true, data: document.data })); }
  async activateCapturedPointer(request: Parameters<Q4800ApplyAdapter["activateCapturedPointer"]>[0]) { const pointer = this.docs.get("runtime/activeRelease"), root = this.docs.get(request.releaseRoot.path), verification = this.docs.get(request.verificationReceipt.path); if (!pointer || !equal(pointer.data, request.expectedPointer) || !root || !equal(root.data, request.releaseRoot.data) || !verification || !equal(verification.data, request.verificationReceipt.data) || this.docs.has(request.activationReceipt.path)) throw new Error("fixture CAS failed"); this.docs.set(request.activationReceipt.path, { path: request.activationReceipt.path, data: request.activationReceipt.data }); this.docs.set(request.pointer.path, { path: request.pointer.path, data: request.pointer.data }); }
  async rollbackCapturedPointer(request: Parameters<Q4800ApplyAdapter["rollbackCapturedPointer"]>[0]) { const pointer = this.docs.get("runtime/activeRelease"); if (!pointer || !equal(pointer.data, request.expectedPointer) || this.docs.has(request.rollbackReceipt.path)) throw new Error("fixture rollback CAS failed"); this.docs.set(request.rollbackReceipt.path, { path: request.rollbackReceipt.path, data: request.rollbackReceipt.data }); this.docs.set(request.restorePointer.path, { path: request.restorePointer.path, data: request.restorePointer.data }); }
}

let fixturePromise: Promise<{ plan: Q4800Plan; inputs: Q4800TrustedInputs; captured: { documents: RestDocument[] } }> | undefined;
async function fixture() {
  fixturePromise ??= (async () => { const [markdown, capturedBytes, previous] = await Promise.all([readFile(source, "utf8"), readFile(live), readFile(prior, "utf8")]); const priorDocs = JSON.parse(previous) as RestDocument[]; const plan = buildQ4800Plan(markdown, capturedBytes, priorDocs, { sourcePath: source }); const gate: Q4800GateApproval = { status: "PASS", planCanonicalSha256: sha(canonicalJson(plan)), runnerSha256: sha(await readFile(fileURLToPath(new URL("../scripts/q4800-owner-approved-release.ts", import.meta.url)))), sourceSha256: plan.source.sha256, capturedBaseSha256: plan.capturedBase.sha256 }; return { plan, inputs: { markdown, capturedBytes, prior: priorDocs, gate }, captured: JSON.parse(capturedBytes.toString("utf8")) as { documents: RestDocument[] } }; })();
  return fixturePromise;
}
async function seededAdapter() { const { plan, inputs, captured } = await fixture(); const adapter = new FixtureAdapter(); const pointer = decodeRestDocument((JSON.parse(inputs.capturedBytes.toString("utf8")) as { pointer: RestDocument }).pointer); adapter.docs.set(pointer.path, { path: pointer.path, data: pointer.data }); for (const document of captured.documents.map(decodeRestDocument)) adapter.docs.set(document.path, { path: document.path, data: document.data }); const needed = new Set(plan.intakeDocuments.flatMap((document) => { const paths = document.data.lineage as { priorSourcePaths?: unknown }; return Array.isArray(paths.priorSourcePaths) ? paths.priorSourcePaths.filter((path): path is string => typeof path === "string") : []; })); for (const document of inputs.prior.map(decodeRestDocument)) if (needed.has(document.path)) adapter.docs.set(document.path, { path: document.path, data: document.data }); return { adapter, plan, inputs }; }

// Preparation contracts.
test("Q4800 parser retains every source ID, exact raw prompt, aliases, and review notes", async () => { const markdown = await readFile(source, "utf8"); const records = parseQ4800Markdown(markdown); const rawPrompts = rawSourcePrompts(markdown); assert.equal(records.length, 4800); assert.equal(new Set(records.map((record) => record.sourceId)).size, 4800); assert.deepEqual(Object.fromEntries([...new Set(records.map((record) => record.categoryId))].sort().map((id) => [id, records.filter((record) => record.categoryId === id).length])), Object.fromEntries(Array.from({ length: 12 }, (_, i) => [`tahadani-${String(i + 51).padStart(3, "0")}`, 400]))); assert.ok(records.every((record) => record.promptAr === rawPrompts.get(record.sourceId) && !/^\d\s/u.test(record.promptAr) && record.rawMarkdown.startsWith(`#### ${record.sourceId}`) && record.reviewProvenance.trim().length > 0)); const restaurant = records.find((record) => record.sourceId === "x400-tahadani-058-060")!; assert.equal(restaurant.promptAr, "في أي مدينة بفلوريدا نشأت برغر كينغ باسمها المعروف سنة 1954؟"); const lineup = records.find((record) => record.sourceId === "x400-tahadani-061-001")!; assert.ok(lineup.promptAr.includes("الأسماء المعروضة: إيكر كاسياس — **؟**") && lineup.promptAr.includes("ترتيب القائمة ليس ادعاءً بالمراكز أو الخطة التكتيكية.")); });
test("Q4800 plan is deterministic, owner-bound, additive, and keeps exact base children", async () => { const { plan, captured } = await fixture(); const capturedQuestionCount = captured.documents.map(decodeRestDocument).filter((document) => document.path.includes("/questions/")).length; assert.equal(plan.source.sha256, Q4800_EXPECTED_SOURCE_SHA256); assert.equal(plan.ownerApproval.authority, "owner_approval"); assert.equal(plan.ownerApproval.specialistReview, "not_claimed"); assert.equal(plan.reconciliation.exactCarried.length + plan.reconciliation.changedVersions.length + plan.reconciliation.additions.length, 4800); assert.equal(plan.reconciliation.runtimeAdded.length + plan.reconciliation.runtimeExisting.length, 4800); assert.equal(plan.release.approvedCount, capturedQuestionCount + plan.reconciliation.runtimeAdded.length); assert.equal(plan.reconciliation.runtimeExisting.length, 374); assert.equal(plan.reconciliation.runtimeAdded.length, 4426); assert.ok(Object.values(plan.release.readiness).every((value) => value.playable)); assert.equal(plan.intakeDocuments.length, 4800); assert.equal(plan.release.documents.filter((document) => document.path.includes("/inventory/")).length, captured.documents.map(decodeRestDocument).filter((document) => document.path.includes("/inventory/")).length); const releasedByGameplay = new Map<string, Array<{ acceptedAnswers: string[] }>>(); for (const document of plan.release.documents.filter((document) => document.path.includes("/questions/"))) { const question = document.data as { categoryId: string; promptAr: string; canonicalAnswer: string; acceptedAnswers: string[] }; const key = `${question.categoryId}\u0000${normalizeArabic(question.promptAr)}\u0000${normalizeArabic(question.canonicalAnswer)}`; releasedByGameplay.set(key, [...(releasedByGameplay.get(key) ?? []), question]); } for (const record of parseQ4800Markdown((await fixture()).inputs.markdown)) { const key = `${record.categoryId}\u0000${normalizeArabic(record.promptAr)}\u0000${normalizeArabic(record.canonicalAnswer)}`; assert.ok(releasedByGameplay.get(key)?.some((question) => record.acceptedAnswers.every((alias) => question.acceptedAnswers.some((released) => normalizeArabic(released) === normalizeArabic(alias)))), `released aliases missing for ${record.sourceId}`); } });
test("numeric literal answer remains category-selectable but is outside Huroof queues", () => { const questions = [{ id: "a-numeric", categoryId: "a", modality: "classic" as const, targetLetter: "", answerConceptId: "a-numeric", headerAr: "أ", promptAr: "كم؟", canonicalAnswer: "2026", acceptedAnswers: ["2026"] }, ...SUPPORTED_LETTERS.map((letter, index) => ({ id: `a-${index}`, categoryId: "a", modality: "classic" as const, targetLetter: letter, answerConceptId: `a-${index}`, headerAr: "أ", promptAr: `س${index}`, canonicalAnswer: `${letter}${index}`, acceptedAnswers: [String(index)] })), ...Array.from({ length: 14 }, (_, index) => ({ id: `b-${index}`, categoryId: "b", modality: "classic" as const, targetLetter: "ب", answerConceptId: `b-${index}`, headerAr: "ب", promptAr: `ص${index}`, canonicalAnswer: `ب${index}`, acceptedAnswers: [String(index)] }))]; const category = createCategoryQuestionSelection(questions, { categories: ["a", "b"], modality: "classic", seed: 1 }); assert.ok(category.queues.a.includes("a-numeric")); const huroof = createMatchQuestionSelection(questions, { categories: ["a"], modality: "classic", seed: 1, reservePerLetter: 1 }); assert.ok(!Object.values(huroof.queues).flat().includes("a-numeric")); });
test("Q4800 preparation refuses source or captured-pointer drift", async () => { const { inputs } = await fixture(); assert.throws(() => buildQ4800Plan(`${inputs.markdown}\n`, inputs.capturedBytes, inputs.prior), /SHA-256/); const changed = JSON.parse(inputs.capturedBytes.toString("utf8")); changed.pointer.fields.releaseId.stringValue = "other"; assert.throws(() => buildQ4800Plan(inputs.markdown, Buffer.from(JSON.stringify(changed)), inputs.prior), /pointer/); });

// Gate-mandated apply safety contracts.
test("apply creates exact bounded successor, writes root after children, and exact rerun is a no-op", async () => { const { adapter, plan, inputs } = await seededAdapter(); const first = await applyQ4800Plan(plan, adapter, inputs); assert.equal(first.idempotent, false); const rootIndex = adapter.created.indexOf(`releases/${plan.release.releaseId}`); assert.ok(rootIndex > 0); assert.ok(adapter.batchSizes.every((size) => size <= 400) && adapter.batchSizes.includes(400)); assert.ok(adapter.created.slice(0, rootIndex).every((path) => path !== `releases/${plan.release.releaseId}`)); assert.ok(equal(adapter.docs.get("runtime/activeRelease")!.data, { releaseId: plan.release.releaseId, approvedCount: plan.release.approvedCount, approvedJsonlSha256: plan.release.approvedJsonlSha256, catalogSha256: plan.release.catalogSha256, documentRootSha256: plan.release.documentRootSha256, sourceManifestSha256: plan.release.sourceManifestSha256, publicationAuthority: "owner_approval", ownerApprovalPath: `contentOwnerApprovals/${plan.ownerApproval.runId}` })); const creates = adapter.created.length; const second = await applyQ4800Plan(plan, adapter, inputs); assert.equal(second.idempotent, true); assert.equal(adapter.created.length, creates); });
test("apply resumes exact partial bounded creates after each immutable stage barrier and rejects malformed barriers", async () => { const { adapter, plan, inputs } = await seededAdapter(); for (const document of plan.intakeDocuments.slice(0, 200)) adapter.docs.set(document.path, { path: document.path, data: document.data }); const result = await applyQ4800Plan(plan, adapter, inputs); assert.equal(result.idempotent, false); for (const prefix of [`contentOwnerApprovals/${plan.ownerApproval.runId}`, `releases/${plan.release.releaseId}`, "q4800VerificationReceipts/"]) { const { adapter: interrupted } = await seededAdapter(); interrupted.blockPrefix = prefix; await assert.rejects(() => applyQ4800Plan(plan, interrupted, inputs), /fixture interruption/); interrupted.blockPrefix = undefined; assert.equal((await applyQ4800Plan(plan, interrupted, inputs)).idempotent, false); } const { adapter: malformed } = await seededAdapter(); const parent = `questionImports/q4800-v2-${plan.source.sha256}`; malformed.docs.set(parent, { path: parent, data: { immutable: true } }); await assert.rejects(() => applyQ4800Plan(plan, malformed, inputs), /recursive inventory|commit barrier/); assert.equal(malformed.created.length, 0); });
test("apply rejects target, tampered plan or gate, stale pointer, changed predecessor/source, conflicts, and nested orphan before writing", async () => { const { adapter, plan, inputs } = await seededAdapter(); adapter.target.projectId = "wrong"; await assert.rejects(() => applyQ4800Plan(plan, adapter, inputs), /target/); assert.equal(adapter.created.length, 0); const { adapter: tamperedAdapter } = await seededAdapter(); const tampered = structuredClone(plan); (tampered.release.documents.find((document) => document.path.includes("/questions/"))!.data.promptAr as string) = "tampered"; await assert.rejects(() => applyQ4800Plan(tampered, tamperedAdapter, inputs), /deterministic/); assert.equal(tamperedAdapter.created.length, 0); const { adapter: badGateAdapter } = await seededAdapter(); await assert.rejects(() => applyQ4800Plan(plan, badGateAdapter, { ...inputs, gate: { ...inputs.gate, runnerSha256: "bad" } }), /Gate receipt/); assert.equal(badGateAdapter.created.length, 0); const { adapter: stale } = await seededAdapter(); stale.docs.set("runtime/activeRelease", { path: "runtime/activeRelease", data: { releaseId: "later" } }); await assert.rejects(() => applyQ4800Plan(plan, stale, inputs), /pointer changed/); assert.equal(stale.created.length, 0); const { adapter: changedBase } = await seededAdapter(); const basePath = `releases/${plan.capturedBase.releaseId}`; changedBase.docs.set(basePath, { path: basePath, data: { altered: true } }); await assert.rejects(() => applyQ4800Plan(plan, changedBase, inputs), /recursive inventory/); assert.equal(changedBase.created.length, 0); const { adapter: changedSource } = await seededAdapter(); const lineagePath = (plan.intakeDocuments.find((document) => document.data.sourceId === plan.reconciliation.exactCarried[0])!.data.lineage as { priorSourcePaths: string[] }).priorSourcePaths[0]!; changedSource.docs.set(lineagePath, { path: lineagePath, data: { altered: true } }); await assert.rejects(() => applyQ4800Plan(plan, changedSource, inputs), /lineage/); assert.equal(changedSource.created.length, 0); const { adapter: collision } = await seededAdapter(); const intake = plan.intakeDocuments[0]!; collision.docs.set(intake.path, { path: intake.path, data: { altered: true } }); await assert.rejects(() => applyQ4800Plan(plan, collision, inputs), /recursive inventory/); assert.equal(collision.created.length, 0); const { adapter: orphan } = await seededAdapter(); orphan.docs.set(`releases/${plan.release.releaseId}/questions/missingParent/ghost/nested`, { path: `releases/${plan.release.releaseId}/questions/missingParent/ghost/nested`, data: { unexpected: true } }); await assert.rejects(() => applyQ4800Plan(plan, orphan, inputs), /recursive inventory/); assert.equal(orphan.created.length, 0); });
test("conditional rollback restores only the exact successor pointer", async () => { const { adapter, plan, inputs } = await seededAdapter(); await applyQ4800Plan(plan, adapter, inputs); const rollback = await rollbackQ4800Plan(plan, adapter, inputs); assert.equal(rollback.rolledBack, true); assert.ok(equal(adapter.docs.get("runtime/activeRelease")!.data, plan.capturedBase.pointer)); adapter.docs.set("runtime/activeRelease", { path: "runtime/activeRelease", data: { releaseId: "later" } }); await assert.rejects(() => rollbackQ4800Plan(plan, adapter, inputs), /rollback CAS/); });
