import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { generateBoard } from '../src/features/game/domain/board.js';
import { answerConceptIdV32, assertReleaseReportV32, exactNormalizeV1, fuzzyNormalizeV1, indexedPairsV32, promptSimilarityV1, validateQuestionBankV32, type CategoryPolicyV32, type QuestionV32 } from '../src/question-bank-v3.2.js';
import { createMatchQuestionSelection, selectMatchQuestion } from '../src/features/game/runtime/question-selector.js';
import { migrateQuestionPilotsV32 } from '../scripts/migrate-question-pilots-v3.2.js';
import { reportV32AliasRemediation } from '../scripts/report-v32-alias-remediation.js';

const policy = (max: 1 | 2 = 1): CategoryPolicyV32 => ({ categoryId: 'tahadani-001', modality: 'classic', supportedAnswerLetters: [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'], grossTarget: { preferred: 336, minimum: 300 }, standaloneEligible: true, playability: 'letter_board', reusePolicy: max === 2 ? { kind: 'closed_domain', maxPerConcept: 2 } : { kind: 'default', maxPerConcept: 1 } });
const question = (id: string, answer = 'محمد صلاح', prompt = `سؤال مميز عن ${id} مع خمس كلمات واضحة`, patch: Partial<QuestionV32> = {}): QuestionV32 => ({ id, schemaVersion: '3.2.0', categoryId: 'tahadani-001', modality: 'classic', headerAr: 'عنوان', promptAr: prompt, canonicalAnswer: answer, acceptedAnswers: [`${answer} البديل`], answerConceptId: answerConceptIdV32(answer), targetLetter: 'م', facetId: `facet:${id}`, claimIds: [`claim:${id}`], evidencePacketIds: [`packet:${id}`], state: 'ready_for_human', ...patch });
const findings = (questions: QuestionV32[], policies = [policy()]) => validateQuestionBankV32({ questions, policies }).findings;

test('exact normalizer preserves Arabic boundaries while fuzzy remains suggestions-only', () => {
  assert.equal(exactNormalizeV1(' أَحْمَدـ،  علي '), 'احمد علي'); assert.notEqual(exactNormalizeV1('هدى'), exactNormalizeV1('هدي')); assert.notEqual(exactNormalizeV1('مدرسة'), exactNormalizeV1('مدرسه')); assert.notEqual(exactNormalizeV1('رؤوف'), exactNormalizeV1('رووف')); assert.equal(fuzzyNormalizeV1('هدى'), fuzzyNormalizeV1('هدي'));
});
test('identity, prompt, alias, and charades invariants are concept-aware', () => {
  const base = question('a'); assert.ok(findings([base, { ...base }]).some((f) => f.code === 'duplicate_id')); assert.ok(findings([base, { ...question('b'), promptAr: base.promptAr }]).some((f) => f.code === 'exact_prompt_concept_duplicate'));
  const eye = { ...question('c', 'عين', base.promptAr), answerConceptId: 'concept:eye' }; const spring = { ...question('d', 'عين', base.promptAr), answerConceptId: 'concept:spring' }; assert.ok(findings([eye, spring]).some((f) => f.code === 'exact_prompt_overlapping_alias_duplicate'));
  const alias = { ...question('e', 'صلاح'), acceptedAnswers: ['محمد صلاح'], answerConceptId: 'concept:other' }; assert.ok(findings([base, alias]).some((f) => f.code === 'alias_reuse_requires_disposition'));
  assert.ok(findings([{ ...base, acceptedAnswers: [base.canonicalAnswer] }]).some((f) => f.code === 'duplicate_normalized_alias_within_question'));
  const charades = question('charades', 'محمد صلاح', 'مثل لاعب كرة مشهور من دون كلام', { modality: 'charades', targetLetter: undefined, facetId: undefined, performanceFacetId: 'performance:charades', claimIds: [], evidencePacketIds: [] }); assert.ok(findings([base, charades]).some((f) => f.code === 'cross_modality_concept_reuse'));
});
test('default and closed-domain concept caps are fail-closed', () => {
  const one = question('one', 'الكويت'); const two = { ...question('two', 'الكويت', 'معلومة مستقلة عن الكويت مختلفة كليا هنا'), claimIds: ['claim:two'], evidencePacketIds: ['packet:two'] }; const three = { ...question('three', 'الكويت', 'وجه ثالث مستقل للكويت مختلف للغاية هنا'), claimIds: ['claim:three'], evidencePacketIds: ['packet:three'] };
  assert.ok(findings([one, two]).some((f) => f.code === 'concept_reuse_cap_exceeded')); assert.equal(findings([one, two], [policy(2)]).filter((f) => f.code === 'concept_reuse_cap_exceeded').length, 0); assert.ok(findings([one, two, three], [policy(2)]).some((f) => f.code === 'concept_reuse_cap_exceeded'));
});
test('projected-size duplicate candidates are indexed rather than all-pairs', () => {
  const projected = Array.from({ length: 672 }, (_, index) => question(`scale-${index}`, `جواب${index}`, `تمييز${index} فريد غير متشابه للنطاق`)); const report = validateQuestionBankV32({ questions: projected, policies: [policy()] }); assert.ok(report.indexedCandidatePairs < projected.length * (projected.length - 1) / 2); assert.ok(report.quadraticPairsAvoided > 0);
});
test('trigram similarity and indexed recall retain a 65-item common stem without a hot-bucket drop', () => {
  const corpus = Array.from({ length: 65 }, (_, index) => question(`stem-${index}`, `جواب ${index}`, `هذا نص مشترك طويل للغاية لاختبار تطابق ثلاثيات الحروف مع اختلاف رقم ${index.toString().padStart(2, '0')}`)); assert.ok(promptSimilarityV1(corpus[0].promptAr, corpus[1].promptAr) >= .9); const pairs = new Set(indexedPairsV32(corpus).map(([left, right]) => [left.id, right.id].sort().join('|'))); assert.ok(pairs.has('stem-0|stem-1'));
});
test('migration is append-only in meaning and reconciles 408 / 418', async () => { const manifest = await migrateQuestionPilotsV32(); assert.equal(manifest.reconciliation.questions, 408); assert.equal(manifest.reconciliation.evidence, 418); const saved = JSON.parse(await readFile('content/question-bank-v3/v3.2/migration-manifest.v3.1-to-v3.2.json', 'utf8')); assert.equal(saved.reconciliation.approved, 0); });
test('alias remediation inventory is non-mutating and assigns every preserved redundant alias to later ownership', async () => { const remediation = await reportV32AliasRemediation(); assert.equal(remediation.questionCount, 408); assert.equal(remediation.duplicateCanonicalAcceptedAnswerCount, 410); assert.ok(remediation.records.every((record) => record.action.includes('retain this v3.2 migration record unchanged'))); });
test('actual 16 visible + 9 surprise boards have no repeated IDs/concepts in 10,000 deterministic matches', () => {
  const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'].slice(0, 25); const questions = letters.flatMap((letter) => Array.from({ length: 3 }, (_, round) => ({ id: `${letter}-${round}`, categoryId: 'tahadani-001', modality: 'classic' as const, targetLetter: letter, answerConceptId: `concept:${letter}-${round}`, headerAr: 'عنوان', promptAr: 'سؤال', canonicalAnswer: 'جواب', acceptedAnswers: ['جواب'] })));
  for (let seed = 0; seed < 10_000; seed += 1) { let selection = createMatchQuestionSelection(questions, { categories: ['tahadani-001'], modality: 'classic', seed, reservePerLetter: 3 }); const ids = new Set<string>(); const concepts = new Set<string>(); for (let round = 0; round < 3; round += 1) { const board = generateBoard(seed + round, letters); const visible = board.cells.filter((cell) => cell.kind === 'letter').map((cell) => cell.visibleValue); const roundLetters = [...visible, ...letters.filter((letter) => !visible.includes(letter)).slice(0, 9)]; for (const letter of roundLetters) { const result = selectMatchQuestion(questions, selection, letter); selection = result.selection; assert.ok(!ids.has(result.question.id)); assert.ok(!concepts.has(result.question.answerConceptId)); ids.add(result.question.id); concepts.add(result.question.answerConceptId); } } }
});
test('runtime queues honor category/modality and fail closed after their concept reserve is consumed', () => {
  const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'].slice(0, 25); const inventory = letters.flatMap((letter) => Array.from({ length: 3 }, (_, index) => ({ id: `a-${letter}-${index}`, categoryId: 'a', modality: 'classic' as const, targetLetter: letter, answerConceptId: `a:${letter}:${index}`, headerAr: 'عنوان', promptAr: 'سؤال', canonicalAnswer: 'جواب', acceptedAnswers: ['جواب'] }))); const selection = createMatchQuestionSelection(inventory, { categories: ['a'], modality: 'classic', seed: 1 }); const first = selectMatchQuestion(inventory, selection, letters[0]); assert.match(first.question.id, /^a-/); assert.throws(() => createMatchQuestionSelection(inventory, { categories: [], modality: 'classic', seed: 1 }), /explicit category/i); assert.throws(() => createMatchQuestionSelection(inventory, { categories: ['a'], modality: 'charades', seed: 1 }), /Separate-mode/i);
});
test('release report is hash-bound and blocks errors/review-required findings', () => { const clean = validateQuestionBankV32({ questions: [question('release')], policies: [policy()] }); assert.doesNotThrow(() => assertReleaseReportV32(clean, clean.contentHash)); assert.throws(() => assertReleaseReportV32({ ...clean, contentHash: 'x' }, clean.contentHash), /mismatch/i); const blocked = validateQuestionBankV32({ questions: [question('x'), { ...question('y'), promptAr: question('x').promptAr }], policies: [policy()] }); assert.throws(() => assertReleaseReportV32(blocked, blocked.contentHash), /errors|review-required/i); });
