import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { answerInitial, normalizeArabic, selectBoardLetters, sha256File, SUPPORTED_LETTERS, type Question } from '../src/question-bank.js';
import { simulateBoards } from '../scripts/simulate-boards.js';
import { validateQuestions } from '../scripts/validate-question-bank.js';
import { assertMappingInventory, verifyCopiedAsset } from '../scripts/import-tahadani-categories.js';
import { assertSeedTopicIntent, PILOT_SEEDS } from '../scripts/generate-pilot-drafts.js';

const root = process.cwd();
const schema = JSON.parse(await readFile(join(root, 'content/questions/question.schema.json'), 'utf8'));
function question(overrides: Partial<Question> = {}): Question {
  return { id: 'q-test', schemaVersion: 1, locale: 'ar-KW', categoryId: 'tahadani-006', targetLetter: 'ج', headerAr: 'في المعلومات العامة', promptAr: 'ما الاسم العربي لجزء النبات الذي يثبت النبات في التربة؟', canonicalAnswer: 'جذر', acceptedAnswers: ['جذر'], acceptDefiniteArticle: true, difficulty: 'easy', questionType: 'text', explanationAr: null, sources: [{ title: 'مصدر', publisher: 'ناشر', url: 'https://www.example.org/reference', accessedAt: '2026-09-03' }], temporal: { kind: 'stable', verifiedAt: '2026-09-03', validUntil: null }, media: null, status: 'draft', authoring: { method: 'model_assisted', model: 'gpt-5.6-terra', createdAt: '2026-09-03T00:00:00Z' }, review: { factReviewer: null, languageReviewer: null, reviewedAt: null, notes: null }, ...overrides };
}
test('Arabic normalization removes diacritics, tatweel and normalizes hamza', () => { assert.equal(normalizeArabic('  أَجـْرٌ  '), 'اجر'); assert.equal(answerInitial('إبرة'), 'ا'); });
test('optional definite article is considered only for initial matching', () => { assert.equal(answerInitial('الجذر', true), 'ج'); assert.equal(answerInitial('الجذر', false), 'ا'); });
test('conflicting accepted answer initial is rejected', () => { const result = validateQuestions([question({ acceptedAnswers: ['جذر', 'مركبة'] })], schema); assert.ok(result.issues.some((issue) => issue.code === 'initial_mismatch')); });
test('malformed prompt, source URL, expired fact and invalid media are rejected', () => { const result = validateQuestions([question({ promptAr: '', sources: [{ title: 'x', publisher: 'x', url: 'http://localhost/x', accessedAt: '2026-09-03' }], temporal: { kind: 'dated', verifiedAt: '2026-09-03', validUntil: '2026-09-02' }, questionType: 'image', media: null })], schema); for (const code of ['schema', 'empty_text', 'source_url', 'expired_dated_fact', 'invalid_media']) assert.ok(result.issues.some((issue) => issue.code === code), code); });
test('pinned v1 dates reject later records and dated facts expire against explicit asOf', () => {
  const later = question({ sources: [{ title: 'x', publisher: 'x', url: 'https://example.org/x', accessedAt: '2026-09-04' }], temporal: { kind: 'stable', verifiedAt: '2026-09-04', validUntil: null }, review: { factReviewer: 'fact', languageReviewer: 'language', reviewedAt: '2026-09-04', notes: null } });
  assert.ok(validateQuestions([later], schema, '2026-09-04').issues.some((issue) => issue.code === 'schema'));
  const dated = question({ temporal: { kind: 'dated', verifiedAt: '2026-09-04', validUntil: '2026-09-04' } });
  assert.ok(validateQuestions([dated], schema, '2026-09-05').issues.some((issue) => issue.code === 'expired_dated_fact'));
});
test('headers are required and cannot be embedded at the start of a prompt', () => { const missing = validateQuestions([question({ headerAr: '' })], schema); assert.ok(missing.issues.some((issue) => issue.code === 'missing_header')); const repeated = validateQuestions([question({ headerAr: 'في عالم الحيوان', promptAr: 'في عالم الحيوان، ما الحيوان الذي يوصف بأنه ملك الغابة؟' })], schema); assert.ok(repeated.issues.some((issue) => issue.code === 'header_embedded_in_prompt')); });
test('explanations allow null or player-facing addons but reject review workflow boilerplate', () => { const nullable = validateQuestions([question()], schema); assert.ok(!nullable.issues.some((issue) => issue.code === 'schema')); const addon = validateQuestions([question({ explanationAr: 'تثبت الجذور النبات في التربة.' })], schema); assert.ok(!addon.issues.some((issue) => issue.code === 'workflow_explanation')); const boilerplate = validateQuestions([question({ explanationAr: 'الإجابة المقصودة هي جذر، ويجب أن تخضع الصياغة والمصدر لمراجعة بشرية قبل الاعتماد.' })], schema); assert.ok(boilerplate.issues.some((issue) => issue.code === 'workflow_explanation')); });
test('exact and near duplicates are reported across categories', () => { const first = question(); const second = question({ id: 'q-second', categoryId: 'tahadani-007' }); const third = question({ id: 'q-third', categoryId: 'tahadani-008', targetLetter: 'ب', canonicalAnswer: 'باب', acceptedAnswers: ['باب'] }); const result = validateQuestions([first, second, third], schema); assert.equal(result.exactDuplicates.length, 1); assert.ok(result.nearDuplicates.length >= 1); });
test('drafts are excluded from runtime and insufficient reserve blocks a board', () => { const drafts = SUPPORTED_LETTERS.map((targetLetter, index) => question({ id: `draft-${index}`, targetLetter, canonicalAnswer: targetLetter, acceptedAnswers: [targetLetter] })); const result = validateQuestions(drafts, schema); assert.equal(result.runtimeInventory.length, 0); assert.throws(() => selectBoardLetters(drafts, 1, 8, 5)); });
test('one thousand seeded boards are deterministic and reserve-safe', () => { assert.deepEqual(simulateBoards(1000), { rounds: 1000, questionCount: 224 }); });
test('import receipt preserves 62 contiguous mappings and source bytes', async () => { const receipt = JSON.parse(await readFile(join(root, 'content/categories/import-receipt.json'), 'utf8')); assert.equal(receipt.copiedAssets.length, 62); assert.deepEqual(receipt.duplicateByteGroups, [[1, 59]]); for (const [index, row] of receipt.copiedAssets.entries()) { assert.equal(row.legacyIndex, index + 1); assert.equal(row.sourceSha256, row.destinationSha256); const destination = join(root, row.destinationPath); assert.equal(await sha256File(destination), row.destinationSha256); } });
test('audited source manifest and mapping hashes have not drifted', async () => { assert.equal(await sha256File('D:/projects/tahadani/category_manifest.json'), '5c787c9982eba35aaa95211edc571a20ab2ee692de0399b62a508fb3cf759318'); assert.equal(await sha256File('D:/projects/tahadani/top_50_categories.md'), 'e40af8f08f5095fa24c2c66f35d2b329cb285d6b60d02f3298dd6622f8cf213d'); });
test('pilot seeds declare topic-owned categories instead of positional assignment', () => { const seeds = Object.values(PILOT_SEEDS).flat(); assert.equal(seeds.length, 280); for (const seed of seeds) assert.doesNotThrow(() => assertSeedTopicIntent(seed)); const categories = new Set(seeds.map((seed) => seed.categoryId)); assert.ok(categories.size >= 8); for (const categoryId of ['tahadani-045', 'tahadani-046', 'tahadani-047', 'tahadani-051']) assert.ok(seeds.some((seed) => seed.categoryId === categoryId)); });
test('missing or extra mappings and source/destination failures stop import checks', async () => { const categories = Array.from({ length: 62 }, (_, index) => ({ index: index + 1, display_name: `فئة ${index + 1}`, slug: 'x', mode: 'trivia', subtype_policy: 'stable_facts' })); const mappings = categories.map((category) => ({ displayName: category.display_name, imageName: 'x.png' })); assert.throws(() => assertMappingInventory(categories, mappings.slice(1))); assert.throws(() => assertMappingInventory(categories, [...mappings, mappings[0]])); const source = join(root, '.question-bank-test-source'); const destination = join(root, '.question-bank-test-destination'); await writeFile(source, 'source'); await writeFile(destination, 'different'); await assert.rejects(() => verifyCopiedAsset(source, destination)); await assert.rejects(() => verifyCopiedAsset(join(root, '.missing-source'), destination)); await Promise.all([unlink(source), unlink(destination)]); });
