import assert from "node:assert/strict";
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { canonicalJson } from "../scripts/firestore-release-canonical.js";
import { activateProductionRelease, prepareProductionRelease, verifyPreparedProductionRelease, type ActivationRequest, type FirestorePublicationAdapter } from "../scripts/firestore-release-publisher.js";
import { compositeProductionPlan } from "../scripts/firestore-release-publisher.js";
import { buildReviewedMediaCompositeReleasePlan, loadTrustedReviewedAuthority, reviewedGoalSupplementHash, reviewedQuestionContentHash, reviewedSupplementSubjectHash, type ReviewedGoalMedia, type ReviewedGoalSupplement, type TrustedReviewedAuthority } from "../scripts/reviewed-media-composite-release.js";
import { receiptHashV33, receiptSigningPayloadV33, type V33ReviewReceipt, type V33TrustRoot } from "../src/question-bank-v3.3.js";
import type { FirestoreReleasePlan, ReleaseDocument } from "../scripts/build-firestore-release.js";

const h = (x: unknown) => createHash("sha256").update(canonicalJson(x)).digest("hex");
const raw = (x: string) => createHash("sha256").update(x, "utf8").digest("hex");
const now = "2026-09-11T12:00:00.000Z";
const hashDocs = (docs: ReleaseDocument[]) => h(docs.slice().sort((a, b) => a.path.localeCompare(b.path)).map(({ path, data }) => ({ path, data })));

function fixture() {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519"); const roles = ["fact_reviewer", "language_reviewer", "video_rights_reviewer", "image_rights_reviewer"];
  const trust: V33TrustRoot = { now, issuers: { issuer: { keys: { key: publicKey.export({ type: "spki", format: "pem" }).toString() }, roles, reviewers: Object.fromEntries(roles.map((role) => [role, [role]])) } } };
  const authority: TrustedReviewedAuthority = { trust, rawSha256: raw(canonicalJson(trust)) }, media: ReviewedGoalMedia[] = [], questions: any[] = [], receipts: V33ReviewReceipt[] = [];
  const makeReceipt = (question: any, role: string, categoryId: string, nonce: string) => { const receipt: any = { receiptId: `${question.id}:${role}`, version: 1, issuer: "issuer", signerKeyId: "key", reviewerUid: role, reviewerRole: role, authorUid: question.authorUid, reviewRequestNonce: nonce, verdict: "approved", questionId: question.id, categoryId, questionContentHash: question.contentHash, evidenceHash: question.evidenceHash, policyHash: question.policyHash, mediaHash: null, issuedAt: now, receiptHash: "", signature: "" }; receipt.receiptHash = receiptHashV33(receipt); receipt.signature = sign(null, Buffer.from(receiptSigningPayloadV33(receipt)), privateKey).toString("base64"); return receipt as V33ReviewReceipt; };
  for (let n = 1; n <= 99; n += 1) {
    const id = `goal-quiz-2026-${String(n).padStart(3, "0")}`, blur = `goal-quiz-2026:${String(n).padStart(3, "0")}:blur`, clean = `goal-quiz-2026:${String(n).padStart(3, "0")}:clean`;
    const prompt: ReviewedGoalMedia = { mediaId: blur, assetSha256: h(`${id}:blur`), objectName: "", generation: String(n), contentType: "video/mp4", byteSize: 100, width: 854, height: 374, durationSeconds: 2 }; prompt.objectName = `question-media/goal-quiz-2026/assets/${prompt.assetSha256}.mp4`;
    const answer: ReviewedGoalMedia = { ...prompt, mediaId: clean, assetSha256: h(`${id}:clean`), objectName: "" }; answer.objectName = `question-media/goal-quiz-2026/assets/${answer.assetSha256}.mp4`; media.push(prompt, answer);
    const question: any = { id, headerAr: "هدف", promptAr: "من سجل؟", canonicalAnswer: `لاعب ${n}`, acceptedAnswers: [`لاعب ${n}`], answerConceptId: h(`concept:${n}`), authorUid: `author-${n}`, evidenceHash: h(`e:${n}`), policyHash: h(`p:${n}`), contentHash: "", promptMediaId: blur, answerMediaId: clean, reviewReceiptIds: ["fact_reviewer", "language_reviewer", "video_rights_reviewer"].map((role) => `${id}:${role}`) };
    question.contentHash = reviewedQuestionContentHash(question, "goals-2026", "video", prompt, answer); for (const role of ["fact_reviewer", "language_reviewer", "video_rights_reviewer"]) receipts.push(makeReceipt(question, role, "goals-2026", `nonce:${id}:${role}`)); questions.push(question);
  }
  const image: ReviewedGoalMedia = { mediaId: "rebuild-v2-photo-011-001", assetSha256: h("jpeg"), objectName: "", generation: "100", contentType: "image/jpeg", byteSize: 100, width: 640, height: 480 }; image.objectName = `question-media/guess-picture-rebuild-v2/assets/${image.assetSha256}.jpg`; media.push(image);
  const imageQuestion: any = { id: "reviewed-image-001", categoryId: "tahadani-001", headerAr: "صورة", promptAr: "ما هذه؟", canonicalAnswer: "صورة", acceptedAnswers: ["صورة"], answerConceptId: h("image-concept"), authorUid: "image-author", evidenceHash: h("image-e"), policyHash: h("image-p"), contentHash: "", mediaId: image.mediaId, reviewReceiptIds: ["fact_reviewer", "language_reviewer", "image_rights_reviewer"].map((role) => `reviewed-image-001:${role}`) }; imageQuestion.contentHash = reviewedQuestionContentHash(imageQuestion, imageQuestion.categoryId, "image", image); for (const role of ["fact_reviewer", "language_reviewer", "image_rights_reviewer"]) receipts.push(makeReceipt(imageQuestion, role, imageQuestion.categoryId, `nonce:image:${role}`));
  const supplement: ReviewedGoalSupplement = { schemaVersion: "question-media-supplement-v1", category: { id: "goals-2026", labelAr: "من سجل الهدف؟" }, asOf: now, trustRootSha256: authority.rawSha256, reviewReportHash: "", questions, imageQuestions: [imageQuestion], media, receipts, contentHash: "" };
  const report: any = { schemaVersion: "question-media-review-report-v1", supplementSubjectHash: reviewedSupplementSubjectHash(supplement), trustRootSha256: authority.rawSha256, receiptIds: receipts.map((receipt) => receipt.receiptId).sort(), reviewedAt: now }; supplement.reviewReportHash = raw(canonicalJson(report)); supplement.contentHash = reviewedGoalSupplementHash(supplement); const trustedReport = { report, rawSha256: supplement.reviewReportHash };
  const releaseId = "release-base-0123456789", prefix = `releases/${releaseId}/`, catalog = Array.from({ length: 62 }, (_, i) => ({ path: `${prefix}catalogCategories/tahadani-${String(i + 1).padStart(3, "0")}`, data: { id: `tahadani-${String(i + 1).padStart(3, "0")}`, labelAr: `فئة ${i + 1}` } })), baseQuestions = Array.from({ length: 300 }, (_, i) => ({ path: `${prefix}questions/base-${String(i + 1).padStart(3, "0")}`, data: { id: `base-${String(i + 1).padStart(3, "0")}`, categoryId: "tahadani-001" } })), inventory = Array.from({ length: 62 }, (_, i) => ({ path: `${prefix}inventory/tahadani-${String(i + 1).padStart(3, "0")}`, data: { categoryId: `tahadani-${String(i + 1).padStart(3, "0")}`, approvedCount: i === 0 ? 300 : 0 } })), children = [...catalog, ...baseQuestions, ...inventory], documentRootSha256 = hashDocs(children), catalogSha256 = hashDocs(catalog);
  const base: FirestoreReleasePlan = { releaseId, approvedCount: 300, approvedJsonlSha256: h("approved"), catalogSha256, documentRootSha256, sourceManifestSha256: h("source"), asOf: now, reviewNonceClaimHashes: [h("base-nonce")], documents: [...children, { path: `releases/${releaseId}`, data: { releaseId, asOf: now, approvedCount: 300, catalogSha256, documentRootSha256, sourceManifestSha256: h("source"), immutable: true, questionBankVersion: "3.3.0" } }] };
  return { base, supplement, authority, report, trustedReport, privateKey };
}
class Adapter implements FirestorePublicationAdapter {
  docs = new Map<string, Record<string, unknown>>(); async getProjectId() { return "huroof-a3ee7"; } async getDatabaseMetadata() { return { locationId: "me-central2", type: "FIRESTORE_NATIVE" }; } async read(paths: string[]) { return paths.map((path) => ({ path, exists: this.docs.has(path), data: this.docs.get(path) })); } async listPrefix(prefix: string) { const root = prefix.endsWith("/") ? prefix.slice(0, -1) : prefix; return [...this.docs.entries()].filter(([path]) => path === root || path.startsWith(prefix)).map(([path, data]) => ({ path, exists: true, data })); } async claimReviewNonceClaims(docs: ReleaseDocument[]) { for (const doc of docs) { const old = this.docs.get(doc.path); if (old && canonicalJson(old) !== canonicalJson(doc.data)) throw new Error("nonce belongs to another release"); if (!old) this.docs.set(doc.path, structuredClone(doc.data)); } } async create(docs: ReleaseDocument[]) { for (const doc of docs) { if (this.docs.has(doc.path)) throw new Error("exists"); this.docs.set(doc.path, structuredClone(doc.data)); } } async activate(request: ActivationRequest) { if ((this.docs.get("runtime/activeRelease")?.releaseId ?? null) !== request.expectedPreviousReleaseId || this.docs.has(request.activationReceipt.path) || this.docs.has(request.verificationUseReceipt.path)) throw new Error("CAS"); this.docs.set(request.verificationUseReceipt.path, structuredClone(request.verificationUseReceipt.data)); this.docs.set(request.activationReceipt.path, structuredClone(request.activationReceipt.data)); this.docs.set(request.activeRelease.path, structuredClone(request.activeRelease.data)); } }

test("signed goal/video and reviewed image supplement forms one composite and preserves base nonce provenance", () => { const { base, supplement, authority, trustedReport } = fixture(), plan = buildReviewedMediaCompositeReleasePlan(base, supplement, authority, trustedReport); assert.equal(plan.approvedCount, 400); assert.ok(plan.documents.some((doc) => doc.path.endsWith("/questions/reviewed-image-001"))); const root = plan.documents.find((doc) => doc.path === `releases/${plan.releaseId}`)!; assert.deepEqual(root.data.baseReviewNonceClaimHashes, base.reviewNonceClaimHashes); assert.notDeepEqual(plan.reviewNonceClaimHashes, base.reviewNonceClaimHashes); });
test("composite rejects tampered base, stale text/role receipts, unrelated trust keys, altered reports, and reused nonce", () => { const { base, supplement, authority, trustedReport, privateKey } = fixture(); const tampered = { ...base, documents: base.documents.map((doc) => doc.path.endsWith("/questions/base-001") ? { ...doc, data: { ...doc.data, changed: true } } : doc) }; assert.throws(() => buildReviewedMediaCompositeReleasePlan(tampered, supplement, authority, trustedReport), /child commitment/i); const answer: any = structuredClone(supplement); answer.questions[0].canonicalAnswer = "تغيير"; answer.questions[0].acceptedAnswers = ["تغيير"]; answer.contentHash = reviewedGoalSupplementHash(answer); assert.throws(() => buildReviewedMediaCompositeReleasePlan(base, answer, authority, trustedReport), /review report|content commitment|receipts/i); const roles: any = structuredClone(supplement); [roles.questions[0].promptMediaId, roles.questions[0].answerMediaId] = [roles.questions[0].answerMediaId, roles.questions[0].promptMediaId]; roles.contentHash = reviewedGoalSupplementHash(roles); assert.throws(() => buildReviewedMediaCompositeReleasePlan(base, roles, authority, trustedReport), /review report|role\/content/i); const unrelated: any = structuredClone(authority); unrelated.trust.issuers.issuer.keys.key = generateKeyPairSync("ed25519").publicKey.export({ type: "spki", format: "pem" }).toString(); assert.throws(() => buildReviewedMediaCompositeReleasePlan(base, supplement, unrelated, trustedReport), /trusted authority/i); const alteredReport: any = { ...trustedReport, report: { ...trustedReport.report, reviewedAt: "2026-09-11T11:59:59.000Z" } }; assert.throws(() => buildReviewedMediaCompositeReleasePlan(base, supplement, authority, alteredReport), /review report/i); const reused: any = structuredClone(supplement); reused.receipts[1].reviewRequestNonce = reused.receipts[0].reviewRequestNonce; reused.receipts[1].receiptHash = receiptHashV33(reused.receipts[1]); reused.receipts[1].signature = sign(null, Buffer.from(receiptSigningPayloadV33(reused.receipts[1])), privateKey).toString("base64"); reused.contentHash = reviewedGoalSupplementHash(reused); assert.throws(() => buildReviewedMediaCompositeReleasePlan(base, reused, authority, trustedReport), /review report|reuses/i); });
test("normal prepare, exact verify, and CAS activation lifecycle requires a prepared/verified base before a composite", async () => { const { base, supplement, authority, trustedReport } = fixture(), plan = buildReviewedMediaCompositeReleasePlan(base, supplement, authority, trustedReport), adapter = new Adapter(); await assert.rejects(prepareProductionRelease(plan, adapter), /base root.*provenance|base root, publication/i); await prepareProductionRelease(base, adapter); await verifyPreparedProductionRelease(base, adapter); const prepared = await prepareProductionRelease(plan, adapter); assert.ok(prepared.created > 0); const barrier = await verifyPreparedProductionRelease(plan, adapter); await activateProductionRelease(plan, adapter, null, "CHG-composite", barrier); assert.equal(adapter.docs.get("runtime/activeRelease")?.releaseId, plan.releaseId); });
test("composite CLI loader anchors exact canonical authority/report bytes and rejects a changed report", async () => { const { base, supplement, authority, report } = fixture(), folder = join(process.cwd(), "output", `composite-loader-${Date.now()}-${Math.random()}`), trustPath = join(process.cwd(), "output", `composite-trust-${Date.now()}-${Math.random()}.json`); await mkdir(folder, { recursive: true }); const paths = { base: join(folder, "base.json"), supplement: join(folder, "supplement.json"), trust: trustPath, report: join(folder, "report.json") }; try { await Promise.all([writeFile(paths.base, canonicalJson(base)), writeFile(paths.supplement, canonicalJson(supplement)), writeFile(paths.trust, canonicalJson(authority.trust)), writeFile(paths.report, canonicalJson(report))]); const flags = { project: "huroof-a3ee7", database: "(default)", location: "me-central2", "base-plan": paths.base, "base-document-root-sha256": base.documentRootSha256, supplement: paths.supplement, "supplement-content-hash": supplement.contentHash, "review-report": paths.report, "review-report-sha256": supplement.reviewReportHash, "trust-root": paths.trust, "trust-root-sha256": authority.rawSha256 }; const plan = await compositeProductionPlan(flags); assert.equal(plan.approvedCount, 400); await writeFile(paths.report, `${canonicalJson(report)} `); await assert.rejects(compositeProductionPlan(flags), /report SHA-256/i); await writeFile(paths.report, canonicalJson(report)); await writeFile(join(folder, "inside-trust.json"), canonicalJson(authority.trust)); await assert.rejects(loadTrustedReviewedAuthority(join(folder, "inside-trust.json"), authority.rawSha256, [paths.supplement]), /outside/i); } finally { await Promise.all([rm(folder, { recursive: true, force: true }), rm(trustPath, { force: true })]); } });
