import assert from 'node:assert/strict';
import test from 'node:test';
import { initialGameState } from '../../src/features/game/domain/lifecycle.js';
import { generateBoard, revealSurprise } from '../../src/features/game/domain/board.js';
import { prepareLetterReveal, selectQuestionForActiveCell, validateQuestionScope } from './index.js';
import { createMatchQuestionSelection } from '../../src/features/game/runtime/question-selector.js';
import { intentHash, intentReceiptId, projectRoom, reduceIntent, type CanonicalMember, type CanonicalRoom } from './game.js';

const room = (): CanonicalRoom => ({ schemaVersion: 2, roomCode: 'A1B2C3D4', revision: 2, game: { ...initialGameState(), lifecycle: 'QUESTION_READING' }, config: { demo: true, questionSeconds: 20, opponentSeconds: 10, teams: { horizontal: 'أفقي', vertical: 'عمودي' }, releaseId: 'demo-drafts', releaseRootSha256: 'hash', releaseDemoFixture: true }, timer: { deadlineMs: 2_000, buzzOpen: true }, questionCursor: 0 });
const player: CanonicalMember = { uid: 'p1', role: 'player', displayName: 'P', ready: false, active: true, team: 'horizontal' };

test('private fields remain absent from player/audience projections while host gets answer/source', () => {
  const canonical = { ...room(), activeQuestion: { id: 'q', targetLetter: 'ا', headerAr: 'عنوان', promptAr: 'سؤال', canonicalAnswer: 'جواب', acceptedAnswers: ['جواب'], sources: [{ title: 'مصدر' }], review: { secret: true } } };
  const host = projectRoom('r1', canonical, [{ ...player, role: 'host' }], 'host', 'p1', 1_000); const publicValue = projectRoom('r1', canonical, [player], 'player', 'p1', 1_000); const audience = projectRoom('r1', canonical, [player], 'audience', undefined, 1_000);
  for (const value of [publicValue, audience]) assert.equal(JSON.stringify(value).match(/canonicalAnswer|acceptedAnswers|sources|review|moderation|primaryAnswer/), null);
  assert.match(JSON.stringify(host), /primaryAnswer/); assert.match(JSON.stringify(host), /مصدر/);
});
test('only first eligible player buzz wins and player sees self winner only', () => {
  const first = reduceIntent(room(), player, { type: 'BUZZ', intentId: 'a', expectedRevision: 2, payload: {} }, 1_000); assert.equal(first.room.game.lifecycle, 'FIRST_ANSWER'); assert.equal(first.room.buzzWinner?.uid, 'p1'); assert.equal(first.room.buzzWinner?.method, 'player'); assert.throws(() => reduceIntent(first.room, { ...player, uid: 'p2', team: 'vertical' }, { type: 'BUZZ', intentId: 'b', expectedRevision: 3, payload: {} }, 1_000)); const winner = projectRoom('r', first.room, [player], 'player', 'p1', 1_000); const host = projectRoom('r', first.room, [player], 'host', 'p1', 1_000); assert.match(JSON.stringify(winner), /isBuzzWinner/); assert.match(JSON.stringify(host), /displayName/);
});
test('zero-player host mode starts and host selection is public without a UID', () => {
  const host: CanonicalMember = { uid: 'host', role: 'host', displayName: 'مضيف', ready: true, active: true }; const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'].slice(0, 25); const lobby = { ...room(), game: initialGameState() };
  assert.equal(reduceIntent(lobby, host, { type: 'START_MATCH', intentId: 'start', expectedRevision: 2, payload: {} }, 1_000, undefined, [host], letters).room.game.lifecycle, 'ROUND_SETUP');
  const selected = reduceIntent(room(), host, { type: 'HOST_SELECT_TEAM', intentId: 'host-horizontal', expectedRevision: 2, payload: { team: 'horizontal' } }, 1_000, undefined, [host]); assert.equal(selected.room.game.lifecycle, 'FIRST_ANSWER'); assert.equal(selected.room.game.answeringTeam, 'horizontal'); assert.deepEqual(selected.room.buzzWinner, { displayName: 'أفقي', team: 'horizontal', method: 'host' }); assert.equal(selected.room.timer, undefined);
  const audience = projectRoom('r', selected.room, [host], 'audience', undefined, 1_000); const playerView = projectRoom('r', selected.room, [{ ...player, active: true }], 'player', player.uid, 1_000); assert.match(JSON.stringify(audience), /"method":"host"/); assert.equal(JSON.stringify(playerView).includes('buzzWinner'), false);
  const opponent = { ...room(), game: { ...room().game, lifecycle: 'OPPONENT_CHANCE' as const, entitledTeam: 'vertical' as const } }; assert.throws(() => reduceIntent(opponent, host, { type: 'HOST_SELECT_TEAM', intentId: 'wrong', expectedRevision: 2, payload: { team: 'horizontal' } }, 1_000, undefined, [host])); assert.equal(reduceIntent(opponent, host, { type: 'HOST_SELECT_TEAM', intentId: 'right', expectedRevision: 2, payload: { team: 'vertical' } }, 1_000, undefined, [host]).room.game.answeringTeam, 'vertical');
});
test('a partial player roster cannot bypass the two-ready-team start gate', () => {
  const host: CanonicalMember = { uid: 'host', role: 'host', displayName: 'مضيف', ready: true, active: true }; const onePlayer: CanonicalMember = { ...player, ready: true, active: true }; const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'].slice(0, 25); assert.throws(() => reduceIntent({ ...room(), game: initialGameState() }, host, { type: 'START_MATCH', intentId: 'partial', expectedRevision: 2, payload: {} }, 1_000, undefined, [host, onePlayer], letters), /teams-not-ready/);
});
test('late, audience, and wrong-team buzzes are rejected', () => {
  assert.throws(() => reduceIntent(room(), { ...player, role: 'audience' }, { type: 'BUZZ', intentId: 'a', expectedRevision: 2, payload: {} }, 1_000)); assert.throws(() => reduceIntent(room(), player, { type: 'BUZZ', intentId: 'a', expectedRevision: 2, payload: {} }, 2_001)); const opponent = { ...room(), game: { ...room().game, lifecycle: 'OPPONENT_CHANCE' as const, entitledTeam: 'vertical' as const } }; assert.throws(() => reduceIntent(opponent, player, { type: 'BUZZ', intentId: 'a', expectedRevision: 2, payload: {} }, 1_000));
});
test('receipt ids are collision-resistant and request hash detects semantic reuse', () => { const prefix = 'a'.repeat(119); assert.notEqual(intentReceiptId('p', `${prefix}a`), intentReceiptId('p', `${prefix}b`)); assert.notEqual(intentHash({ type: 'BUZZ', intentId: 'same', expectedRevision: 1, payload: {} }), intentHash({ type: 'BUZZ', intentId: 'same', expectedRevision: 2, payload: {} })); });
test('OPEN_QUESTION is a timer-only side effect and does not invoke an unsupported lifecycle event', () => { const host: CanonicalMember = { ...player, uid: 'h', role: 'host', team: undefined }; const result = reduceIntent(room(), host, { type: 'OPEN_QUESTION', intentId: 'open', expectedRevision: 2, payload: {} }, 1_000); assert.equal(result.room.game.lifecycle, 'QUESTION_READING'); assert.deepEqual(result.room.timer, { deadlineMs: 21_000, buzzOpen: true }); });
test('pinned question selection uses the active cell revealed/visible letter', () => { const board = generateBoard(1, [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي']); const active = board.cells.find((cell) => cell.kind === 'letter')!; const canonical = { ...room(), game: { ...room().game, board, activeCellId: active.id } }; const matching = { id: 'match', targetLetter: active.visibleValue, headerAr: 'عنوان', promptAr: 'سؤال', canonicalAnswer: 'جواب', acceptedAnswers: ['جواب'] }; const other = { ...matching, id: 'other', targetLetter: '؟' }; assert.equal(selectQuestionForActiveCell(canonical, [other, matching]).id, 'match'); });
test('surprise reveal atomically selects an unused pinned-release letter and question', () => {
  const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي']; let board = generateBoard(3, letters); const active = board.cells.find((cell) => cell.kind === 'surprise')!; const priorSurprise = board.cells.find((cell) => cell.kind === 'surprise' && cell.id !== active.id)!; const priorLetter = letters.find((letter) => !board.cells.some((cell) => cell.kind === 'letter' && cell.visibleValue === letter))!; board = revealSurprise(board, priorSurprise.id, priorLetter);
  const canonical = { ...room(), game: { ...room().game, lifecycle: 'LETTER_REVEAL' as const, board, activeCellId: active.id } };
  const questions = letters.map((targetLetter, index) => ({ id: `q-${index}`, targetLetter, headerAr: 'عنوان', promptAr: 'سؤال', canonicalAnswer: 'جواب', acceptedAnswers: ['جواب'] }));
  const reveal = prepareLetterReveal(canonical, questions); assert.ok(reveal.surpriseLetter); assert.notEqual(reveal.surpriseLetter, priorLetter); assert.equal(reveal.question.targetLetter, reveal.surpriseLetter);
  const host: CanonicalMember = { ...player, uid: 'host', role: 'host', team: undefined }; const result = reduceIntent(canonical, host, { type: 'LETTER_REVEALED', intentId: 'reveal', expectedRevision: 2, payload: {} }, 1_000, reveal.question, [host], undefined, reveal.surpriseLetter);
  const nextActive = result.room.game.board!.cells.find((cell) => cell.id === active.id)!; assert.equal(nextActive.revealedLetter, reveal.surpriseLetter);
  const revealedOrVisibleLetters = result.room.game.board!.cells.flatMap((cell) => cell.kind === 'letter' ? [cell.visibleValue] : cell.revealedLetter ? [cell.revealedLetter] : []); assert.equal(new Set(revealedOrVisibleLetters).size, revealedOrVisibleLetters.length);
  const surpriseDigits = result.room.game.board!.cells.filter((cell) => cell.kind === 'surprise').map((cell) => cell.visibleValue); assert.equal(new Set(surpriseDigits).size, surpriseDigits.length);
});
test('host correction projection carries correction and prior owner without exposing it publicly', () => { const board = generateBoard(2, [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي']); const cell = board.cells[0]; cell.owner = 'horizontal'; const canonical = { ...room(), game: { ...room().game, board, lifecycle: 'CORRECTION' as const, correction: { cellId: cell.id, owner: 'vertical' as const, reason: 'تصحيح' } } }; const host = projectRoom('r', canonical, [{ ...player, role: 'host' }], 'host', 'p1', 1_000); const audience = projectRoom('r', canonical, [player], 'audience', undefined, 1_000); assert.deepEqual((host.projection as { correction: unknown }).correction, { cellId: cell.id, owner: 'vertical', reason: 'تصحيح', priorOwner: 'horizontal' }); assert.equal(JSON.stringify(audience).includes('تصحيح'), false); });
test('Firebase request scope is persisted-ready and selection defaults to a three-round reserve', () => { assert.deepEqual(validateQuestionScope({ categories: ['tahadani-007', 'tahadani-006', 'tahadani-006'], modality: 'classic' }), { categories: ['tahadani-006', 'tahadani-007'], modality: 'classic' }); assert.throws(() => validateQuestionScope({ categories: [], modality: 'classic' }), /scope/i); assert.throws(() => validateQuestionScope({ categories: ['tahadani-006'], modality: 'charades' }), /scope/i); const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'].slice(0, 25); const onePerLetter = letters.map((targetLetter) => ({ id: targetLetter, categoryId: 'tahadani-006', modality: 'classic' as const, targetLetter, answerConceptId: `concept:${targetLetter}`, headerAr: 'h', promptAr: 'p', canonicalAnswer: 'a', acceptedAnswers: ['b'] })); assert.throws(() => createMatchQuestionSelection(onePerLetter, { categories: ['tahadani-006'], modality: 'classic', seed: 1 }), /reserve/i); });
