import assert from 'node:assert/strict';
import test from 'node:test';
import { initialGameState } from '../../src/features/game/domain/lifecycle.js';
import { generateBoard, revealSurprise } from '../../src/features/game/domain/board.js';
import { prepareLetterReveal, selectQuestionForActiveCell, validateQuestionScope } from './index.js';
import { createMatchQuestionSelection, selectCharadesQuestion } from '../../src/features/game/runtime/question-selector.js';
import { intentHash, intentReceiptId, isRoomClosed, projectRoom, reduceIntent, type CanonicalMember, type CanonicalRoom } from './game.js';

const room = (): CanonicalRoom => ({ schemaVersion: 2, roomCode: 'A1B2C3D4', revision: 2, game: { ...initialGameState(), lifecycle: 'QUESTION_READING' }, config: { demo: true, questionSeconds: 20, opponentSeconds: 10, teams: { horizontal: 'أفقي', vertical: 'عمودي' }, releaseId: 'demo-drafts', releaseRootSha256: 'hash', releaseDemoFixture: true }, timer: { deadlineMs: 2_000, buzzOpen: true }, questionCursor: 0 });
const player: CanonicalMember = { uid: 'p1', role: 'player', displayName: 'P', ready: false, active: true, team: 'horizontal' };

test('closed rooms are terminal for shared join and intent guards', () => {
  const closed = { ...room(), closedAt: new Date().toISOString() } as CanonicalRoom;
  assert.equal(isRoomClosed(closed), true);
  assert.throws(() => reduceIntent(closed, player, { type: 'BUZZ', intentId: 'closed-buzz', expectedRevision: 2, payload: {} }, 1_000), /room-closed/);
});

test('private fields remain absent from player/audience projections while host gets answer/source', () => {
  const canonical = { ...room(), activeQuestion: { id: 'q', targetLetter: 'ا', headerAr: 'عنوان', promptAr: 'سؤال', canonicalAnswer: 'جواب', acceptedAnswers: ['جواب'], sources: [{ title: 'مصدر' }], review: { secret: true } } };
  const host = projectRoom('r1', canonical, [{ ...player, role: 'host' }], 'host', 'p1', 1_000); const publicValue = projectRoom('r1', canonical, [player], 'player', 'p1', 1_000); const audience = projectRoom('r1', canonical, [player], 'audience', undefined, 1_000);
  for (const value of [publicValue, audience]) assert.equal(JSON.stringify(value).match(/canonicalAnswer|acceptedAnswers|sources|review|moderation|primaryAnswer/), null);
  assert.match(JSON.stringify(host), /primaryAnswer/); assert.match(JSON.stringify(host), /مصدر/);
});
test('Firebase projections preserve match settings for a same-settings rematch', () => {
  const canonical = { ...room(), config: { ...room().config, categories: ['tahadani-006', 'tahadani-007'], modality: 'image' as const, difficulty: 'hard', mode: 'custom' as const } };
  const value = projectRoom('r1', canonical, [{ ...player, role: 'host' }], 'host', 'p1', 1_000).projection as { room: { matchSettings: unknown } };
  assert.deepEqual(value.room.matchSettings, { demo: true, questionSeconds: 20, opponentSeconds: 10, teams: { horizontal: 'أفقي', vertical: 'عمودي' }, categories: ['tahadani-006', 'tahadani-007'], modality: 'image', difficulty: 'hard', mode: 'custom' });
});
test('only first eligible player buzz wins and player sees self winner only', () => {
  const first = reduceIntent(room(), player, { type: 'BUZZ', intentId: 'a', expectedRevision: 2, payload: {} }, 1_000); assert.equal(first.room.game.lifecycle, 'FIRST_ANSWER'); assert.equal(first.room.buzzWinner?.uid, 'p1'); assert.equal(first.room.buzzWinner?.method, 'player'); assert.throws(() => reduceIntent(first.room, { ...player, uid: 'p2', team: 'vertical' }, { type: 'BUZZ', intentId: 'b', expectedRevision: 3, payload: {} }, 1_000)); const winner = projectRoom('r', first.room, [player], 'player', 'p1', 1_000); const host = projectRoom('r', first.room, [player], 'host', 'p1', 1_000); assert.match(JSON.stringify(winner), /isBuzzWinner/); assert.match(JSON.stringify(host), /displayName/);
});
test('zero-player host mode starts and host selection is public without a UID', () => {
  const host: CanonicalMember = { uid: 'host', role: 'host', displayName: 'مضيف', ready: true, active: true }; const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'].slice(0, 25); const lobby = { ...room(), game: initialGameState() };
  const started = reduceIntent(lobby, host, { type: 'START_MATCH', intentId: 'start', expectedRevision: 2, payload: {} }, 1_000, undefined, [host], letters); assert.equal(started.room.game.lifecycle, 'ROUND_SETUP'); const startedSummary = (projectRoom('r', started.room, [host], 'host', host.uid, 1_000).projection as { room: { readyCount: number; memberCount: number } }).room; assert.equal(startedSummary.readyCount, 0); assert.equal(startedSummary.memberCount, 0);
  const selected = reduceIntent(room(), host, { type: 'HOST_SELECT_TEAM', intentId: 'host-horizontal', expectedRevision: 2, payload: { team: 'horizontal' } }, 1_000, undefined, [host]); assert.equal(selected.room.game.lifecycle, 'FIRST_ANSWER'); assert.equal(selected.room.game.answeringTeam, 'horizontal'); assert.deepEqual(selected.room.buzzWinner, { displayName: 'أفقي', team: 'horizontal', method: 'host' }); assert.equal(selected.room.timer, undefined);
  const audience = projectRoom('r', selected.room, [host], 'audience', undefined, 1_000); const playerView = projectRoom('r', selected.room, [{ ...player, active: true }], 'player', player.uid, 1_000); assert.match(JSON.stringify(audience), /"method":"host"/); assert.equal(JSON.stringify(playerView).includes('buzzWinner'), false);
  const opponent = { ...room(), game: { ...room().game, lifecycle: 'OPPONENT_CHANCE' as const, entitledTeam: 'vertical' as const } }; assert.throws(() => reduceIntent(opponent, host, { type: 'HOST_SELECT_TEAM', intentId: 'wrong', expectedRevision: 2, payload: { team: 'horizontal' } }, 1_000, undefined, [host])); assert.equal(reduceIntent(opponent, host, { type: 'HOST_SELECT_TEAM', intentId: 'right', expectedRevision: 2, payload: { team: 'vertical' } }, 1_000, undefined, [host]).room.game.answeringTeam, 'vertical');
});
test('a partial player roster cannot bypass the two-ready-team start gate', () => {
  const host: CanonicalMember = { uid: 'host', role: 'host', displayName: 'مضيف', ready: true, active: true }; const onePlayer: CanonicalMember = { ...player, ready: true, active: true }; const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'].slice(0, 25); assert.throws(() => reduceIntent({ ...room(), game: initialGameState() }, host, { type: 'START_MATCH', intentId: 'partial', expectedRevision: 2, payload: {} }, 1_000, undefined, [host, onePlayer], letters), /teams-not-ready/);
});
test('late, audience, and wrong-team buzzes are rejected', () => {
  assert.throws(() => reduceIntent(room(), { ...player, role: 'audience' }, { type: 'BUZZ', intentId: 'a', expectedRevision: 2, payload: {} }, 1_000)); assert.throws(() => reduceIntent(room(), player, { type: 'BUZZ', intentId: 'a', expectedRevision: 2, payload: {} }, 2_001)); const opponent = { ...room(), game: { ...room().game, lifecycle: 'OPPONENT_CHANCE' as const, entitledTeam: 'vertical' as const } }; assert.throws(() => reduceIntent(opponent, player, { type: 'BUZZ', intentId: 'a', expectedRevision: 2, payload: {} }, 1_000));
});
test('receipt ids are collision-resistant and request hash detects semantic reuse', () => { const prefix = 'a'.repeat(119); assert.notEqual(intentReceiptId('p', `${prefix}a`), intentReceiptId('p', `${prefix}b`)); assert.notEqual(intentHash({ type: 'BUZZ', intentId: 'same', expectedRevision: 1, payload: {} }), intentHash({ type: 'BUZZ', intentId: 'same', expectedRevision: 2, payload: {} })); });
test('OPEN_QUESTION is a timer-only side effect and does not invoke an unsupported lifecycle event', () => { const host: CanonicalMember = { ...player, uid: 'h', role: 'host', team: undefined }; const result = reduceIntent(room(), host, { type: 'OPEN_QUESTION', intentId: 'open', expectedRevision: 2, payload: {} }, 1_000); assert.equal(result.room.game.lifecycle, 'QUESTION_READING'); assert.deepEqual(result.room.timer, { deadlineMs: 21_000, buzzOpen: true }); });
test('regular selection gives only the host the new question before reveal and surprise selection clears stale state', () => {
  const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي']; const board = generateBoard(4, letters); const regular = board.cells.find((cell) => cell.kind === 'letter')!; const surprise = board.cells.find((cell) => cell.kind === 'surprise')!; const host: CanonicalMember = { ...player, uid: 'host', role: 'host', team: undefined }; const stale = { id: 'stale', targetLetter: 'ا', headerAr: 'قديم', promptAr: 'سؤال قديم', canonicalAnswer: 'جواب قديم', acceptedAnswers: ['جواب قديم'] }; const question = { id: 'fresh', targetLetter: regular.visibleValue, headerAr: 'عنوان جديد', promptAr: 'سؤال جديد', canonicalAnswer: 'جواب جديد', acceptedAnswers: ['جواب جديد'] }; const selecting = { ...room(), game: { ...room().game, lifecycle: 'CELL_SELECTION' as const, board }, activeQuestion: stale };
  const selected = reduceIntent(selecting, host, { type: 'SELECT_CELL', intentId: 'regular', expectedRevision: 2, payload: { cellId: regular.id } }, 1_000, question, [host]);
  assert.equal(selected.room.activeQuestion?.id, question.id); assert.equal(selected.room.questionCursor, 1); const hostProjection = projectRoom('r', selected.room, [host], 'host', host.uid, 1_000).projection as { question?: { headerAr?: string; promptAr?: string; primaryAnswer?: string } }; assert.deepEqual(hostProjection.question, { headerAr: question.headerAr, promptAr: question.promptAr, primaryAnswer: question.canonicalAnswer, acceptedAnswers: question.acceptedAnswers, sources: [] });
  for (const role of ['player', 'audience'] as const) { const publicProjection = projectRoom('r', selected.room, [player], role, role === 'player' ? player.uid : undefined, 1_000).projection as { question?: unknown }; assert.equal(publicProjection.question, undefined); assert.equal(JSON.stringify(publicProjection).includes('جواب جديد'), false); }
  const revealed = reduceIntent(selected.room, host, { type: 'LETTER_REVEALED', intentId: 'reveal', expectedRevision: 3, payload: {} }, 1_001, selected.room.activeQuestion, [host]); assert.equal(revealed.room.activeQuestion?.id, question.id); assert.equal(revealed.room.questionCursor, 1);
  const surpriseSelection = reduceIntent(selecting, host, { type: 'SELECT_CELL', intentId: 'surprise', expectedRevision: 2, payload: { cellId: surprise.id } }, 1_000, undefined, [host]); assert.equal(surpriseSelection.room.activeQuestion, undefined); assert.equal(surpriseSelection.room.questionCursor, 0);
});
test('pinned question selection uses the active cell revealed/visible letter', () => { const board = generateBoard(1, [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي']); const active = board.cells.find((cell) => cell.kind === 'letter')!; const canonical = { ...room(), game: { ...room().game, board, activeCellId: active.id } }; const matching = { id: 'match', targetLetter: active.visibleValue, headerAr: 'عنوان', promptAr: 'سؤال', canonicalAnswer: 'جواب', acceptedAnswers: ['جواب'] }; const other = { ...matching, id: 'other', targetLetter: '؟' }; assert.equal(selectQuestionForActiveCell(canonical, [other, matching]).id, 'match'); });
test('surprise reveal atomically selects an unused pinned-release letter and question', () => {
  const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي']; let board = generateBoard(3, letters); const active = board.cells.find((cell) => cell.kind === 'surprise')!; const priorSurprise = board.cells.find((cell) => cell.kind === 'surprise' && cell.id !== active.id)!; const priorLetter = letters.find((letter) => !board.cells.some((cell) => cell.kind === 'letter' && cell.visibleValue === letter))!; board = revealSurprise(board, priorSurprise.id, priorLetter);
  const canonical = { ...room(), game: { ...room().game, lifecycle: 'LETTER_REVEAL' as const, board, activeCellId: active.id } };
  const questions = letters.map((targetLetter, index) => ({ id: `q-${index}`, targetLetter, headerAr: 'عنوان', promptAr: 'سؤال', canonicalAnswer: 'جواب', acceptedAnswers: ['جواب'] }));
  const reveal = prepareLetterReveal(canonical, questions); assert.ok(reveal.surpriseLetter); assert.notEqual(reveal.surpriseLetter, priorLetter); assert.equal(reveal.question.targetLetter, reveal.surpriseLetter);
  const host: CanonicalMember = { ...player, uid: 'host', role: 'host', team: undefined }; const result = reduceIntent(canonical, host, { type: 'LETTER_REVEALED', intentId: 'reveal', expectedRevision: 2, payload: {} }, 1_000, reveal.question, [host], undefined, reveal.surpriseLetter);
  const nextActive = result.room.game.board!.cells.find((cell) => cell.id === active.id)!; assert.equal(nextActive.revealedLetter, reveal.surpriseLetter);
  const revealedOrVisibleLetters = result.room.game.board!.cells.flatMap((cell) => cell.kind === 'letter' ? [cell.visibleValue] : cell.revealedLetter ? [cell.revealedLetter] : []); assert.equal(new Set(revealedOrVisibleLetters).size, revealedOrVisibleLetters.length);
  const surpriseDigits = result.room.game.board!.cells.filter((cell) => cell.kind === 'surprise').map((cell) => cell.visibleValue); assert.equal(new Set(surpriseDigits).size, surpriseDigits.length);
});
test('host correction projection carries correction and prior owner without exposing it publicly', () => { const board = generateBoard(2, [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي']); const cell = board.cells[0]; cell.owner = 'horizontal'; const canonical = { ...room(), game: { ...room().game, board, lifecycle: 'CORRECTION' as const, correction: { cellId: cell.id, owner: 'vertical' as const, reason: 'تصحيح' } } }; const host = projectRoom('r', canonical, [{ ...player, role: 'host' }], 'host', 'p1', 1_000); const audience = projectRoom('r', canonical, [player], 'audience', undefined, 1_000); assert.deepEqual((host.projection as { correction: unknown }).correction, { cellId: cell.id, owner: 'vertical', reason: 'تصحيح', priorOwner: 'horizontal' }); assert.equal(JSON.stringify(audience).includes('تصحيح'), false); });
test('Firebase request scope accepts a separate charades lifecycle and selection never uses a letter board', () => { assert.deepEqual(validateQuestionScope({ categories: ['tahadani-007', 'tahadani-006', 'tahadani-006'], modality: 'classic' }), { categories: ['tahadani-006', 'tahadani-007'], modality: 'classic' }); assert.deepEqual(validateQuestionScope({ categories: ['tahadani-016'], modality: 'charades' }), { categories: ['tahadani-016'], modality: 'charades' }); assert.throws(() => validateQuestionScope({ categories: [], modality: 'classic' }), /scope/i); const charades = { id: 'charades-1', categoryId: 'tahadani-016', modality: 'charades' as const, answerConceptId: 'concept:act', headerAr: 'تمثيل', promptAr: 'مثّل العبارة', canonicalAnswer: 'بحر', acceptedAnswers: ['بحر'] }; assert.equal(selectCharadesQuestion([charades], { categories: ['tahadani-016'], cursor: 0 }).id, 'charades-1'); assert.throws(() => createMatchQuestionSelection([charades], { categories: ['tahadani-016'], modality: 'charades', seed: 1 }), /separate-mode/i); const letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'].slice(0, 25); const onePerLetter = letters.map((targetLetter) => ({ id: targetLetter, categoryId: 'tahadani-006', modality: 'classic' as const, targetLetter, answerConceptId: `concept:${targetLetter}`, headerAr: 'h', promptAr: 'p', canonicalAnswer: 'a', acceptedAnswers: ['b'] })); assert.throws(() => createMatchQuestionSelection(onePerLetter, { categories: ['tahadani-006'], modality: 'classic', seed: 1 }), /reserve/i); });
test('charades start, answer, complete, and rematch without a board or letter selectors', () => {
  const host: CanonicalMember = { uid: 'host', role: 'host', displayName: 'مضيف', ready: true, active: true };
  const question = { id: 'charades-1', categoryId: 'tahadani-016', modality: 'charades' as const, answerConceptId: 'concept:act', headerAr: 'تمثيل', promptAr: 'مثّل العبارة', canonicalAnswer: 'بحر', acceptedAnswers: ['بحر'] };
  const lobby = { ...room(), game: initialGameState(), config: { ...room().config, modality: 'charades' as const, categories: ['tahadani-016'] } };
  const started = reduceIntent(lobby, host, { type: 'START_MATCH', intentId: 'charades-start', expectedRevision: 2, payload: {} }, 1_000, question, [host]);
  assert.equal(started.room.game.lifecycle, 'QUESTION_READING'); assert.equal(started.room.game.board, undefined); assert.equal(started.room.game.activeCellId, undefined); assert.equal(started.room.activeQuestion?.id, question.id); assert.equal(JSON.stringify(projectRoom('r', started.room, [host], 'player', undefined, 1_000)).includes('canonicalAnswer'), false);
  assert.throws(() => reduceIntent(started.room, host, { type: 'SELECT_CELL', intentId: 'forbidden-cell', expectedRevision: 3, payload: { cellId: 'cell-0-0' } }, 1_000), /charades-no-letter-board/);
  const buzzed = reduceIntent(started.room, { ...player, ready: true, active: true }, { type: 'BUZZ', intentId: 'charades-buzz', expectedRevision: 3, payload: {} }, 1_001, undefined, [host, { ...player, ready: true, active: true }]);
  const judged = reduceIntent(buzzed.room, host, { type: 'JUDGE_CORRECT', intentId: 'charades-correct', expectedRevision: 4, payload: {} }, 1_002, undefined, [host, player]);
  const completed = reduceIntent(judged.room, host, { type: 'AWARD_CELL', intentId: 'charades-complete', expectedRevision: 5, payload: {} }, 1_003, undefined, [host, player]);
  assert.equal(completed.room.game.lifecycle, 'ROUND_COMPLETE'); assert.equal(completed.room.game.questionScores.horizontal, 1); assert.equal(completed.room.game.board, undefined);
  const rematchQuestion = { ...question, id: 'charades-2', answerConceptId: 'concept:other' };
  const rematch = reduceIntent(completed.room, host, { type: 'START_NEXT_ROUND', intentId: 'charades-next', expectedRevision: 6, payload: {} }, 1_004, rematchQuestion, [host]);
  assert.equal(rematch.room.game.lifecycle, 'QUESTION_READING'); assert.equal(rematch.room.game.currentRound, 2); assert.equal(rematch.room.game.board, undefined); assert.equal(rematch.room.activeQuestion?.id, 'charades-2');
});
