import { createHash } from 'node:crypto';
import { generateBoard, revealSurprise, type TeamAxis } from '../../src/features/game/domain/board.js';
import { deriveMatch, reduceGame, type GameEvent, type GameState } from '../../src/features/game/domain/lifecycle.js';
import type { MatchQuestionSelection } from '../../src/features/game/runtime/question-selector.js';

export type MemberRole = 'host' | 'player' | 'audience';
export type CanonicalMember = { uid: string; role: MemberRole; displayName: string; ready: boolean; active: boolean; team?: TeamAxis; joinedAt?: unknown };
export type CanonicalQuestion = { id: string; targetLetter: string; headerAr: string; promptAr: string; canonicalAnswer: string; acceptedAnswers: string[]; categoryId?: string; modality?: 'classic' | 'image' | 'charades'; answerConceptId?: string; sources?: Array<{ title?: string; url?: string }>; review?: unknown; moderation?: unknown };
export type CanonicalRoom = { schemaVersion: 2; roomCode: string; revision: number; game: GameState; config: { demo: boolean; questionSeconds: number; opponentSeconds: number; teams: Record<TeamAxis, string>; releaseId: string; releaseRootSha256: string; releaseDemoFixture: boolean; categories?: string[]; modality?: 'classic' | 'image' | 'charades' }; timer?: { deadlineMs: number; buzzOpen: boolean; remainingMs?: number; pausedBuzzOpen?: boolean }; buzzWinner?: { uid?: string; displayName: string; team: TeamAxis; method: 'player' | 'host' }; activeQuestion?: CanonicalQuestion; questionSelection?: MatchQuestionSelection; questionCursor: number; createdAt?: unknown; updatedAt?: unknown };
export type IntentType = 'LOBBY_SET_READY' | 'START_MATCH' | 'ROUND_READY' | 'SELECT_CELL' | 'LETTER_REVEALED' | 'OPEN_QUESTION' | 'BUZZ' | 'HOST_SELECT_TEAM' | 'JUDGE_CORRECT' | 'JUDGE_INCORRECT' | 'RETRY_CELL' | 'RETURN_CELL' | 'AWARD_CELL' | 'CHECK_PATH' | 'START_NEXT_ROUND' | 'PAUSE' | 'RESUME' | 'BEGIN_CORRECTION' | 'CONFIRM_CORRECTION' | 'CANCEL_CORRECTION';
export type GameIntent = { type: IntentType; intentId: string; expectedRevision: number; payload: Record<string, unknown> };
export const MAX_PLAYERS = 16; export const MAX_AUDIENCE = 200;
const types = new Set<IntentType>(['LOBBY_SET_READY', 'START_MATCH', 'ROUND_READY', 'SELECT_CELL', 'LETTER_REVEALED', 'OPEN_QUESTION', 'BUZZ', 'HOST_SELECT_TEAM', 'JUDGE_CORRECT', 'JUDGE_INCORRECT', 'RETRY_CELL', 'RETURN_CELL', 'AWARD_CELL', 'CHECK_PATH', 'START_NEXT_ROUND', 'PAUSE', 'RESUME', 'BEGIN_CORRECTION', 'CONFIRM_CORRECTION', 'CANCEL_CORRECTION']);

export function validateDisplayName(value: unknown, fallback: string): string { const name = typeof value === 'string' ? value.trim() : fallback; if (!name || name.length > 48 || /\p{Cc}/u.test(name)) throw new Error('invalid-display-name'); return name; }
export function normalizeRoomCode(value: string): string { const code = value.toUpperCase().replace(/[^A-Z0-9]/g, ''); if (!/^[A-Z0-9]{8}$/.test(code)) throw new Error('invalid-room-code'); return code; }
export function intentReceiptId(uid: string, intentId: string): string { return createHash('sha256').update(uid).update('\0').update(intentId).digest('hex'); }
export function intentHash(intent: GameIntent): string { return createHash('sha256').update(JSON.stringify({ type: intent.type, expectedRevision: intent.expectedRevision, payload: intent.payload })).digest('hex'); }
export function validIntent(intent: unknown): intent is GameIntent { if (!intent || typeof intent !== 'object') return false; const value = intent as GameIntent; if (!types.has(value.type) || !/^[A-Za-z0-9_-]{1,120}$/.test(value.intentId) || !Number.isInteger(value.expectedRevision) || value.expectedRevision < 0 || !value.payload || typeof value.payload !== 'object' || Array.isArray(value.payload)) return false; const keys = Object.keys(value.payload); if (value.type === 'LOBBY_SET_READY') return keys.length === 1 && typeof value.payload.ready === 'boolean'; if (value.type === 'SELECT_CELL') return keys.length === 1 && typeof value.payload.cellId === 'string' && /^cell-[0-4]-[0-4]$/.test(value.payload.cellId); if (value.type === 'HOST_SELECT_TEAM') return keys.length === 1 && (value.payload.team === 'horizontal' || value.payload.team === 'vertical'); if (value.type === 'BEGIN_CORRECTION') return keys.every((key) => ['cellId', 'owner', 'reason'].includes(key)) && typeof value.payload.cellId === 'string' && /^cell-[0-4]-[0-4]$/.test(value.payload.cellId) && (value.payload.owner === undefined || value.payload.owner === 'horizontal' || value.payload.owner === 'vertical') && typeof value.payload.reason === 'string' && value.payload.reason.trim().length > 0 && value.payload.reason.length <= 240; return keys.length === 0; }

function allReady(room: CanonicalRoom, members: CanonicalMember[]) { const players = members.filter((member) => member.active && member.role === 'player'); return players.length === 0 || (players.length >= 2 && new Set(players.map((member) => member.team)).size === 2 && players.every((member) => member.ready)); }
function teamCanBuzz(room: CanonicalRoom, team: TeamAxis) { return room.game.lifecycle === 'QUESTION_READING' || (room.game.lifecycle === 'OPPONENT_CHANCE' && room.game.entitledTeam === team); }
function timerIsOpen(room: CanonicalRoom, now: number) { return Boolean(room.timer?.buzzOpen && room.timer.deadlineMs > now); }

/** This always builds a new role-safe object; canonical question/review fields cannot serialize by accident. */
export function projectRoom(roomId: string, room: CanonicalRoom, members: CanonicalMember[], role: MemberRole, uid?: string, now = Date.now()) {
  const active = members.filter((member) => member.active); const participants = active.filter((member) => member.role !== 'audience'); const self = uid ? active.find((member) => member.uid === uid) : undefined; const match = deriveMatch(room.game); const canStart = allReady(room, participants); const publicQuestion = room.activeQuestion ? { headerAr: room.activeQuestion.headerAr, promptAr: room.activeQuestion.promptAr, ...(room.game.lifecycle === 'QUESTION_FAILED' ? { revealedAnswer: room.activeQuestion.canonicalAnswer } : {}) } : undefined; const winner = room.buzzWinner ? { displayName: room.buzzWinner.displayName, team: room.buzzWinner.team, method: room.buzzWinner.method } : undefined;
  const projection: Record<string, unknown> = { room: { roomCode: room.roomCode, state: room.game.lifecycle, readyCount: participants.filter((member) => member.ready).length, memberCount: participants.length, teams: room.config.teams, members: participants.map((member) => ({ displayName: member.displayName, team: member.team, ready: member.ready, role: member.role })), matchSettings: { demo: room.config.demo, questionSeconds: room.config.questionSeconds, opponentSeconds: room.config.opponentSeconds, teams: room.config.teams, categories: [], difficulty: 'mixed', mode: 'classic' }, canStart, ...(canStart ? {} : { startBlockedReason: 'READY_TEAMS_REQUIRED' }) }, ...(room.config.demo ? { demo: true } : {}), board: room.game.board?.cells.map(({ id, q, r, kind, visibleValue, revealedLetter, owner }) => ({ id, q, r, kind, visibleValue, ...(revealedLetter ? { revealedLetter } : {}), ...(owner ? { owner } : {}) })), activeCellId: room.game.activeCellId, currentRound: room.game.currentRound, questionScores: room.game.questionScores, roundWins: match.roundWins, currentStreak: match.currentStreak, roundResults: match.roundResults.map(({ round, winner: roundWinner }) => ({ round, winner: roundWinner })), entitledTeam: room.game.entitledTeam, answeringTeam: room.game.answeringTeam, winningPath: room.game.winningPath, ...(match.matchWinner ? { matchWinner: match.matchWinner, matchWinReason: match.matchWinReason } : {}), ...(publicQuestion ? { question: publicQuestion } : {}), ...(room.timer ? { deadlineAt: new Date(room.timer.deadlineMs).toISOString(), buzzOpen: timerIsOpen(room, now) } : {}), ...(winner && (role === 'host' || role === 'audience') ? { buzzWinner: winner } : {}) };
  if (self && role !== 'audience') projection.self = { uid: self.uid, ready: self.ready, team: self.team, canBuzz: self.role === 'player' && self.team !== undefined && !room.buzzWinner && timerIsOpen(room, now) && teamCanBuzz(room, self.team), ...(room.buzzWinner?.uid === self.uid ? { isBuzzWinner: true } : {}) };
  if (role === 'host') { if (room.activeQuestion) projection.question = { ...publicQuestion, primaryAnswer: room.activeQuestion.canonicalAnswer, acceptedAnswers: room.activeQuestion.acceptedAnswers, sources: room.activeQuestion.sources ?? [] }; if (room.game.correction) projection.correction = { ...room.game.correction, priorOwner: room.game.board?.cells.find((cell) => cell.id === room.game.correction?.cellId)?.owner }; }
  return { roomId, revision: room.revision, serverTime: new Date(now).toISOString(), role, projection };
}
export function expireRoom(room: CanonicalRoom, now: number): CanonicalRoom { if (!room.timer || !room.timer.buzzOpen || room.timer.deadlineMs > now || !['QUESTION_READING', 'OPPONENT_CHANCE'].includes(room.game.lifecycle)) return room; return { ...room, revision: room.revision + 1, game: reduceGame(room.game, { type: 'TIME_EXPIRED' }), timer: undefined, buzzWinner: undefined }; }
export function makeBoard(room: CanonicalRoom, letters = [...'ابتثجحخدذرزسشصضطظعغفقكلمنهوي']) { return generateBoard((room.questionCursor + 1) * 0x9e3779b1, letters); }

export function reduceIntent(room: CanonicalRoom, member: CanonicalMember, intent: GameIntent, now: number, question?: CanonicalQuestion, members: CanonicalMember[] = [member], boardLetters?: string[], surpriseLetter?: string): { room: CanonicalRoom; member: CanonicalMember; eventType: string } {
  if (intent.expectedRevision !== room.revision) throw new Error('stale-revision'); if (!member.active) throw new Error('inactive-member'); const hostOnly = intent.type !== 'LOBBY_SET_READY' && intent.type !== 'BUZZ'; if (hostOnly && member.role !== 'host') throw new Error('host-only');
  if (intent.type === 'LOBBY_SET_READY') { if (member.role !== 'player' || room.game.lifecycle !== 'LOBBY') throw new Error('ready-not-allowed'); return { room: { ...room, revision: room.revision + 1 }, member: { ...member, ready: intent.payload.ready as boolean }, eventType: intent.type }; }
  if (intent.type === 'BUZZ') { if (member.role !== 'player' || !member.team || room.buzzWinner || !timerIsOpen(room, now) || !teamCanBuzz(room, member.team)) throw new Error('buzz-not-allowed'); return { room: { ...room, revision: room.revision + 1, game: reduceGame(room.game, { type: 'BUZZ_ACCEPTED', team: member.team }), timer: undefined, buzzWinner: { uid: member.uid, displayName: member.displayName, team: member.team, method: 'player' } }, member, eventType: intent.type }; }
  if (intent.type === 'HOST_SELECT_TEAM') { const team = intent.payload.team; if ((team !== 'horizontal' && team !== 'vertical') || !teamCanBuzz(room, team)) throw new Error('host-team-selection-not-allowed'); return { room: { ...room, revision: room.revision + 1, game: reduceGame(room.game, { type: 'BUZZ_ACCEPTED', team }), timer: undefined, buzzWinner: { displayName: room.config.teams[team], team, method: 'host' } }, member, eventType: intent.type }; }
  let event: GameEvent; switch (intent.type) { case 'START_MATCH': event = { type: 'START_MATCH', board: makeBoard(room, boardLetters) }; break; case 'START_NEXT_ROUND': event = { type: 'START_NEXT_ROUND', board: makeBoard(room, boardLetters) }; break; case 'SELECT_CELL': event = { type: 'SELECT_CELL', cellId: intent.payload.cellId as string }; break; case 'BEGIN_CORRECTION': event = { type: 'BEGIN_CORRECTION', cellId: intent.payload.cellId as string, owner: intent.payload.owner as TeamAxis | undefined, reason: (intent.payload.reason as string).trim() }; break; case 'OPEN_QUESTION': event = { type: 'OPEN_QUESTION' } as GameEvent; break; default: event = { type: intent.type as Exclude<GameEvent['type'], 'START_MATCH' | 'START_NEXT_ROUND' | 'SELECT_CELL' | 'BEGIN_CORRECTION' | 'BUZZ_ACCEPTED'> } as GameEvent; }
  if (intent.type === 'START_MATCH' && !allReady(room, members)) throw new Error('teams-not-ready'); let game = intent.type === 'OPEN_QUESTION' ? room.game : reduceGame(room.game, event); let timer = room.timer; let activeQuestion = room.activeQuestion; let buzzWinner = room.buzzWinner; if (intent.type === 'LETTER_REVEALED') { if (!question) throw new Error('no-release-question'); const active = room.game.board?.cells.find((cell) => cell.id === room.game.activeCellId); if (active?.kind === 'surprise' && !active.revealedLetter) { if (!surpriseLetter || !room.game.board || !room.game.activeCellId) throw new Error('no-surprise-letter'); game = { ...game, board: revealSurprise(room.game.board, room.game.activeCellId, surpriseLetter) }; } activeQuestion = question; } if (intent.type === 'OPEN_QUESTION' || intent.type === 'RETRY_CELL') { timer = { deadlineMs: now + (intent.type === 'OPEN_QUESTION' ? room.config.questionSeconds : room.config.opponentSeconds) * 1000, buzzOpen: true }; buzzWinner = undefined; } if (intent.type === 'JUDGE_INCORRECT' && game.lifecycle === 'OPPONENT_CHANCE') { timer = { deadlineMs: now + room.config.opponentSeconds * 1000, buzzOpen: true }; buzzWinner = undefined; } if (intent.type === 'PAUSE' && room.timer) timer = { deadlineMs: 0, buzzOpen: false, remainingMs: Math.max(0, room.timer.deadlineMs - now), pausedBuzzOpen: room.timer.buzzOpen }; if (intent.type === 'RESUME' && room.timer?.remainingMs !== undefined) timer = { deadlineMs: now + room.timer.remainingMs, buzzOpen: Boolean(room.timer.pausedBuzzOpen) }; if (['JUDGE_CORRECT', 'RETURN_CELL', 'AWARD_CELL', 'CHECK_PATH', 'START_NEXT_ROUND'].includes(intent.type)) timer = undefined;
  return { room: { ...room, revision: room.revision + 1, game, timer, activeQuestion, buzzWinner, questionCursor: room.questionCursor + (intent.type === 'LETTER_REVEALED' ? 1 : 0) }, member, eventType: intent.type };
}
