import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import { resolve } from 'node:path';
import type { Incoming, LedgerEntry } from '../scripts/master-import.js';
import { isLoopbackAddress } from './local-admin-guard.js';

const defaultLedger = 'output/master-import-20260909/master-import-apply-ledger.json';
const defaultRegistry = 'content/question-media/v18-private-240/manifest.json';
const defaultMediaRoot = 'content/question-media/v18-private-240/originals';
const defaultDb = process.env.GAME_DB_PATH ?? resolve(process.env.LOCALAPPDATA ?? '', 'Temp/huroof-wa-oloof-local-game.sqlite');
const defaultDrafts = 'content/questions/drafts/questions.jsonl';
const defaultApproved = 'content/questions/approved/questions.jsonl';
type RequestLike = { socket:{remoteAddress?:string}; headers:Record<string,string|string[]|undefined> };
type Ledger = { runKind:string; runState?:string; entries:LedgerEntry[]; baseline:Record<string,number>; after:Record<string,number>; outcomes:Record<string,number> };
type ReviewOptions = { ledgerPath?:string; dbPath?:string; fileDraftsPath?:string; fileApprovedPath?:string; registryPath?:string; mediaRoot?:string };
const hdr=(r:RequestLike,k:string)=>r.headers[k]??r.headers[k.toLowerCase()]; const txt=(v:string|string[]|undefined)=>typeof v==='string'?v:undefined;
export const isTrustedReviewHost=(host:string|undefined)=>{try{return ['127.0.0.1','localhost','[::1]','::1'].includes(new URL(`http://${host??''}`).hostname);}catch{return false;}};
export const isTrustedReviewOrigin=(origin:string|undefined)=>new Set((process.env.LOCAL_IMPORT_REVIEW_ORIGINS??'http://127.0.0.1:5199,http://localhost:5199,http://127.0.0.1:8787,http://localhost:8787').split(',').map(x=>x.trim())).has(origin??'');
/** Browser GET/image requests commonly omit Origin; Sec-Fetch-Site binds those reads to this origin. */
export const isTrustedImportReviewRequest=(r:RequestLike)=>{if(!isLoopbackAddress(r.socket.remoteAddress)||!isTrustedReviewHost(txt(hdr(r,'host'))))return false;const origin=txt(hdr(r,'origin'));return origin?isTrustedReviewOrigin(origin):txt(hdr(r,'sec-fetch-site'))==='same-origin';};
const hashMatches=(bytes:Buffer,expected:string)=>/^[a-f0-9]{64}$/u.test(expected)&&createHash('sha256').update(bytes).digest('hex')===expected;
const clean=(v:string|null)=>v?.trim().slice(0,160)??''; const safeId=(v:string)=>/^[A-Za-z0-9:_-]{1,180}$/u.test(v);
const sourceIdentity=(s:Incoming)=>[s.id,s.source_package,s.category_id,s.source_record_id,s.source_content_sha256].join('\0');
const storedRows=(dbPath:string)=>{const db=new DatabaseSync(resolve(dbPath),{readOnly:true});try{return (db.prepare('SELECT id,data FROM local_admin_drafts ORDER BY id').all() as {id:string;data:string}[]).map(x=>({id:x.id,data:JSON.parse(x.data) as Record<string,unknown>}));}finally{db.close();}};
const fileRows=async(path:string)=>{try{return (await readFile(path,'utf8')).split(/\r?\n/gu).filter(Boolean).map(line=>JSON.parse(line)as Record<string,unknown>);}catch{return [];}};
const storageState=(entry:LedgerEntry, db:Map<string,Record<string,unknown>>, files:Map<string,Record<string,unknown>>)=>{const id=entry.storageId??entry.matchedExistingId;const data=id?(db.get(id)??files.get(id)):undefined;if(!data)return {state:'missing' as const,id};if(entry.physicalRow){const source=data.importSource as Incoming|undefined;if(!source||sourceIdentity(source)!==sourceIdentity(entry.source!))return {state:'mismatched' as const,id};return {state:'present' as const,id,data};}return {state:'preserved_existing' as const,id,data};};
export async function loadImportLedger(path=process.env.LOCAL_IMPORT_LEDGER_PATH??defaultLedger):Promise<Ledger>{const resolved=resolve(path);const ledger=JSON.parse(await readFile(resolved,'utf8'))as Ledger;if(ledger.runKind!=='apply'||ledger.runState!=='prepared'||!Array.isArray(ledger.entries)||!ledger.entries.every(e=>e&&typeof e.incomingId==='string'&&typeof e.outcome==='string'))throw new Error('IMPORT_LEDGER_NOT_COMMITTED_APPLY');let receipt:{state?:string;reportPath?:string};try{receipt=JSON.parse(await readFile(`${resolved}.completion.json`,'utf8'))as {state?:string;reportPath?:string};}catch{throw new Error('IMPORT_LEDGER_COMPLETION_MISSING');}if(!['committed','committed-recovered'].includes(receipt.state??'')||resolve(receipt.reportPath??'')!==resolved)throw new Error('IMPORT_LEDGER_COMPLETION_MISSING');return ledger;}
const currentCounts=(drafts:Record<string,unknown>[],approved:Record<string,unknown>[],db:Record<string,unknown>[])=>{const all=[...drafts,...approved,...db];return {stored:all.length,sqliteRows:db.length,drafts:all.filter(x=>x.status==='draft').length,approved:all.filter(x=>x.status==='approved').length,normalApprovedGameplayPool:approved.filter(x=>x.status==='approved'&&x.readOnly!==true&&(x.modality===undefined||x.modality==='classic')).length,categories:new Set(all.map(x=>String(x.categoryId))).size};};
export async function localImportReviewPage(url:URL, options:ReviewOptions|string={}){const o=typeof options==='string'?{ledgerPath:options}:options,ledger=await loadImportLedger(o.ledgerPath), dbRows=storedRows(o.dbPath??defaultDb),drafts=await fileRows(o.fileDraftsPath??defaultDrafts),approved=await fileRows(o.fileApprovedPath??defaultApproved),db=new Map(dbRows.map(x=>[x.id,x.data])),files=new Map([...drafts,...approved].map(x=>[String(x.id),x]));const category=clean(url.searchParams.get('category')),outcome=clean(url.searchParams.get('outcome')),q=clean(url.searchParams.get('q')).toLocaleLowerCase('ar'),limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit')??40)||40)),offset=Math.max(0,Number(url.searchParams.get('offset')??0)||0);const filtered=ledger.entries.filter(e=>(!category||e.categoryId===category)&&(!outcome||e.outcome===outcome)&&(!q||[e.incomingId,e.categoryId,e.sourcePackage,e.mode,e.reason].join(' ').toLocaleLowerCase('ar').includes(q)));return {runKind:ledger.runKind,baseline:ledger.baseline,after:currentCounts(drafts,approved,dbRows.map(x=>x.data)),outcomes:ledger.outcomes,total:filtered.length,offset,limit,items:filtered.slice(offset,offset+limit).map(e=>{const state=storageState(e,db,files);return {incomingId:e.incomingId,storageId:e.storageId,outcome:e.outcome,reason:e.reason,categoryId:e.categoryId,sourcePackage:e.sourcePackage,mode:e.mode,physicalRow:e.physicalRow,storageState:state.state,storageIdCurrent:state.id,hasAnswer:Boolean(e.source?.answer),...(e.source?.media?{media:{assetSha256:e.source.media.sha256}}:{})};}),categories:[...new Set(ledger.entries.map(e=>e.categoryId))].sort()};}
export async function localImportReviewDetail(id:string,options:ReviewOptions|string={}){if(!safeId(id))throw new Error('IMPORT_REVIEW_ID_INVALID');const o=typeof options==='string'?{ledgerPath:options}:options,ledger=await loadImportLedger(o.ledgerPath),entry=ledger.entries.find(e=>e.incomingId===id);if(!entry?.source)throw new Error('IMPORT_REVIEW_NOT_FOUND');const dbRows=storedRows(o.dbPath??defaultDb),drafts=await fileRows(o.fileDraftsPath??defaultDrafts),approved=await fileRows(o.fileApprovedPath??defaultApproved),state=storageState(entry,new Map(dbRows.map(x=>[x.id,x.data])),new Map([...drafts,...approved].map(x=>[String(x.id),x]))),s=entry.source,current=state.data;return {incomingId:entry.incomingId,outcome:entry.outcome,reason:entry.reason,categoryId:entry.categoryId,sourcePackage:entry.sourcePackage,mode:s.mode,question:s.question,instruction:s.instruction,answer:s.answer,acceptedAnswers:s.accepted_answers,targetLetter:s.target_letter,letterModeEligible:s.letter_mode_eligible,stagingState:entry.outcome==='staged'?entry.reason:undefined,storageState:state.state,storageIdCurrent:state.id,currentStored:current?{id:current.id,prompt:current.promptAr,answer:current.canonicalAnswer,readOnly:current.readOnly,status:current.status}:undefined,...(s.media?{media:{assetSha256:s.media.sha256,altAr:'صورة خاصة لسجل الاستيراد'}}:{})};}
export async function readLocalImportReviewMedia(id:string,assetSha256:string,options:ReviewOptions|string={}){if(!safeId(id)||!/^[a-f0-9]{64}$/u.test(assetSha256))throw new Error('IMPORT_MEDIA_REQUEST_INVALID');const o=typeof options==='string'?{ledgerPath:options}:options,ledger=await loadImportLedger(o.ledgerPath),entry=ledger.entries.find(e=>e.incomingId===id),s=entry?.source;if(!s?.media||s.media.sha256!==assetSha256)throw new Error('IMPORT_MEDIA_BINDING_MISMATCH');const state=storageState(entry!,new Map(storedRows(o.dbPath??defaultDb).map(x=>[x.id,x.data])),new Map());if(state.state!=='present')throw new Error('IMPORT_MEDIA_STORAGE_NOT_PRESENT');const registry=JSON.parse(await readFile(resolve(o.registryPath??defaultRegistry),'utf8'))as {assets:{assetSha256:string;localFile:string}[]};const asset=registry.assets.find(x=>x.assetSha256===assetSha256);if(!asset||asset.localFile!==`originals/${assetSha256}.png`)throw new Error('IMPORT_MEDIA_REGISTRY_MISMATCH');const root=resolve(o.mediaRoot??defaultMediaRoot),file=resolve(root,`${assetSha256}.png`);if(!file.startsWith(`${root}\\`)&&!file.startsWith(`${root}/`))throw new Error('IMPORT_MEDIA_PATH_INVALID');const bytes=await readFile(file);if(!hashMatches(bytes,assetSha256))throw new Error('IMPORT_MEDIA_HASH_MISMATCH');return bytes;}
