import { appendFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { AUTHORING_VERSION, contentHash, createReleaseManifest, indexedDuplicateClusters, isIsoDate, makePolicies, makeSlots, partitionSlots, promoteDraft, stableJson, stableJsonl, validateSlots, type CategoryPolicy, type RuntimeItem, type V2Draft } from '../src/question-bank-v2.js';

const ROOT = process.cwd();
const V2 = join(ROOT, 'content', 'question-bank-v2');
const BASELINES = {
  'content/questions/drafts/questions.jsonl': '006E74AB0D573E8BB7F81CCA4C70F7D657AB94EE4A586E1DEFBB6E0FB014F795',
  'content/questions/question.schema.json': '80C7DAF32D6BA8B4FA0B580FAB63AB7C3D960CE5A1DFEDCDC6EE545A7AE3163A',
  'content/categories/categories.json': '073B37A65BAABF1996A014C097378E3D62F18B348F08D1CB16C4C47D93E0C727',
  'content/questions/approved/questions.jsonl': '01BA4719C80B6FE911B091A7C05124B64EEECE964E09C058EF8F9805DACA546B',
} as const;

const schemas: Record<string, object> = {
  'classic-question-draft.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Classic Question V2 Draft', type: 'object', required: ['id', 'schemaVersion', 'categoryId', 'targetLetter', 'headerAr', 'promptAr', 'canonicalAnswer', 'acceptedAnswers', 'difficulty', 'status', 'sourcePacketIds', 'temporal', 'provenance'], properties: { schemaVersion: { const: AUTHORING_VERSION }, status: { const: 'draft' }, headerAr: { type: 'string' }, promptAr: { type: 'string' }, canonicalAnswer: { type: 'string' }, explanationAr: { type: ['string', 'null'] }, sourcePacketIds: { type: 'array', minItems: 1 }, temporal: { type: 'object' }, provenance: { type: 'object' } } },
  'classic-question-approved.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Classic Question V2 Approved', type: 'object', required: ['status', 'approvedAt', 'reviewReceiptIds'], properties: { status: { const: 'approved' }, reviewReceiptIds: { type: 'array', minItems: 5 }, approvedAt: { type: 'string', format: 'date' } } },
  'source-packet.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Source Packet V2', type: 'object', required: ['packetId', 'sourceRegistryId', 'claimLocators', 'sourceTier', 'evidenceKind', 'checkedAt', 'supportedFields', 'policyVersion', 'provenance'], properties: { packetId: { type: 'string' }, sourceRegistryId: { type: 'string' }, claimLocators: { type: 'array', minItems: 1, items: { type: 'string' } }, sourceTier: { enum: ['primary', 'official', 'reference'] }, evidenceKind: { enum: ['web-page', 'document', 'media-license'] }, checkedAt: { type: 'string', format: 'date' }, digest: { type: ['string', 'null'] }, archiveUrl: { type: ['string', 'null'] }, supportedFields: { type: 'array' }, policyVersion: { const: AUTHORING_VERSION }, provenance: { type: 'object' } } },
  'review-receipt.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Review Receipt V2', type: 'object', required: ['receiptId', 'itemId', 'kind', 'reviewer', 'reviewedAt', 'policyVersion', 'verdict', 'evidence'], properties: { kind: { enum: ['fact', 'arabic', 'relevance', 'duplicate', 'temporal', 'specialist', 'rights'] }, verdict: { enum: ['pass', 'fail'] }, reviewedAt: { type: 'string', format: 'date' } } },
  'image-media.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Image Media V2', type: 'object', required: ['assetId', 'localPath', 'sha256', 'altAr', 'rightsReceiptId', 'publishable'], properties: { localPath: { pattern: '^(?!https?://)' }, sha256: { pattern: '^[a-f0-9]{64}$' }, publishable: { const: true } } },
  'image-question.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Image Question V2', type: 'object', required: ['questionType', 'media', 'status'], properties: { questionType: { const: 'image' }, media: { $ref: 'image-media.v2.schema.json' }, status: { const: 'draft' } } },
  'charades-item.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Charades Item V2', type: 'object', required: ['id', 'categoryId', 'difficulty', 'status', 'phraseAr'], not: { required: ['targetLetter'] }, properties: { status: { const: 'draft' }, phraseAr: { type: 'string' } } },
  'authoring-slot.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Authoring Slot V2', type: 'object', additionalProperties: false, required: ['slotId', 'planVersion', 'categoryId', 'modality', 'difficulty', 'ordinal', 'state'], properties: { slotId: { type: 'string' }, planVersion: { const: AUTHORING_VERSION }, modality: { enum: ['classic', 'image', 'charades'] }, targetLetter: { type: 'string' }, difficulty: { enum: ['easy', 'medium', 'hard'] }, ordinal: { type: 'integer', minimum: 1 }, state: { enum: ['unfilled', 'blocked_source', 'blocked_media', 'needs_asset'] }, blocker: { type: 'string' } }, allOf: [{ if: { properties: { modality: { const: 'charades' } } }, then: { not: { required: ['targetLetter'] } }, else: { required: ['targetLetter'] } }] },
  'promotion-request.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Promotion Request V2', type: 'object', required: ['draftId', 'asOf', 'policyVersion', 'sourcePacketIds', 'reviewReceiptIds'], properties: { asOf: { type: 'string', format: 'date' } } },
  'release-manifest.v2.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'Immutable Release Manifest V2', type: 'object', required: ['releaseId', 'asOf', 'approvedContentHash', 'categoryIds', 'counts', 'policyVersion'], properties: { approvedContentHash: { pattern: '^[a-f0-9]{64}$' }, asOf: { type: 'string', format: 'date' } } },
};

const sourceRegistry = {
  registryVersion: AUTHORING_VERSION, claimLevelVerification: false,
  entries: [
    ['nasa-science', 'NASA Science', 'https://science.nasa.gov/solar-system/solar-system-facts/', 'official'], ['unesco-world-heritage', 'UNESCO World Heritage List', 'https://whc.unesco.org/en/list', 'official'], ['un-member-states', 'United Nations Member States', 'https://www.un.org/about-us/member-states', 'official'], ['six-iso-4217', 'SIX ISO 4217 maintenance', 'https://www.six-group.com/en/products-services/financial-information/market-reference-data/data-standards.html', 'official'], ['fifa-world-cup-2026', 'FIFA World Cup 2026', 'https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/match-schedule-fixtures-results-teams-stadiums', 'official'], ['ifab-laws', 'IFAB Laws of the Game', 'https://www.theifab.com/laws-of-the-game-documents/?language=en', 'official'], ['real-madrid-history', 'Real Madrid History', 'https://www.realmadrid.com/en-US/the-club/history', 'official'], ['minecraft-official', 'Minecraft About', 'https://www.minecraft.net/en-us/about-minecraft', 'official'], ['one-piece-official', 'One Piece official archive', 'https://one-piece.com/anime/index.html?category=&page=1&sort=asc', 'official'], ['quran-complex', 'King Fahd Qur’an Complex', 'https://qurancomplex.gov.sa/en/kfgqpc/kfq-structure/', 'primary'], ['us-copyright-facts-expression', 'US Copyright Office facts and expression', 'https://www.copyright.gov/help/faq/faq-general.html', 'official'], ['us-copyright-fair-use', 'US Copyright Office fair use', 'https://www.copyright.gov/fair-use/more-info.html', 'official'],
  ].map(([id, title, url, tier]) => ({ id, title, url, tier, purpose: 'source-class discovery only; not claim-level verification' })),
};

async function sha256File(path: string) { return contentHash(await readFile(path, 'utf8')); }
async function writeImmutable(path: string, content: string) {
  const current = await readFile(path, 'utf8').catch(() => null);
  if (current !== null && current !== content) throw new Error(`Refusing to overwrite versioned artifact: ${path}`);
  if (current === null) await writeFile(path, content);
}
async function categories() { return (JSON.parse(await readFile(join(ROOT, 'content/categories/categories.json'), 'utf8')) as { categories: Array<{ id: string; displayNameAr: string; sourceMode: string; sourcePolicy: string; classicCompatibility: string }> }).categories; }
async function ensurePlans() {
  const allCategories = await categories(); const policies = makePolicies(allCategories); const slots = makeSlots(allCategories); const parts = partitionSlots(slots);
  const dirs = [join(V2, 'schemas'), join(V2, 'policies'), join(V2, 'slots'), join(V2, 'source-packets'), join(V2, 'drafts'), join(V2, 'attempts'), join(V2, 'reports'), join(V2, 'approved'), join(V2, 'releases')]; await Promise.all(dirs.map((dir) => mkdir(dir, { recursive: true })));
  await Promise.all(Object.entries(schemas).map(([file, schema]) => writeFile(join(V2, 'schemas', file), stableJson(schema))));
  await Promise.all([writeFile(join(V2, 'policies', 'category-policy-registry.v2.json'), stableJson({ registryVersion: AUTHORING_VERSION, policies })), writeFile(join(V2, 'policies', 'source-registry.v2.json'), stableJson(sourceRegistry)), writeFile(join(V2, 'slots', 'classic.v2.jsonl'), stableJsonl(parts.classic)), writeFile(join(V2, 'slots', 'image.v2.jsonl'), stableJsonl(parts.image)), writeFile(join(V2, 'slots', 'charades.v2.jsonl'), stableJsonl(parts.charades))]);
  const fixturePacket = { packetId: 'packet-fixture-earth-001', sourceRegistryId: 'nasa-science', claimLocators: ['Solar System Facts / Earth'], sourceTier: 'official', evidenceKind: 'web-page', checkedAt: '2026-09-03', digest: null, archiveUrl: null, supportedFields: ['promptAr', 'canonicalAnswer'], policyVersion: AUTHORING_VERSION, provenance: { runId: 'fixture-v2', model: null, templateVersion: 'fixture-1' }, verificationState: 'structural_fixture_only' };
  const fixtureDraft: V2Draft = { id: 'draft-v2-fixture-earth-001', schemaVersion: AUTHORING_VERSION, locale: 'ar-KW', categoryId: 'tahadani-006', targetLetter: 'ا', headerAr: 'في النظام الشمسي', promptAr: 'ما الكوكب الثالث من الشمس؟', canonicalAnswer: 'الأرض', acceptedAnswers: ['الأرض', 'أرض'], acceptDefiniteArticle: true, difficulty: 'easy', questionType: 'text', explanationAr: null, status: 'draft', sourcePacketIds: [fixturePacket.packetId], temporal: { kind: 'stable', checkedAt: '2026-09-03', validUntil: null }, provenance: { runId: 'fixture-v2', attemptId: 'attempt-v2-fixture-earth-001', templateVersion: 'fixture-1', method: 'model_assisted', model: 'gpt-5.6-terra' } };
  const blockedAttempt = { attemptId: 'attempt-v2-missing-source-001', slotId: parts.classic[1].slotId, outcome: 'blocked_source', reason: 'No source packet was supplied; no draft was emitted.', createdAt: '2026-09-03T00:00:00Z' };
  await Promise.all([writeImmutable(join(V2, 'source-packets', 'fixture-earth.v2.json'), stableJson(fixturePacket)), writeImmutable(join(V2, 'drafts', 'fixture.v2.jsonl'), stableJsonl([fixtureDraft])), writeImmutable(join(V2, 'attempts', 'fixture.v2.jsonl'), stableJsonl([blockedAttempt]))]);
  return { policies, slots, parts, fixtureDraft };
}

export async function validateAuthoring(asOf: string) {
  if (!isIsoDate(asOf)) throw new Error(`Invalid --as-of date: ${asOf}`);
  const baselineActual = Object.fromEntries(await Promise.all(Object.entries(BASELINES).map(async ([path]) => [path, (await sha256File(join(ROOT, path))).toUpperCase()])));
  const baselineIssues = Object.entries(BASELINES).filter(([path, expected]) => baselineActual[path] !== expected).map(([path]) => `baseline hash drift: ${path}`);
  const { policies, slots, parts, fixtureDraft } = await ensurePlans(); const slotIssues = validateSlots(slots, policies); const duplicate = indexedDuplicateClusters([fixtureDraft]);
  const counts = { total: slots.length, classic: parts.classic.length, image: parts.image.length, charades: parts.charades.length, realDrafts: 1, approved: 0, blockedAttempts: 1 };
  const classicCategoryIds = [...new Set(parts.classic.map((slot) => slot.categoryId))].sort(); const imageCategoryIds = [...new Set(parts.image.map((slot) => slot.categoryId))].sort(); const charadesCategoryIds = [...new Set(parts.charades.map((slot) => slot.categoryId))].sort();
  const coverage = { reportVersion: AUTHORING_VERSION, asOf, structuralOnly: true, modalities: { classic: { plannedSlots: parts.classic.length, realDrafts: 1, reviewed: 0, approved: 0, playable: 0, categories: classicCategoryIds }, image: { plannedSlots: parts.image.length, realDrafts: 0, reviewed: 0, approved: 0, playable: 0, blockedMediaSlots: parts.image.length, categories: imageCategoryIds }, charades: { plannedSlots: parts.charades.length, realDrafts: 0, reviewed: 0, approved: 0, playableClassic: 0, categories: charadesCategoryIds } } };
  const readiness = { reportVersion: AUTHORING_VERSION, asOf, rule: 'approved, non-expired, schema-valid and policy-valid records in the exact selected pack only', standalone: Object.fromEntries(policies.map((policy) => [policy.categoryId, policy.modality === 'classic' ? { threshold: 224, approved: 0, ready: false } : { threshold: null, approved: 0, ready: false, behavior: policy.readiness.behavior }])), namedCombinedPacks: [{ name: 'all-classic-catalog', categoryIds: classicCategoryIds, approved: 0, ready: false }], charades: { categories: charadesCategoryIds, classicInventory: 0, reportedSeparately: true } };
  const provenance = { reportVersion: AUTHORING_VERSION, asOf, structuralSourcePackets: 1, humanFactVerifiedItems: 0, draftOnlyModelOutputs: 1, sourceRegistryEntries: sourceRegistry.entries.length, claimLevelVerification: false };
  const mediaRights = { reportVersion: AUTHORING_VERSION, asOf, imageCategories: imageCategoryIds, localPublishableQuestionMedia: 0, blockedSlots: parts.image.length, status: 'blocked_media' };
  const specialist = { reportVersion: AUTHORING_VERSION, asOf, categories: policies.filter((policy) => policy.review.specialist).map((policy) => policy.categoryId), specialistReceipts: 0, approved: 0 };
  const temporal = { reportVersion: AUTHORING_VERSION, asOf, approvedExpired: 0, draftExpired: 0, datedPolicyCategories: policies.filter((policy) => policy.temporal.class === 'dated').map((policy) => policy.categoryId), religiousRecheckOnWordingChange: policies.filter((policy) => policy.temporal.class === 'religious').map((policy) => policy.categoryId) };
  const report = { reportVersion: AUTHORING_VERSION, asOf, structuralOnly: true, claimLevelFactVerification: 'not performed', counts, slotIssues, baselineIssues, duplicate, partitions: { categoryPolicies: policies.length, classicCategories: classicCategoryIds.length, imageCategories: imageCategoryIds.length, charadesCategories: charadesCategoryIds.length }, yield: { plannedSlots: slots.length, realDrafts: 1, blockedSourceAttempts: 1, approved: 0, playable: 0 } };
  await Promise.all([writeFile(join(V2, 'reports', 'authoring-validation.v2.json'), stableJson(report)), writeFile(join(V2, 'reports', 'coverage.v2.json'), stableJson(coverage)), writeFile(join(V2, 'reports', 'duplicates.v2.json'), stableJson({ reportVersion: AUTHORING_VERSION, asOf, exactClusters: duplicate.exact, indexedCandidates: duplicate.candidates, unresolvedHighConfidenceClusters: 0, strategy: 'normalized exact hashes plus bounded Arabic shingle candidate index; no all-pairs scan' })), writeFile(join(V2, 'reports', 'source-review.v2.json'), stableJson(provenance)), writeFile(join(V2, 'reports', 'readiness.v2.json'), stableJson(readiness)), writeFile(join(V2, 'reports', 'temporal-expiry.v2.json'), stableJson(temporal)), writeFile(join(V2, 'reports', 'media-rights.v2.json'), stableJson(mediaRights)), writeFile(join(V2, 'reports', 'specialist-review.v2.json'), stableJson(specialist))]);
  await writeFile(join(V2, 'reports', 'baseline-receipt.v2.json'), stableJson({ receiptVersion: AUTHORING_VERSION, preserved: baselineActual, expected: BASELINES, verifiedAsOf: asOf }));
  await writeImmutable(join(V2, 'releases', 'baseline-unapproved.v2.json'), stableJson({ releaseId: 'v2-authoring-baseline-unapproved', asOf, policyVersion: AUTHORING_VERSION, categoryIds: policies.map((policy) => policy.categoryId), counts: { approved: 0, plannedSlotsExcluded: slots.length }, approvedContentHash: contentHash(''), immutable: true }));
  if (baselineIssues.length || slotIssues.length) throw new Error([...baselineIssues, ...slotIssues].join('\n'));
  return report;
}

export async function appendPromotion(inputPath: string, asOf: string) {
  const request = JSON.parse(await readFile(inputPath, 'utf8')) as { draft: V2Draft; policy: CategoryPolicy; packets: Array<{ packetId: string; checkedAt: string }>; receipts: Parameters<typeof promoteDraft>[3] };
  const result = promoteDraft(request.draft, request.policy, request.packets, request.receipts, asOf); const output = join(V2, 'approved', 'questions.v2.jsonl');
  const existing = await readFile(output, 'utf8').catch(() => ''); if (existing.split(/\r?\n/).some((line) => line && JSON.parse(line).id === result.approved.id)) return result;
  await appendFile(output, JSON.stringify(result.approved) + '\n'); return result;
}

async function main() { const command = process.argv[2] ?? 'validate'; const asOf = process.argv.includes('--as-of') ? process.argv[process.argv.indexOf('--as-of') + 1] : '2026-09-03'; if (command === 'plan') { const result = await ensurePlans(); console.log(`Generated ${result.slots.length} v2 authoring slots (${result.parts.classic.length} classic, ${result.parts.image.length} image, ${result.parts.charades.length} charades).`); return; } if (command === 'validate') { const report = await validateAuthoring(asOf); console.log(`Validated v2 authoring plan: ${report.counts.total} slots; ${report.counts.realDrafts} real draft; ${report.counts.approved} approved.`); return; } if (command === 'promote') { const input = process.argv[3]; if (!input) throw new Error('Usage: authoring-v2 promote <request.json> --as-of YYYY-MM-DD'); const result = await appendPromotion(resolve(input), asOf); console.log(`Promoted ${result.approved.id}.`); return; } if (command === 'release') { const [itemsPath, duplicateReportPath] = [process.argv[3], process.argv[4]]; if (!itemsPath || !duplicateReportPath) throw new Error('Usage: authoring-v2 release <runtime-items.json> <duplicates-report.json> --as-of YYYY-MM-DD'); const [items, duplicateReport, plan] = await Promise.all([readFile(resolve(itemsPath), 'utf8').then((text) => JSON.parse(text) as RuntimeItem[]), readFile(resolve(duplicateReportPath), 'utf8').then((text) => JSON.parse(text) as { unresolvedHighConfidenceClusters?: number }), ensurePlans()]); const manifest = createReleaseManifest(items, plan.policies, duplicateReport.unresolvedHighConfidenceClusters ?? 0, asOf); await writeImmutable(join(V2, 'releases', `${manifest.releaseId}.json`), stableJson(manifest)); console.log(`Created immutable release manifest ${manifest.releaseId}.`); return; } throw new Error(`Unknown command: ${command}`); }
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main().catch((error) => { console.error(error); process.exitCode = 1; });
