import { getApp, getApps, initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { FieldValue, getFirestore } from 'firebase-admin/firestore';
import { readFileSync } from 'node:fs';

const [uid, target] = process.argv.slice(2);
if (!uid || !/^[A-Za-z0-9_-]{1,128}$/.test(uid) || !target) throw new Error('Usage: tsx scripts/bootstrap-admin-principal.ts EXACT_UID emulator|staging');
if (target !== 'emulator' && target !== 'staging') throw new Error('Target must be exactly emulator or staging.');
if (target === 'emulator' && !process.env.FIRESTORE_EMULATOR_HOST) throw new Error('Emulator target requires FIRESTORE_EMULATOR_HOST.');
if (!getApps().length) initializeApp();
const firebaseConfig = process.env.FIREBASE_CONFIG ? JSON.parse(process.env.FIREBASE_CONFIG) as { projectId?: string } : {};
const projectId = getApp().options.projectId ?? process.env.GOOGLE_CLOUD_PROJECT ?? process.env.GCLOUD_PROJECT ?? firebaseConfig.projectId;
const stagingProject = process.env.ADMIN_BOOTSTRAP_STAGING_PROJECT;
const aliases = JSON.parse(readFileSync(new URL('../.firebaserc', import.meta.url), 'utf8')) as { projects?: { production?: string } };
const productionProject = aliases.projects?.production;
if (target === 'staging' && (!stagingProject || projectId !== stagingProject || !productionProject || projectId === productionProject)) throw new Error('Staging bootstrap requires an exact non-production ADMIN_BOOTSTRAP_STAGING_PROJECT matching the initialized project ID.');
if (target === 'emulator' && !projectId?.startsWith('demo-')) throw new Error('Emulator bootstrap requires an explicit demo-* initialized project ID.');
const auth = getAuth(); const db = getFirestore();
const user = await auth.getUser(uid);
if (user.disabled || !user.emailVerified || !user.providerData.some(provider => provider.providerId === 'google.com')) throw new Error('Bootstrap target must be an enabled, verified Google identity.');
const version = Number((await db.doc(`adminPrincipals/${uid}`).get()).data()?.authzVersion ?? 0) + 1;
const adminRoles = ['super_admin'];
await db.doc(`adminPrincipals/${uid}`).set({ enabled: true, identityReady: false, roles: adminRoles, authzVersion: version, bootstrappedFor: target, updatedAt: FieldValue.serverTimestamp() }, { merge: true });
await auth.setCustomUserClaims(user.uid, { ...(user.customClaims ?? {}), adminRoles, authzVersion: version });
await auth.revokeRefreshTokens(user.uid);
const batch = db.batch();
batch.set(db.doc(`adminPrincipals/${uid}`), { identityReady: true, identityUpdatedAt: FieldValue.serverTimestamp() }, { merge: true });
batch.set(db.doc('adminAuthzInvariants/superAdmins'), { revision: FieldValue.increment(1), updatedAt: FieldValue.serverTimestamp() }, { merge: true });
await batch.commit();
console.log(`Bootstrapped exact UID ${uid} for ${target}; refresh the Google ID token before testing.`);
