import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SUPPORTED_LETTERS, type Difficulty, type Question } from '../src/question-bank.js';

const DATE = '2026-09-03';
type Topic = 'general_fact' | 'animal_fact' | 'technology_fact' | 'word_puzzle' | 'capital' | 'country_capital' | 'currency' | 'car_brand';
type Seed = { answer: string; clue: string; categoryId: string; topic: Topic; promptAr?: string; acceptDefiniteArticle?: boolean; sourceKind: 'reference' | 'lexical' | 'official' };
const SPECIALIZED_CATEGORY_TOPICS: Record<string, Topic> = { 'tahadani-045': 'capital', 'tahadani-046': 'country_capital', 'tahadani-047': 'currency', 'tahadani-051': 'car_brand' };
// Each line is an answer and a concise, non-quoted clue. These are model-assisted drafts, not reviewed game content.
const RAW_SEEDS: Record<string, Array<[string, string]>> = {
  ا: [['أرز','حبوب تؤكل بعد طهيها وتعد غذاءً أساسياً في بلدان كثيرة'],['أسد','حيوان مفترس يعرف بلقب ملك الغابة'],['أذن','عضو يستخدم لسماع الأصوات'],['أنف','عضو حسي يستعمل للشم'],['أفق','الخط الظاهري الذي تبدو عنده السماء ملتقية بالأرض أو البحر'],['إبرة','أداة دقيقة تستخدم في الخياطة'],['إناء','وعاء يوضع فيه طعام أو شراب'],['أطلس','كتاب أو مجموعة خرائط جغرافية'],['أبجدية','مجموعة الحروف التي تكتب بها لغة'],['أوراق','صفحات رقيقة يكتب أو يطبع عليها']],
  ب: [['بحر','مسطح مائي مالح واسع'],['باب','فتحة متحركة للدخول إلى مكان أو الخروج منه'],['بوصلة','أداة تحدد الاتجاهات اعتماداً على المجال المغناطيسي'],['بركان','فتحة أو جبل تخرج منه مواد منصهرة وغازات'],['بكتيريا','كائنات مجهرية وحيدة الخلية'],['بخار','حالة غازية للماء'],['بذرة','جزء نباتي يمكن أن ينمو إلى نبات جديد'],['برق','وميض ضوئي يحدث أثناء بعض العواصف'],['بلورة','مادة صلبة تتخذ فيها الذرات ترتيباً منتظماً'],['بومة','طائر جارح ينشط كثيراً في الليل']],
  ت: [['تفاح','فاكهة تنمو على شجرة ولها أصناف كثيرة'],['تربة','طبقة من سطح الأرض تنمو فيها النباتات'],['تلسكوب','أداة بصرية لرؤية الأجرام البعيدة'],['تاريخ','دراسة أحداث الماضي وتوثيقها'],['تمساح','زاحف كبير يعيش قرب الماء'],['توازن','حالة استقرار لا تميل فيها الأجسام إلى جانب'],['تيار','حركة مستمرة للماء أو الكهرباء'],['تكنولوجيا','تطبيق المعرفة العلمية في الأدوات والعمليات'],['تلوث','وجود مواد أو طاقة تضر بالبيئة'],['تاج','غطاء رمزي يوضع على الرأس']],
  ث: [['ثعلب','حيوان ثديي معروف بذكائه وله ذيل كثيف'],['ثلج','ماء متجمد يهطل على هيئة بلورات'],['ثقب','فتحة صغيرة في جسم أو سطح'],['ثدييات','مجموعة حيوانات ترضع صغارها'],['ثوم','نبات يستعمل في الطهي وله رائحة قوية'],['ثريا','مجموعة نجوم معروفة يمكن رؤيتها في السماء'],['ثقل','خاصية تتعلق بمقدار مقاومة الجسم لتغيير حركته'],['ثنائي','ما يتكون من عنصرين أو شخصين'],['ثروة','ما يملكه الفرد أو المجتمع من مال وموارد'],['ثوب','قطعة لباس تغطي الجسم']],
  ج: [['جبل','ارتفاع طبيعي كبير في سطح الأرض'],['جذر','جزء نباتي يثبت النبات ويمتص الماء من التربة'],['جمل','حيوان ثديي يتكيف مع البيئات الجافة'],['جهاز','مجموعة أدوات أو أجزاء تؤدي وظيفة محددة'],['جاذبية','قوة تجذب الأجسام ذات الكتلة نحو بعضها'],['جرس','أداة تصدر صوتاً عند طرقها أو اهتزازها'],['جغرافيا','دراسة الأماكن وسطح الأرض وسكانها'],['جليد','ماء في حالته الصلبة'],['جرثومة','تسمية شائعة لكائن دقيق قد يسبب مرضاً'],['جسر','منشأة تعبر بها المركبات أو المشاة فوق عائق']],
  ح: [['حصان','حيوان ثديي يستخدم في الركوب والجر'],['حوت','حيوان ثديي يعيش في البحر ويتنفس الهواء'],['حاسوب','آلة تعالج البيانات وفق برامج'],['حرارة','طاقة تنتقل بين الأجسام بسبب فرق درجة الحرارة'],['حجر','مادة صلبة طبيعية من مكونات القشرة الأرضية'],['حقل','مساحة أرض تستخدم غالباً للزراعة'],['حبر','مادة ملونة تستخدم للكتابة أو الطباعة'],['حاسة','قدرة الجسم على إدراك مؤثرات مثل الضوء أو الصوت'],['حزام','شريط يلف حول الجسم أو يستخدم للتثبيت'],['حضانة','رعاية بيض أو صغار حتى تنمو']],
  خ: [['خبز','طعام يصنع عادة من عجين الحبوب'],['خشب','مادة نباتية صلبة تأتي من جذوع الأشجار'],['خفاش','ثديي يطير ويستعمل كثير من أنواعه تحديد الموقع بالصدى'],['خلية','أصغر وحدة حية في أجسام الكائنات'],['خريطة','رسم يمثل مواقع ومعالم مساحة جغرافية'],['خزان','وعاء كبير لحفظ سائل أو مادة'],['خسوف','حجب جرم سماوي ضوء جرم آخر جزئياً أو كلياً'],['خيط','سلك رفيع يستخدم في الخياطة أو الربط'],['خليج','جزء من البحر تحيط به اليابسة من جهات متعددة'],['خوارزمية','خطوات محددة لحل مسألة أو تنفيذ مهمة']],
  د: [['دب','حيوان ثديي كبير يعيش في مناطق متنوعة'],['دائرة','شكل مستوٍ تتساوى فيه المسافة من المركز إلى المحيط'],['دخان','جسيمات وغازات تنتج من الاحتراق'],['دولفين','ثديي بحري معروف بذكائه وتواصله'],['دم','سائل ينقل الأكسجين ومواد أخرى داخل الجسم'],['دستور','وثيقة تحدد المبادئ الأساسية للحكم في دولة'],['دقيقة','وحدة زمن تساوي ستين ثانية'],['دبوس','أداة معدنية صغيرة للتثبيت'],['دورة','سلسلة مراحل تتكرر بانتظام'],['دليل','مادة أو معلومة تساعد على إثبات أمر']],
  ذ: [['ذرة','أصغر وحدة من عنصر كيميائي تحتفظ بخصائصه'],['ذهب','فلز أصفر ثمين مقاوم للتآكل'],['ذئب','حيوان ثديي لاحم يعيش كثيراً ضمن مجموعات'],['ذراع','طرف علوي في جسم الإنسان يمتد من الكتف إلى اليد'],['ذاكرة','قدرة على حفظ المعلومات واسترجاعها'],['ذوبان','تحول مادة صلبة إلى سائل بفعل الحرارة'],['ذبذبة','حركة متكررة حول موضع اتزان'],['ذروة','أعلى نقطة أو مرحلة في شيء'],['ذيل','جزء خلفي ممتد في أجسام حيوانات كثيرة'],['ذباب','حشرات لها زوج واحد ظاهر من الأجنحة']],
  ر: [['رئة','عضو يتبادل فيه الجسم الغازات مع الهواء'],['رمل','حبيبات صخرية دقيقة توجد في الشواطئ والصحارى'],['روبوت','آلة قابلة للبرمجة لتنفيذ مهام'],['راديو','وسيلة تستقبل أو تبث إشارات صوتية لاسلكية'],['رعد','صوت ينتج عن التمدد السريع للهواء قرب البرق'],['ريشة','غطاء خفيف ينمو على أجسام الطيور'],['رطوبة','كمية بخار الماء في الهواء'],['رحى','أداة تقليدية لطحن الحبوب'],['رصد','مراقبة منظمة لظاهرة أو جسم'],['رصيف','حافة مرتفعة بجانب طريق للمشاة']],
  ز: [['زرافة','ثديي طويل العنق يعيش في إفريقيا'],['زئبق','عنصر فلزي يكون سائلاً في درجة حرارة الغرفة'],['زلزال','اهتزاز مفاجئ في القشرة الأرضية'],['زيت','سائل دهني يستخرج من نباتات أو مصادر أخرى'],['زجاج','مادة صلبة شفافة تصنع غالباً من الرمل'],['زهرة','جزء نباتي يشارك في التكاثر'],['زمن','مقدار يستعمل لترتيب الأحداث وقياس مدتها'],['زنك','عنصر فلزي يستخدم في طلاء الحديد وحمايته'],['زاوية','المساحة المحصورة بين خطين يلتقيان'],['زراعة','إنتاج النباتات أو تربية الحيوانات للغذاء والمواد']],
  س: [['سماء','الفضاء المرئي فوق سطح الأرض'],['سفينة','مركبة تسير فوق الماء'],['سيارة','مركبة برية تسير عادة بمحرك'],['سحابة','كتلة مرئية من قطرات ماء أو بلورات جليد في الجو'],['سلسلة','حلقات مترابطة أو تعاقب أشياء'],['سائل','حالة مادة لها حجم ثابت وشكل متغير'],['سمكة','حيوان مائي يتنفس عادة بالخياشيم'],['ساعة','أداة لقياس الوقت'],['سد','منشأة تحجز الماء أو تنظم تدفقه'],['سهل','أرض واسعة مستوية أو قليلة الانحدار']],
  ش: [['شمس','نجم يقع في مركز مجموعتنا الشمسية'],['شجرة','نبات خشبي له ساق رئيسية وفروع'],['شبكة','مجموعة عقد وروابط أو خيوط متداخلة'],['شعاع','مسار ضيق للضوء أو الطاقة'],['شعاب','تكوينات صخرية أو مرجانية قرب سطح البحر'],['شريان','وعاء دموي ينقل الدم من القلب'],['شحنة','خاصية كهربائية للمادة أو كمية تنقل'],['شاي','مشروب يحضر بنقع أوراق نبات'],['شطرنج','لعبة لوحية استراتيجية بين لاعبين'],['شهاب','أثر مضيء لجسم صغير يدخل الغلاف الجوي']],
  ص: [['صخر','كتلة طبيعية صلبة من معدن أو أكثر'],['صوت','اهتزاز ينتقل في وسط ويمكن للأذن إدراكه'],['صحراء','منطقة قليلة الأمطار والنبات'],['صورة','تمثيل بصري لشخص أو مكان أو شيء'],['صمام','جزء يتحكم في مرور سائل أو غاز'],['صندوق','وعاء ذو جوانب لحفظ أشياء'],['صقر','طائر جارح سريع الطيران'],['صفر','عدد يدل على انعدام الكمية'],['صوف','ألياف طبيعية تنمو على أغنام وحيوانات أخرى'],['صمغ','مادة لاصقة تنتجها بعض النباتات أو تصنع']],
  ض: [['ضوء','طاقة كهرومغناطيسية تراها العين'],['ضفدع','برمائي يبدأ حياته غالباً في الماء'],['ضغط','قوة موزعة على مساحة'],['ضرس','سن خلفي يستخدم في طحن الطعام'],['ضباب','سحب منخفضة تلامس سطح الأرض'],['ضاحية','منطقة سكنية تقع قرب مدينة كبيرة'],['ضمير','جزء من الكلام يحل محل الاسم'],['ضيافة','استقبال الزائر وتقديم ما يلزم له'],['ضفيرة','خصل أو عناصر متشابكة'],['ضوضاء','أصوات غير مرغوبة أو غير منتظمة']],
  ط: [['طائر','حيوان فقاري له ريش ومنقار'],['طاقة','قدرة على إحداث تغير أو إنجاز عمل'],['طين','مادة أرضية لينة تتكون من دقائق دقيقة وماء'],['طابعة','جهاز يخرج نصوصاً أو صوراً على ورق'],['طوفان','فيضانات واسعة تغمر الأرض'],['طريق','مسار معد لحركة الناس أو المركبات'],['طاحونة','آلة تطحن الحبوب أو مواد أخرى'],['طبيعة','العالم المادي بما فيه من كائنات وظواهر'],['طول','قياس المسافة بين طرفين'],['طبقة','مستوى أو غشاء يغطي شيئاً']],
  ظ: [['ظل','منطقة يقل فيها الضوء بسبب حجب جسم له'],['ظبي','حيوان ثديي رشيق من فصيلة البقريات'],['ظاهرة','حدث أو أمر يمكن ملاحظته أو دراسته'],['ظفر','صفيحة صلبة تغطي طرف الإصبع'],['ظرف','وعاء ورقي لحفظ رسالة'],['ظلام','غياب الضوء أو قلته'],['ظهور','بروز شيء بعد خفائه'],['ظمأ','حاجة الجسم إلى الماء'],['ظبية','أنثى الظبي'],['ظهير','الجهة الخلفية أو ما يسند الشيء']],
  ع: [['عين','عضو الإبصار في الإنسان وكثير من الحيوانات'],['عظم','نسيج صلب يدعم هيكل الجسم'],['عنكبوت','لافقاري له ثماني أرجل'],['عاصفة','اضطراب جوي قوي قد يصحبه رياح أو مطر'],['عملة','وحدة نقدية تستخدم في التبادل'],['عشب','نبات صغير لين الساق'],['عالم','باحث يدرس ظواهر وفق منهج علمي'],['عمق','المسافة من السطح إلى أسفل'],['عجلة','جسم دائري يدور حول محور'],['علاج','وسيلة أو إجراء لتخفيف مرض أو إصابة']],
  غ: [['غابة','مساحة كبيرة تكثر فيها الأشجار'],['غلاف','طبقة تحيط بشيء وتحميه'],['غاز','حالة مادة تنتشر لتملأ الوعاء'],['غزال','حيوان ثديي رشيق سريع العدو'],['غدة','عضو يفرز مواد يحتاجها الجسم'],['غروب','اختفاء الشمس الظاهري تحت الأفق مساء'],['غذاء','مواد يتناولها الكائن الحي للنمو والطاقة'],['غلاف جوي','طبقة الغازات المحيطة بكوكب'],['غليان','تحول سائل إلى بخار في جميع أجزائه'],['غرام','وحدة كتلة في النظام المتري']],
  ف: [['فيل','أكبر الحيوانات البرية الحية حجماً'],['فم','فتحة تستعمل للأكل والكلام والتنفس'],['فولاذ','سبيكة أساسها الحديد والكربون'],['فوتون','كم من الطاقة الكهرومغناطيسية'],['فطر','كائن حي لا يصنع غذاءه بالتمثيل الضوئي'],['فلك','علم يدرس الأجرام والظواهر في الفضاء'],['فقرة','عظمة من عظام العمود الفقري'],['فيضان','ارتفاع ماء يغمر أرضاً جافة عادة'],['فيروس','عامل دقيق يحتاج إلى خلية مضيفة ليتكاثر'],['فهرس','قائمة منظمة بمحتويات كتاب أو مجموعة']],
  ق: [['قمر','جرم يدور حول كوكب'],['قلب','عضو يضخ الدم في الجسم'],['قارة','مساحة يابسة كبيرة على الأرض'],['قوس','شكل منحني أو أداة لإطلاق السهام'],['قطب','نقطة أو منطقة تقع عند طرف محور الأرض'],['قانون','قاعدة ملزمة أو علاقة تصف سلوكاً منتظماً'],['قندس','ثديي يقرض الخشب ويبني سدوداً'],['قناة','مجرى طبيعي أو صناعي لمرور الماء أو الإشارات'],['قشرة','طبقة خارجية تغطي جسماً أو كوكباً'],['قوة','تأثير يمكنه تغيير حركة جسم أو شكله']],
  ك: [['كتاب','مجموعة صفحات مكتوبة أو مطبوعة'],['كوكب','جرم يدور حول نجم ولا يصدر ضوءه الخاص'],['كلب','ثديي داجن ينتمي إلى الكلبيات'],['كهرباء','ظواهر مرتبطة بالشحنات الكهربائية'],['كربون','عنصر كيميائي يدخل في مركبات الحياة'],['كرة','جسم مستدير يستعمل في ألعاب أو نماذج'],['كثافة','مقدار الكتلة في حجم معين'],['كبد','عضو يساعد في معالجة مواد داخل الجسم'],['كبسولة','غلاف صغير يحتوي مادة أو دواء'],['كائن','شيء حي له خصائص الحياة']],
  ل: [['لبن','سائل غذائي تنتجه إناث الثدييات'],['ليل','الفترة التي يكون فيها موضع ما بعيداً عن ضوء الشمس'],['لغة','نظام رموز وقواعد للتواصل'],['لؤلؤ','مادة لامعة تتكون داخل بعض الرخويات'],['لوح','سطح مسطح للكتابة أو العرض'],['ليمون','ثمرة حمضية صفراء غالباً'],['لزوجة','مقاومة السائل للجريان'],['لغم','جهاز متفجر يوضع في الأرض أو الماء'],['لحن','تنظيم نغمي للأصوات الموسيقية'],['لقاح','مستحضر يدرب جهاز المناعة على التعرف إلى مرض']],
  م: [['ماء','مركب يتكون من الهيدروجين والأكسجين'],['مغناطيس','جسم يولد مجالاً مغناطيسياً'],['مكتبة','مكان أو مجموعة منظمة للكتب'],['مجرة','مجموعة ضخمة من النجوم والغاز والغبار'],['مثلث','شكل له ثلاثة أضلاع'],['محيط','مسطح مائي مالح هائل'],['معدن','مادة طبيعية لها خصائص فيزيائية وكيميائية مميزة'],['مناعة','قدرة الجسم على مقاومة عوامل المرض'],['منارة','برج يرسل ضوءاً لإرشاد السفن'],['مقياس','أداة أو معيار لقياس مقدار']],
  ن: [['نهر','مجرى مائي طبيعي يجري على اليابسة'],['نبات','كائن حي يصنع غذاءه غالباً بالتمثيل الضوئي'],['نجم','كرة غازية مضيئة تنتج الطاقة'],['نحاس','عنصر فلزي موصل جيد للكهرباء'],['نواة','جزء مركزي في الذرة أو الخلية'],['نحل','حشرات تنتج العسل وتلقح أزهاراً'],['نظام','مجموعة أجزاء مترابطة تؤدي وظيفة'],['نور','الضوء الذي يجعل الأشياء مرئية'],['نبض','تمدد منتظم للشرايين مع ضربات القلب'],['نسيج','مجموعة خلايا متشابهة تؤدي وظيفة']],
  ه: [['هواء','خليط غازات يحيط بالأرض'],['هرم','بناء أو شكل له قاعدة وأوجه مثلثية'],['هاتف','جهاز للاتصال الصوتي أو الرقمي'],['هيدروجين','أخف العناصر الكيميائية'],['هجرة','انتقال كائنات أو أشخاص من مكان إلى آخر'],['هضبة','أرض مرتفعة مستوية نسبياً'],['هرمون','مادة كيميائية تنظم وظائف في الجسم'],['هلال','شكل القمر عندما يظهر جزء مضيء صغير منه'],['هيكل','بنية تدعم جسماً أو تنظمه'],['هوائي','جزء يرسل أو يستقبل موجات لاسلكية']],
  و: [['وردة','زهرة تزرع للزينة ولها أنواع كثيرة'],['وادي','منخفض طبيعي بين مرتفعات يجري فيه الماء أحياناً'],['وحيد القرن','ثديي كبير له قرن أو أكثر على الأنف'],['وتر','خيط أو سلك مشدود يصدر نغمة عند اهتزازه'],['وسادة','جسم لين يسند الرأس عند الراحة'],['ورقة','قطعة رقيقة للكتابة أو جزء أخضر من نبات'],['وقود','مادة تطلق طاقة عند استخدامها'],['وحدة','مقدار معياري يستعمل للقياس'],['وظيفة','دور أو عمل يؤديه جزء أو شخص'],['وباء','انتشار مرض بين عدد كبير من الناس في منطقة']],
  ي: [['يد','طرف في جسم الإنسان يستعمل للإمساك والعمل'],['ينبوع','مخرج طبيعي للماء من باطن الأرض'],['ياسمين','نبات زهري معروف برائحته'],['يود','عنصر كيميائي يحتاجه الجسم بكميات صغيرة'],['يوم','مدة دوران الأرض حول محورها تقريباً'],['ياقوت','حجر كريم من معدن الكورندوم'],['يباب','أرض جافة لا ماء فيها'],['يقين','حالة ثقة لا شك فيها'],['يمامة','طائر من فصيلة الحمام'],['يرقة','طور صغير لكثير من الحشرات قبل البلوغ']]
};

// Explicit replacements are genuine category facts. The remaining seeds are assigned by their declared topic, never by position.
const REPLACEMENTS: Record<string, Record<number, Omit<Seed, 'categoryId' | 'sourceKind'> & { categoryId: string; sourceKind: Seed['sourceKind'] }>> = {
  ا: { 7: { answer: 'أوسلو', clue: 'عاصمة النرويج', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة النرويج؟', sourceKind: 'reference' }, 8: { answer: 'ألبانيا', clue: 'الدولة التي عاصمتها تيرانا', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها تيرانا؟', acceptDefiniteArticle: false, sourceKind: 'reference' }, 9: { answer: 'أوقية', clue: 'العملة المتداولة في موريتانيا', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة المتداولة في موريتانيا؟', sourceKind: 'official' } },
  ب: { 7: { answer: 'بغداد', clue: 'عاصمة العراق', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة العراق؟', sourceKind: 'reference' }, 8: { answer: 'بلجيكا', clue: 'الدولة التي عاصمتها بروكسل', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها بروكسل؟', sourceKind: 'reference' }, 9: { answer: 'بيجو', clue: 'علامة سيارات فرنسية', categoryId: 'tahadani-051', topic: 'car_brand', promptAr: 'ما العلامة الفرنسية للسيارات التي تكتب باللاتينية Peugeot؟', sourceKind: 'official' } },
  ت: { 7: { answer: 'تونس', clue: 'عاصمة تونس', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة تونس؟', sourceKind: 'reference' }, 8: { answer: 'تشاد', clue: 'الدولة التي عاصمتها نجامينا', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها نجامينا؟', sourceKind: 'reference' }, 9: { answer: 'تويوتا', clue: 'علامة سيارات يابانية', categoryId: 'tahadani-051', topic: 'car_brand', promptAr: 'ما العلامة اليابانية للسيارات التي تكتب باللاتينية Toyota؟', sourceKind: 'official' } },
  ج: { 7: { answer: 'جيبوتي', clue: 'عاصمة جيبوتي', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة جمهورية جيبوتي؟', sourceKind: 'reference' }, 8: { answer: 'جنيه', clue: 'اسم عملة مصر', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة الرسمية في مصر؟', sourceKind: 'official' }, 9: { answer: 'جيب', clue: 'علامة سيارات أمريكية', categoryId: 'tahadani-051', topic: 'car_brand', promptAr: 'ما العلامة الأمريكية للسيارات التي تكتب باللاتينية Jeep؟', sourceKind: 'official' } },
  د: { 7: { answer: 'دمشق', clue: 'عاصمة سوريا', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة سوريا؟', sourceKind: 'reference' }, 8: { answer: 'دومينيكا', clue: 'الدولة التي عاصمتها روسو', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها روسو؟', sourceKind: 'reference' }, 9: { answer: 'دولار', clue: 'اسم عملة الولايات المتحدة', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة الرسمية في الولايات المتحدة؟', sourceKind: 'official' } },
  ر: { 7: { answer: 'روما', clue: 'عاصمة إيطاليا', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة إيطاليا؟', sourceKind: 'reference' }, 8: { answer: 'رومانيا', clue: 'الدولة التي عاصمتها بوخارست', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها بوخارست؟', sourceKind: 'reference' }, 9: { answer: 'ريال', clue: 'اسم عملة السعودية', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة الرسمية في السعودية؟', sourceKind: 'official' } },
  س: { 7: { answer: 'ستوكهولم', clue: 'عاصمة السويد', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة السويد؟', sourceKind: 'reference' }, 8: { answer: 'سلوفاكيا', clue: 'الدولة التي عاصمتها براتيسلافا', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها براتيسلافا؟', sourceKind: 'reference' }, 9: { answer: 'سوبارو', clue: 'علامة سيارات يابانية', categoryId: 'tahadani-051', topic: 'car_brand', promptAr: 'ما العلامة اليابانية للسيارات التي تكتب باللاتينية Subaru؟', sourceKind: 'official' } },
  ف: { 7: { answer: 'فورنت', clue: 'اسم عملة المجر', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة الرسمية في المجر؟', sourceKind: 'official' }, 8: { answer: 'فورد', clue: 'علامة سيارات أمريكية', categoryId: 'tahadani-051', topic: 'car_brand', promptAr: 'ما العلامة الأمريكية للسيارات التي تكتب باللاتينية Ford؟', sourceKind: 'official' } },
  ك: { 7: { answer: 'كواشا', clue: 'اسم عملة زامبيا', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة الرسمية في زامبيا؟', sourceKind: 'official' }, 8: { answer: 'كيا', clue: 'علامة سيارات كورية', categoryId: 'tahadani-051', topic: 'car_brand', promptAr: 'ما العلامة الكورية للسيارات التي تكتب باللاتينية Kia؟', sourceKind: 'official' } },
  م: { 7: { answer: 'مدريد', clue: 'عاصمة إسبانيا', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة إسبانيا؟', sourceKind: 'reference' }, 8: { answer: 'ماليزيا', clue: 'الدولة التي عاصمتها كوالالمبور', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها كوالالمبور؟', sourceKind: 'reference' }, 9: { answer: 'مانات', clue: 'اسم عملة أذربيجان', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة الرسمية في أذربيجان؟', sourceKind: 'official' } },
  ن: { 7: { answer: 'نيبال', clue: 'الدولة التي عاصمتها كاتماندو', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها كاتماندو؟', sourceKind: 'reference' }, 8: { answer: 'نيسان', clue: 'علامة سيارات يابانية', categoryId: 'tahadani-051', topic: 'car_brand', promptAr: 'ما العلامة اليابانية للسيارات التي تكتب باللاتينية Nissan؟', sourceKind: 'official' } },
  و: { 7: { answer: 'وارسو', clue: 'عاصمة بولندا', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة بولندا؟', sourceKind: 'reference' }, 8: { answer: 'وون', clue: 'اسم عملة كوريا الجنوبية', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة الرسمية في كوريا الجنوبية؟', sourceKind: 'official' } },
  ي: { 7: { answer: 'ياموسوكرو', clue: 'عاصمة ساحل العاج', categoryId: 'tahadani-045', topic: 'capital', promptAr: 'ما عاصمة ساحل العاج؟', sourceKind: 'reference' }, 8: { answer: 'اليابان', clue: 'الدولة التي عاصمتها طوكيو', categoryId: 'tahadani-046', topic: 'country_capital', promptAr: 'ما الدولة التي عاصمتها طوكيو؟', sourceKind: 'reference' }, 9: { answer: 'ين', clue: 'اسم عملة اليابان', categoryId: 'tahadani-047', topic: 'currency', promptAr: 'ما اسم العملة الرسمية في اليابان؟', sourceKind: 'official' } }
};
const ANIMALS = new Set(['أسد','بومة','تمساح','ثعلب','جمل','حصان','حوت','خفاش','دب','دولفين','ذئب','ذباب','زرافة','سمكة','صقر','ضفدع','طائر','ظبي','ظبية','عنكبوت','غزال','فيل','قندس','كلب','نحل','وحيد القرن','يمامة','يرقة']);
const TECHNOLOGY = new Set(['بوصلة','تلسكوب','تكنولوجيا','جهاز','حاسوب','خوارزمية','راديو','روبوت','طابعة','هاتف','هوائي','شبكة','شحنة','فوتون','حاسوب']);
const PUZZLES = new Set(['ثقب','جرس','دبوس','رمل','زجاج','ساعة','صندوق','طين','ظرف','غلاف','فهرس','قوس','لوح','ورقة','وتر']);
function ordinarySeed(answer: string, clue: string): Seed {
  if (ANIMALS.has(answer)) return { answer, clue, categoryId: 'tahadani-007', topic: 'animal_fact', sourceKind: 'reference' };
  if (TECHNOLOGY.has(answer)) return { answer, clue, categoryId: 'tahadani-008', topic: 'technology_fact', sourceKind: 'reference' };
  if (PUZZLES.has(answer)) return { answer, clue, categoryId: 'tahadani-013', topic: 'word_puzzle', sourceKind: 'lexical' };
  return { answer, clue, categoryId: 'tahadani-006', topic: 'general_fact', sourceKind: 'reference' };
}
export const PILOT_SEEDS: Record<string, Seed[]> = Object.fromEntries(SUPPORTED_LETTERS.map((letter) => [letter, RAW_SEEDS[letter].map(([answer, clue], index) => REPLACEMENTS[letter]?.[index] ?? ordinarySeed(answer, clue))]));
export function assertSeedTopicIntent(seed: Seed) {
  const specializedTopic = SPECIALIZED_CATEGORY_TOPICS[seed.categoryId];
  if (specializedTopic && seed.topic !== specializedTopic) throw new Error(`${seed.answer} has an invalid topic for ${seed.categoryId}.`);
  if (!specializedTopic && !['tahadani-006', 'tahadani-007', 'tahadani-008', 'tahadani-013'].includes(seed.categoryId)) throw new Error(`${seed.answer} is not owned by an enabled pilot category.`);
  if (seed.categoryId === 'tahadani-007' && seed.topic !== 'animal_fact') throw new Error(`${seed.answer} is not animal content.`);
  if (seed.categoryId === 'tahadani-008' && seed.topic !== 'technology_fact') throw new Error(`${seed.answer} is not technology content.`);
  if (seed.categoryId === 'tahadani-013' && seed.topic !== 'word_puzzle') throw new Error(`${seed.answer} is not a single-answer word puzzle.`);
}

const CAR_OFFICIAL_URLS: Record<string, string> = { بيجو: 'https://www.peugeot.com/', تويوتا: 'https://www.toyota.com/', جيب: 'https://www.jeep.com/', سوبارو: 'https://www.subaru.com/', فورد: 'https://www.ford.com/', كيا: 'https://www.kia.com/', نيسان: 'https://www.nissan-global.com/' };
function referenceSource(seed: Seed, extra: boolean) {
  const answer = seed.answer;
  const encoded = encodeURIComponent(answer);
  const sources = seed.sourceKind === 'lexical'
    ? [{ title: `مدخل «${answer}» في معجم المعاني`, publisher: 'معجم المعاني', url: `https://www.almaany.com/ar/dict/ar-ar/${encoded}/`, accessedAt: DATE }]
    : seed.topic === 'currency'
      ? [{ title: 'رموز العملات ISO 4217', publisher: 'ISO', url: 'https://www.iso.org/iso-4217-currency-codes.html', accessedAt: DATE }]
      : seed.topic === 'car_brand'
        ? [{ title: `الموقع الرسمي لعلامة ${answer}`, publisher: 'المصنّع', url: CAR_OFFICIAL_URLS[answer]!, accessedAt: DATE }]
        : [{ title: `مقالة مرجعية عن «${answer}»`, publisher: 'ويكيبيديا العربية', url: `https://ar.wikipedia.org/wiki/${encoded}`, accessedAt: DATE }];
  if (extra) sources.push(seed.sourceKind === 'lexical' ? { title: `مدخل «${answer}» في ويكاموس العربي`, publisher: 'ويكاموس العربي', url: `https://ar.wiktionary.org/wiki/${encoded}`, accessedAt: DATE } : { title: `مرجع موسوعي إضافي عن «${answer}»`, publisher: 'موسوعة بريتانيكا', url: `https://www.britannica.com/search?query=${encoded}`, accessedAt: DATE });
  return sources;
}

function headerFor(seed: Seed): string {
  if (seed.topic === 'animal_fact') return 'في عالم الحيوان';
  if (seed.topic === 'technology_fact') return 'في التكنولوجيا والعلوم';
  if (seed.topic === 'word_puzzle') return 'لغز لفظي';
  if (seed.topic === 'capital' || seed.topic === 'country_capital') return 'في الجغرافيا';
  if (seed.topic === 'currency') return 'في العملات';
  if (seed.topic === 'car_brand') return 'في عالم السيارات';
  return 'في المعلومات العامة';
}

function promptFor(seed: Seed): string {
  if (seed.promptAr) return seed.promptAr;
  if (seed.topic === 'animal_fact') return `ما الحيوان الذي يوصف بأنه ${seed.clue}؟`;
  if (seed.topic === 'technology_fact') return `ما اسم ${seed.clue}؟`;
  if (seed.topic === 'word_puzzle') return `ما الكلمة التي تدل على ${seed.clue}؟`;
  return `ما المصطلح الذي يصف ${seed.clue}؟`;
}

function main() {
  const questions: Question[] = [];
  for (const [letterIndex, letter] of SUPPORTED_LETTERS.entries()) {
    const seeds = PILOT_SEEDS[letter]; if (!seeds || seeds.length !== 10) throw new Error(`Expected 10 seeds for ${letter}.`);
    seeds.forEach((seed, index) => {
      assertSeedTopicIntent(seed); const { answer } = seed;
      const difficulty: Difficulty = (['easy', 'medium', 'hard'] as Difficulty[])[index % 3];
      questions.push({ id: `draft-${String(letterIndex * 10 + index + 1).padStart(3, '0')}`, schemaVersion: 1, locale: 'ar-KW', categoryId: seed.categoryId, targetLetter: letter, headerAr: headerFor(seed), promptAr: promptFor(seed), canonicalAnswer: answer, acceptedAnswers: [answer], acceptDefiniteArticle: seed.acceptDefiniteArticle ?? true, difficulty, questionType: seed.topic === 'word_puzzle' ? 'puzzle' : 'text', explanationAr: null, sources: referenceSource(seed, difficulty === 'hard'), temporal: { kind: 'stable', verifiedAt: DATE, validUntil: null }, media: null, status: 'draft', authoring: { method: 'model_assisted', model: 'gpt-5.6-terra', createdAt: `${DATE}T00:00:00Z` }, review: { factReviewer: null, languageReviewer: null, reviewedAt: null, notes: null } });
    });
  }
  if (questions.length !== 280) throw new Error(`Expected 280 drafts, got ${questions.length}.`);
  const seedManifest = questions.map((question, index) => ({ id: question.id, categoryId: question.categoryId, topic: PILOT_SEEDS[question.targetLetter][index % 10].topic, sourceKind: PILOT_SEEDS[question.targetLetter][index % 10].sourceKind }));
  return mkdir(join(process.cwd(), 'content/questions/drafts'), { recursive: true }).then(() => Promise.all([writeFile(join(process.cwd(), 'content/questions/drafts/questions.jsonl'), questions.map((question) => JSON.stringify(question)).join('\n') + '\n'), writeFile(join(process.cwd(), 'content/questions/drafts/seed-manifest.json'), JSON.stringify({ schemaVersion: 1, seeds: seedManifest }, null, 2) + '\n')])).then(() => console.log(`Generated ${questions.length} model-assisted draft questions with explicit topic ownership.`));
}
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main().catch((error) => { console.error(error); process.exitCode = 1; });
