import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type Candidate, type RemediationDisposition } from './question-bank-v3-review.js';
import { materializeAcademyPackets } from './academy-packets-v3-next.js';
import { materializeSpecializedPackets, reviseSpecialized, unresolvedSpecializedIds, validateSpecializedPackets } from './specialized-packets-v3.js';
import { writeV31CategoryArtifacts } from './question-bank-v3.1.js';

const ROOT = process.cwd(); const OUT = join(ROOT, 'content/question-bank-v3'); const asOf = '2026-09-04';
const rewritten = new Set(['draft-035','draft-043','draft-051','draft-071','draft-083','draft-117','draft-134','draft-146','draft-163','draft-204','draft-266','draft-033','draft-046','draft-136','draft-165','draft-182','draft-225','draft-264']);
const promptOverrides: Record<string, string> = {
  'draft-033': 'ما الاسم الدال على فجوة نافذة في جدار أو جسم صلب؟', 'draft-035': 'ما اسم النبات ذي الفصوص البيضاء الذي يستعمل لتتبيل الطعام؟', 'draft-037': 'ما اسم قوة الجاذبية المؤثرة في جسم؟', 'draft-043': 'ما الحيوان ذو السنام الذي يعتمد عليه في التنقل في الصحراء؟', 'draft-046': 'ما الأداة ذات الجرس المعدني التي تصدر رنيناً عند تحريكها؟', 'draft-051': 'ما الحيوان المدجن الذي يمتطى ويستخدم في سباقات الفروسية؟', 'draft-071': 'ما الحيوان الثديي ذو الفراء الذي يسبت بعض أنواعه شتاءً؟', 'draft-083': 'ما الحيوان اللاحم من الكلبيات الذي يعوي ويعيش في قطعان؟', 'draft-117': 'ما الحيوان الفقاري المائي الذي يتنفس بالخياشيم وله زعانف؟', 'draft-134': 'ما التمثيل البصري الناتج عن التقاط الضوء بكاميرا أو رسمه؟', 'draft-136': 'ما الوعاء الصلب ذو الغطاء المستخدم لحفظ أشياء ونقلها؟', 'draft-146': 'ما المنطقة السكنية الواقعة خارج المركز الرئيس للمدينة؟', 'draft-163': 'ما الاسم العلمي لحدث يمكن رصده وقياسه في الطبيعة؟', 'draft-165': 'ما الغلاف الورقي المغلق الذي توضع فيه رسالة قبل إرسالها؟', 'draft-180': 'ما المصطلح العام لخطة أو تدخل يهدف إلى معالجة مرض أو إصابة؟', 'draft-182': 'ما الطبقة الخارجية التي تحيط بكتاب أو منتج لتحميه؟', 'draft-204': 'ما الأداة المقوسة التي يطلق بها السهم؟', 'draft-225': 'ما السطح الصلب المستوي المستخدم للكتابة بالطباشير؟', 'draft-230': 'ما المستحضر الحيوي الذي يدرّب جهاز المناعة على التعرف إلى ممرض؟', 'draft-264': 'ما الخيط المشدود في آلة موسيقية والذي يهتز لإنتاج نغمة؟', 'draft-266': 'ما الجزء الأخضر المسطح من النبات الذي يجري فيه معظم البناء الضوئي؟',
};
Object.assign(promptOverrides, {
  'draft-028': 'ما عاصمة الجمهورية الواقعة في شمال أفريقيا بين الجزائر وليبيا؟',
  'draft-046': 'ما الأداة المعدنية التي تصدر رنيناً عند تحريكها؟',
  'draft-048': 'ما عاصمة الدولة الواقعة على خليج عدن عند مدخل البحر الأحمر؟',
  'draft-054': 'كيف نسمّي الطاقة التي تنتقل بين الأجسام بسبب اختلاف درجتيهما؟',
  'draft-121': 'ما التسمية العربية التي تطلق على نجم يقع في مركز منظومتنا الكوكبية؟',
  'draft-204': 'ما الأداة المنحنية التي يطلق بها السهم؟',
  'draft-232': 'أي كلمة عربية تدل على جسم يولد مجالاً يجذب مواد معينة؟',
});
function rewriteAcademyPrompt(playable: Record<string, unknown>) {
  const raw = String(playable.promptAr).replace(/^ما المصطلح الذي يصف\s*/, '').replace(/^ما الكلمة التي تدل على\s*/, '').replace(/^ما اسم\s*/, '').replace(/[؟?]$/,'').trim();
  const source = raw.startsWith('ما ') ? `الشيء الذي ${raw.slice(3)}` : raw;
  const forms = [(meaning: string) => `أي كلمة عربية تدل على ${meaning}؟`, (meaning: string) => `كيف يُسمّى ${meaning} في العربية؟`, (meaning: string) => `ما اللفظ المناسب لوصف ${meaning}؟`, (meaning: string) => `أي اسم يعبّر عن ${meaning}؟`, (meaning: string) => `ما التسمية العربية التي تطلق على ${meaning}؟`, (meaning: string) => `بأي لفظ نعبّر عن ${meaning}؟`, (meaning: string) => `ما الكلمة الدالة على ${meaning}؟`, (meaning: string) => `كيف نسمّي ${meaning}؟`];
  const answer = String(playable.canonicalAnswer ?? '');
  return forms[[...answer].reduce((sum, character) => sum + character.codePointAt(0)!, 0) % forms.length](source || 'هذا المعنى في الاستعمال العربي');
}
function academyDifficulty(playable: Record<string, unknown>, promptAr: string): 'easy' | 'medium' | 'hard' {
  // Content rubric: direct everyday object/organism clues are easy; learned relations are medium; narrow abstract or technical senses are hard.
  const text = `${promptAr} ${String(playable.canonicalAnswer ?? '')}`;
  if (/قوة|ظاهرة|منظومة|نظام|تنظيم|علمي|مجازي|مفهوم|مجرد|إجراء|خاصية|عملية/.test(text)) return 'hard';
  if (/حيوان|نبات|طعام|لون|أداة|وعاء|سطح|كتاب|رسالة|ماء|صوت/.test(text)) return 'easy';
  return 'medium';
}
function academyPlayable(sourceId: string, playable: Record<string, unknown>) {
  const replacement = sourceId === 'draft-103' ? { canonicalAnswer: 'زنبق', acceptedAnswers: ['زنبق'], promptAr: 'ما اسم نبات زهري من فصيلة نباتات الأبصال؟' } : sourceId === 'draft-180' ? { canonicalAnswer: 'علم', acceptedAnswers: ['علم'], promptAr: 'ما الاسم الذي يطلق على المعرفة المنظمة المبنية على الملاحظة والدراسة؟' } : sourceId === 'draft-230' ? { canonicalAnswer: 'لعبة', acceptedAnswers: ['لعبة'], promptAr: 'ما الاسم الذي يطلق على نشاط ترفيهي له قواعد ويُمارس للفوز؟' } : {};
  const revised = { ...playable, ...replacement };
  const promptAr = replacement.promptAr ?? promptOverrides[sourceId] ?? rewriteAcademyPrompt(revised);
  return { ...revised, promptAr, difficulty: academyDifficulty(revised, promptAr), explanationAr: null };
}
const sha = (raw: string) => createHash('sha256').update(raw).digest('hex');
function v1Disposition(id: string): [RemediationDisposition, string] { if (id === 'draft-180' || id === 'draft-230') return ['needs_evidence','The health-sensitive legacy item was replaced with a non-medical lexical clue; human dictionary-sense selection remains required.']; if (id === 'draft-037') return ['needs_evidence','Corrected the inertia misconception: ثقل is the force of gravity on a body; claim-specific evidence remains required.']; if (rewritten.has(id)) return ['needs_evidence','Ambiguous legacy wording was rewritten into a single-concept clue; claim-specific authoritative evidence remains required.']; return ['needs_evidence','Imported legacy draft has no claim-specific authoritative evidence packet.']; }
function v21Disposition(id: string): [RemediationDisposition, string] { if (id.includes('huroof-001') || id.includes('huroof-002')) return ['needs_evidence','Research basis or wording correction exists, but claim-specific authoritative evidence is still required.']; if (id.includes('huroof-003')) return ['fixture_blocked','This is a resource-name fixture and must be rescoped before review.']; return ['cultural_review_blocked','Culture/heritage item requires authenticated cultural review and a claim-specific source packet.']; }
function specializedDifficulty(categoryId: string): 'easy' | 'medium' | 'hard' { if (['tahadani-045','tahadani-046'].includes(categoryId)) return 'medium'; if (categoryId === 'tahadani-047') return 'hard'; if (categoryId === 'tahadani-008') return 'hard'; if (categoryId === 'tahadani-051') return 'medium'; return 'medium'; }
function rubric(playable: Record<string, unknown>, sourceVersion: 'v1' | 'v2.1') { const answer = String(playable.canonicalAnswer ?? ''); const prompt = String(playable.promptAr ?? ''); const familiarity = answer.length <= 4 ? 3 : answer.length <= 8 ? 2 : 1; const clueDirectness = /ما (الحيوان|الأداة|الجهاز|العاصمة|العملة)/.test(prompt) ? 3 : 2; const domainSpecificity = /[اأ]فريقي|خوارزمية|كهرومغناطيسي|شبكية|تاريخي|فلبيني|باختري/.test(prompt) ? 3 : 1; const retrievalBurden = sourceVersion === 'v2.1' || domainSpecificity === 3 ? 3 : 1; const score = familiarity + clueDirectness - domainSpecificity - retrievalBurden; const difficulty = score >= 3 ? 'easy' : score >= 0 ? 'medium' : 'hard'; return { difficulty, rationale: `familiarity=${familiarity}; directness=${clueDirectness}; specificity=${domainSpecificity}; retrieval=${retrievalBurden}`, familiarity, clueDirectness, domainSpecificity, retrievalBurden, score }; }
export async function importCandidatesV3(): Promise<Candidate[]> {
  const [v1Raw, v21Raw] = await Promise.all([readFile(join(ROOT, 'content/questions/drafts/questions.jsonl'), 'utf8'), readFile(join(ROOT, 'content/question-bank-v2.1/drafts/new-categories.v2.1.jsonl'), 'utf8')]);
  const v1 = v1Raw.split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as Record<string, unknown>); const v21 = v21Raw.split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as Record<string, unknown>);
  const imported: Candidate[] = [...v1.map((playable) => { const sourceId = String(playable.id); const [disposition, dispositionReason] = v1Disposition(sourceId); const academy = ['tahadani-006', 'tahadani-013'].includes(String(playable.categoryId)); return { candidateId: `v3-v1-${sourceId}`, sourceVersion: 'v1' as const, sourceId, playable: academy ? academyPlayable(sourceId, playable) : { ...playable, ...(promptOverrides[sourceId] ? { promptAr: promptOverrides[sourceId] } : {}), explanationAr: null }, state: academy ? 'evidence_ready' as const : 'draft' as const, disposition, dispositionReason, provenance: { importedAt: asOf, sourcePath: 'content/questions/drafts/questions.jsonl', sourceHash: sha(v1Raw) } }; }), ...v21.map((playable) => { const sourceId = String(playable.id); const [disposition, dispositionReason] = v21Disposition(sourceId); return { candidateId: `v3-v21-${sourceId}`, sourceVersion: 'v2.1' as const, sourceId, playable: { ...playable, ...(sourceId.includes('huroof-002') ? { promptAr: 'ما الظاهرة التي تتمثل في اهتزاز مفاجئ للأرض بسبب حركة في القشرة؟' } : {}), explanationAr: null }, state: 'draft' as const, disposition, dispositionReason, provenance: { importedAt: asOf, sourcePath: 'content/question-bank-v2.1/drafts/new-categories.v2.1.jsonl', sourceHash: sha(v21Raw) } }; })];
  if (imported.length !== 284) throw new Error(`Expected 284 candidates, found ${imported.length}.`);
  let candidates = imported.map((candidate) => { if (['tahadani-006', 'tahadani-013'].includes(String(candidate.playable.categoryId))) return candidate; const revised = reviseSpecialized(candidate); const unresolved = unresolvedSpecializedIds.has(revised.sourceId); return { ...revised, playable: { ...revised.playable, difficulty: specializedDifficulty(String(revised.playable.categoryId)), explanationAr: null }, state: unresolved ? 'draft' as const : 'ready_for_human' as const, disposition: unresolved ? 'needs_evidence' as const : 'ready_for_human' as const, dispositionReason: unresolved ? 'The mapped direct source did not retrieve and no replacement source has yet been captured.' : 'Direct, claim-specific authoritative packet is captured; authenticated human review remains required.' }; });
  candidates = candidates.map((candidate) => { const difficultyRationale = rubric(candidate.playable, candidate.sourceVersion); return { ...candidate, playable: { ...candidate.playable, difficulty: difficultyRationale.difficulty }, difficultyRationale }; }); const [academyPackets, specializedPackets] = await Promise.all([materializeAcademyPackets(candidates, asOf), materializeSpecializedPackets(candidates, asOf)]); const packetIds = new Map([...academyPackets, ...specializedPackets].map((packet) => [packet.candidateId, packet.packetId])); const invalidPacketIds = new Set((await validateSpecializedPackets(candidates, specializedPackets, asOf)).map((issue) => issue.replace('invalid specialized packet specialized-v3-', '')).map((suffix) => suffix ? suffix : '')); candidates = candidates.map((candidate) => invalidPacketIds.has(candidate.candidateId) ? { ...candidate, evidencePacketId: packetIds.get(candidate.candidateId), state: 'draft' as const, disposition: 'needs_evidence' as const, dispositionReason: 'The persisted direct-source excerpt did not verify its distinctive claim token.' } : { ...candidate, evidencePacketId: packetIds.get(candidate.candidateId) });
  if (candidates.some((candidate) => !candidate.evidencePacketId)) throw new Error('Every v3 candidate requires exactly one evidence packet.'); await mkdir(join(OUT, 'candidates'), { recursive: true }); await writeFile(join(OUT, 'candidates/imported.v3.jsonl'), candidates.map((candidate) => JSON.stringify(candidate)).join('\n') + '\n'); await writeV31CategoryArtifacts(candidates); return candidates;
}
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) importCandidatesV3().then((items) => console.log(`Imported ${items.length} v3 candidates.`));
