import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { QUESTION_BANK_V32, answerConceptIdV32, canonicalJsonV32, contentHashV32, type CategoryPolicyV32, type QuestionV32 } from '../src/question-bank-v3.2.js';

const ROOT = process.cwd(); const SOURCE = join(ROOT, 'content/question-bank-v3/pilots'); const DESTINATION = join(ROOT, 'content/question-bank-v3/v3.2/pilots'); const OUT = join(ROOT, 'content/question-bank-v3/v3.2');
const hash = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');
type Json = Record<string, unknown>;
function canonical(value: unknown) { return canonicalJsonV32(value); }
function modality(category: Json): 'classic' | 'image' | 'charades' { if (category.id === 'tahadani-014' || category.sourceMode === 'image' || category.classicCompatibility === 'image_pending') return 'image'; return category.sourceMode === 'charades' || category.classicCompatibility === 'separate_mode' ? 'charades' : 'classic'; }
function policies(categories: Json[], sourceQuestions: Json[]): CategoryPolicyV32[] { return categories.map((category) => { const id = String(category.id); const mode = modality(category); const closed = ['tahadani-001', 'tahadani-045', 'tahadani-046', 'tahadani-059'].includes(id); const observedLetters = [...new Set(sourceQuestions.filter((question) => question.categoryId === id && question.modality !== 'charades').map((question) => String(question.targetLetter)).filter(Boolean))].sort(); const image = mode === 'image'; const finiteBlocked = ['tahadani-020', 'tahadani-044'].includes(id) || (observedLetters.length === 0 && (closed || image)); return { categoryId: id, modality: mode, supportedAnswerLetters: mode === 'charades' ? [] : observedLetters, grossTarget: { preferred: 336, minimum: 300 }, standaloneEligible: mode === 'classic' && !finiteBlocked, playability: mode === 'charades' ? 'separate_mode' : finiteBlocked ? 'scope_blocked' : 'letter_board', ...(finiteBlocked ? { scopeBlocker: id === 'tahadani-044' ? 'image/media inventory and explicit scope are required' : 'finite-domain coverage requires an explicit scope exception' } : {}), reusePolicy: closed ? { kind: 'closed_domain', maxPerConcept: 2 } : { kind: 'default', maxPerConcept: 1 } }; }); }
function migrated(question: Json): QuestionV32 {
  const mode = String(question.modality) as QuestionV32['modality']; const base: Json = { ...question, schemaVersion: QUESTION_BANK_V32, answerConceptId: answerConceptIdV32(String(question.canonicalAnswer ?? '')), migration: { sourceSchemaVersion: question.schemaVersion, semanticVersion: QUESTION_BANK_V32 } };
  if (mode === 'charades') { delete base.targetLetter; delete base.acceptDefiniteArticle; base.performanceFacetId = `performance:${question.id}`; }
  else base.facetId = `facet:${question.id}`;
  const value = base as QuestionV32; return { ...value, contentHash: contentHashV32(value) };
}
async function files(directory: string): Promise<string[]> { const entries = await readdir(directory, { withFileTypes: true }); return (await Promise.all(entries.map(async (entry) => entry.isDirectory() ? files(join(directory, entry.name)) : [join(directory, entry.name)]))).flat(); }
export async function migrateQuestionPilotsV32(source = SOURCE, destination = DESTINATION) {
  const sourceFiles = (await files(source)).filter((path) => /batch-.+\.(questions\.jsonl|evidence\.jsonl|report\.json)$/.test(path)); const coreCategories = (JSON.parse(await readFile(join(ROOT, 'content/categories/categories.json'), 'utf8')) as { categories: Json[] }).categories; const extensions = (JSON.parse(await readFile(join(ROOT, 'content/categories/extensions/huroof-v2.1.json'), 'utf8')) as { categories: Json[] }).categories; const sourceQuestions = (await Promise.all(sourceFiles.filter((path) => path.endsWith('.questions.jsonl')).map(async (path) => (await readFile(path, 'utf8')).split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as Json)))).flat(); const policy = policies([...coreCategories, ...extensions], sourceQuestions); if (policy.length !== 66 || new Set(policy.map((item) => item.categoryId)).size !== 66) throw new Error('Expected exactly 66 explicit, unique category policies.');
  await rm(destination, { recursive: true, force: true }); const manifestFiles: Array<Record<string, unknown>> = []; let questions = 0; let evidence = 0;
  for (const sourcePath of sourceFiles.sort()) {
    const relative = sourcePath.slice(source.length + 1).replaceAll('\\', '/'); const destinationPath = join(destination, relative); await mkdir(resolve(destinationPath, '..'), { recursive: true }); const oldText = await readFile(sourcePath, 'utf8'); let newText = oldText;
    if (relative.endsWith('.questions.jsonl')) { const records = oldText.split(/\r?\n/).filter(Boolean).map((line) => migrated(JSON.parse(line) as Json)); questions += records.length; newText = records.map(canonical).join('\n') + '\n'; }
    else if (relative.endsWith('.evidence.jsonl')) { evidence += oldText.split(/\r?\n/).filter(Boolean).length; }
    else { const legacy = JSON.parse(oldText) as Json; newText = canonical({ schemaVersion: QUESTION_BANK_V32, migration: { sourceSchemaVersion: legacy.schemaVersion, sourceReportHash: hash(oldText), evidenceRetainedAt: `../${relative.replace(/\.report\.json$/, '.evidence.jsonl')}` }, legacyReport: legacy }) + '\n'; }
    await writeFile(destinationPath, newText); manifestFiles.push({ path: relative, oldSha256: hash(oldText), newSha256: hash(newText), oldContentHash: hash(oldText), newContentHash: hash(newText) });
  }
  if (questions !== 408 || evidence !== 418) throw new Error(`Migration reconciliation failed: ${questions} questions / ${evidence} evidence.`);
  await mkdir(OUT, { recursive: true }); const policyDocument = { schemaVersion: QUESTION_BANK_V32, policyVersion: 'question-bank-duplicate-v3.2', categories: policy }; await writeFile(join(OUT, 'category-policies.v3.2.json'), canonical(policyDocument) + '\n');
  const questionAudits = (await Promise.all((await files(destination)).filter((path) => path.endsWith('.questions.jsonl')).map(async (path) => (await readFile(path, 'utf8')).split(/\r?\n/).filter(Boolean).map((line) => { const record = JSON.parse(line) as QuestionV32; return { id: record.id, contentHash: record.contentHash, answerConceptId: record.answerConceptId, conceptHash: hash(record.answerConceptId) }; })))).flat(); const manifest = { schemaVersion: QUESTION_BANK_V32, source: 'content/question-bank-v3/pilots', destination: 'content/question-bank-v3/v3.2/pilots', reconciliation: { questions, evidence, preserved: ['id', 'headerAr', 'promptAr', 'canonicalAnswer', 'acceptedAnswers', 'evidencePacketIds', 'state', 'provenance'], approved: 0, released: 0 }, files: manifestFiles, records: questionAudits.sort((a, b) => a.id.localeCompare(b.id)), manifestHash: '' }; manifest.manifestHash = hash(canonical({ ...manifest, manifestHash: undefined })); await writeFile(join(OUT, 'migration-manifest.v3.1-to-v3.2.json'), canonical(manifest) + '\n'); return manifest;
}
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) console.log(JSON.stringify(await migrateQuestionPilotsV32(), null, 2));
