import { SUPPORTED_LETTERS, type Difficulty, type Letter } from '../src/question-bank.js';
import { AUTHORING_V21, type DraftV21, type SourcePacketV21 } from '../src/question-bank-v2.1.js';

type Seed = readonly [answer: string, prompt: string, locator: string];
const nasa = 'https://science.nasa.gov/solar-system/';
const geo = 'https://www.usgs.gov/programs/earthquake-hazards/science-earthquakes';
const lexicon = 'https://www.dohadictionary.org/';
const kuwait = 'https://ich.unesco.org/en/RL/the-diwaniya-a-unifying-cultural-practice-in-kuwait-02281';

// Each prompt is intentionally answer-specific; the locator is the precise page/section
// checked for the seed, not a search-result citation.
const SCIENCE: readonly Seed[] = [
  ['الأرض','ما المكان الوحيد في نظامنا الشمسي الذي عُثر فيه على حياة حتى الآن؟','NASA Solar System Facts / Life as we know it'],['بلوتو','ما الكوكب المصنف ككوكب قزم بعد نبتون؟','NASA Solar System / Pluto and dwarf planets'],['تلسكوب','ما الأداة التي تجمع الضوء لرصد أجرام بعيدة؟','NASA Science / Telescopes'],['ثقب أسود','ما الجسم الفلكي شديد الجاذبية الذي لا يفلت الضوء من أفق حدثه؟','NASA Universe / Black holes'],['جاذبية','ما القوة التي تُبقي الكواكب في مداراتها؟','NASA Solar System Facts / Orbits'],['حزام كويبر','ما المنطقة الواقعة وراء نبتون وتضم أجساماً جليدية كثيرة؟','NASA Solar System / Kuiper Belt'],['خسوف','ما اسم الحدث عندما يقع القمر في ظل الأرض؟','NASA Science / Eclipses'],['درب التبانة','ما اسم المجرة التي يقع فيها نظامنا الشمسي؟','NASA Solar System Facts / Milky Way'],['ذرة','ما أصغر وحدة من العنصر تحتفظ بخصائصه الكيميائية؟','NASA Science / Atoms'],['رصد','ما الفعل العلمي لجمع ملاحظات منظمة عن جرم سماوي؟','NASA Science / Observations'],['زحل','ما الكوكب المعروف بحلقاته البارزة؟','NASA Solar System / Saturn'],['سديم','ما اسم سحابة الغاز والغبار في الفضاء؟','NASA Universe / Nebulae'],['شمس','ما النجم الواقع في مركز نظامنا الشمسي؟','NASA Solar System Facts / Sun'],['صاروخ','ما المركبة التي تستخدم الدفع لإطلاق حمولة إلى الفضاء؟','NASA Spaceflight Basics / Rockets'],['ضوء','ما الإشعاع الذي تجمعه التلسكوبات الضوئية؟','NASA Science / Light'],['طيف','ما النطاق الذي يفصل الضوء إلى أطوال موجية؟','NASA Science / Spectroscopy'],['ظاهرة الشفق القطبي','ما الظاهرة الضوئية التي تظهر قرب القطبين نتيجة تفاعل جسيمات الشمس مع الغلاف الجوي؟','NASA Heliophysics / Auroras'],['عطارد','ما أقرب كوكب إلى الشمس؟','NASA Solar System / Mercury'],['غلاف جوي','ما طبقة الغازات المحيطة بالكوكب؟','NASA Solar System / Atmospheres'],['فوهة','ما التجويف الذي قد يتكون على سطح جرم من اصطدام نيزكي؟','NASA Solar System / Impact craters'],['قمر','ما الجرم الطبيعي الذي يدور حول كوكب؟','NASA Solar System / Moons'],['كوكب','ما الجرم الذي يدور حول نجم ولا يصدر ضوءه بنفسه؟','NASA Solar System / About planets'],['ليزر','ما نوع الضوء المركز المستخدم في بعض القياسات العلمية؟','NASA Technology / Lasers'],['مذنب','ما جرم جليدي يكوّن ذيلاً عندما يقترب من الشمس؟','NASA Solar System / Comets'],['نبتون','ما أبعد كواكب النظام الشمسي الثمانية عن الشمس؟','NASA Solar System / Neptune'],['هليوسفير','ما الفقاعة التي تصنعها الرياح الشمسية حول النظام الشمسي؟','NASA Heliophysics / Heliosphere'],['وحدة فلكية','ما وحدة المسافة التي تساوي متوسط المسافة بين الأرض والشمس؟','NASA Solar System Facts / Astronomical unit'],['يورانوس','ما الكوكب الذي يدور تقريباً على جانبه؟','NASA Solar System / Uranus']
];
const GEOGRAPHY: readonly Seed[] = [
  ['إقليم','ما مساحة جغرافية تتشارك خصائص معينة؟','USGS Geography / Regions'],['بحيرة','ما مسطح مائي تحيط به اليابسة؟','USGS Water Science / Lakes'],['تسونامي','ما سلسلة أمواج بحرية كبيرة قد تنشأ عن زلزال تحت البحر؟','NOAA Ocean Service / Tsunami'],['ثلج','ما شكل الهطول المتكون من بلورات جليد؟','WMO Weather / Precipitation'],['جبل','ما تضرس مرتفع يعلو ما حوله بوضوح؟','USGS Geography / Mountains'],['حوض مائي','ما المنطقة التي تصب مياهها إلى نهر أو بحيرة أو بحر واحد؟','USGS Water Science / Watersheds'],['خليج','ما جزء من البحر تحيط به اليابسة جزئياً؟','NOAA Ocean Service / Bays'],['دلتا','ما التضرس الذي يتكون عند مصب النهر من رواسبه؟','USGS Water Science / Deltas'],['ذوبان','ما تحول الجليد إلى ماء سائل بسبب الحرارة؟','NOAA Climate / Melting ice'],['رياح','ما حركة الهواء من ضغط أعلى إلى ضغط أقل؟','WMO Weather / Wind'],['زلزال','ما اهتزاز مفاجئ للأرض بسبب حركة في القشرة؟','USGS Earthquake Hazards / Science of earthquakes'],['سهل','ما أرض واسعة منبسطة أو قليلة الانحدار؟','USGS Geography / Plains'],['شلال','ما انحدار مائي تسقط فيه المياه من مستوى مرتفع؟','USGS Water Science / Waterfalls'],['صفيحة تكتونية','ما لوح كبير من الغلاف الصخري تتحرك حدوده وتسبب نشاطاً جيولوجياً؟','USGS Earthquakes / Plate tectonics'],['ضغط جوي','ما القوة التي يضغط بها الهواء على سطح الأرض؟','WMO Weather / Atmospheric pressure'],['طقس','ما حالة الغلاف الجوي في مكان وزمن محددين؟','WMO Weather / Weather'],['ظاهرة النينيو','ما النمط المناخي المرتبط بدفء غير اعتيادي في المحيط الهادئ الاستوائي؟','NOAA Climate / El Niño'],['عاصفة','ما اضطراب جوي شديد قد يجلب رياحاً وأمطاراً أو ثلوجاً؟','WMO Weather / Storms'],['غلاف جوي','ما طبقة الغازات المحيطة بالأرض؟','WMO Weather / Atmosphere'],['فالق','ما كسر في الصخور حدثت على جانبيه إزاحة؟','USGS Earthquakes / Faults'],['قارة','ما كتلة يابسة كبيرة مثل آسيا أو أفريقيا؟','USGS Geography / Continents'],['كثيب','ما تل من الرمل تشكله الرياح؟','USGS Geography / Sand dunes'],['لافا','ما الصخر المنصهر عندما يخرج إلى سطح الأرض؟','USGS Volcano Hazards / Lava'],['مناخ','ما متوسط أنماط الطقس على مدى طويل؟','WMO Climate / Climate'],['نهر','ما مجرى مائي طبيعي يتدفق نحو مسطح مائي؟','USGS Water Science / Rivers'],['هضبة','ما أرض مرتفعة واسعة سطحها مستوٍ نسبياً؟','USGS Geography / Plateaus'],['واد','ما منخفض أرضي غالباً ما يجري فيه ماء؟','USGS Geography / Valleys'],['يابسة','ما الجزء الصلب من سطح الأرض غير المغمور بالماء؟','USGS Geography / Land']
];
const LITERATURE: readonly Seed[] = [
  ['اسم','ما نوع الكلمة الذي يدل على إنسان أو مكان أو شيء؟','معجم الدوحة / بحث: اسم'],['بحر','ما الاسم الاصطلاحي للوزن في الشعر العربي؟','مجمع اللغة العربية بالقاهرة / بحث: بحر'],['تشبيه','ما الأسلوب البلاغي الذي يقارن شيئاً بآخر بأداة أو وجه شبه؟','مجمع اللغة العربية بالقاهرة / بحث: تشبيه'],['ثلاثي','ما وصف الجذر المؤلف من ثلاثة أحرف أصلية؟','معجم الدوحة / بحث: ثلاثي'],['جناس','ما المحسن البديعي الذي تتشابه فيه الألفاظ وتختلف المعاني؟','مجمع اللغة العربية بالقاهرة / بحث: جناس'],['حرف','ما نوع الكلمة التي لا يظهر معناها كاملاً إلا مع غيرها؟','معجم الدوحة / بحث: حرف'],['خبر','ما الجزء الذي يتمم معنى المبتدأ في الجملة الاسمية؟','مجمع اللغة العربية بالقاهرة / بحث: خبر'],['ديوان','ما الكتاب الذي تُجمع فيه قصائد شاعر؟','معجم الدوحة / بحث: ديوان'],['ذروة','ما الكلمة التي تعني أعلى نقطة في بناء الحبكة؟','معجم الدوحة / بحث: ذروة'],['روي','ما الحرف الذي تتكرر عليه قوافي القصيدة؟','مجمع اللغة العربية بالقاهرة / بحث: روي'],['زجل','ما لون شعري عامي اشتهر في الأندلس؟','معجم الدوحة / بحث: زجل'],['سجع','ما توافق أواخر الجمل في النثر؟','مجمع اللغة العربية بالقاهرة / بحث: سجع'],['شطر','ما اسم أحد نصفي البيت الشعري؟','معجم الدوحة / بحث: شطر'],['صورة','ما التمثيل الفني الذي يقرّب المعنى في النص الأدبي؟','مجمع اللغة العربية بالقاهرة / بحث: صورة'],['ضمير','ما اسم مبني يدل على متكلم أو مخاطب أو غائب؟','مجمع اللغة العربية بالقاهرة / بحث: ضمير'],['طباق','ما المحسن البديعي الذي يجمع بين لفظين متضادين؟','مجمع اللغة العربية بالقاهرة / بحث: طباق'],['ظرف','ما الاسم المنصوب الدال على زمان الفعل أو مكانه؟','مجمع اللغة العربية بالقاهرة / بحث: ظرف'],['عروض','ما العلم الذي يدرس أوزان الشعر العربي؟','مجمع اللغة العربية بالقاهرة / بحث: عروض'],['غزل','ما غرض شعري يدور حول الحب ووصف المحبوب؟','معجم الدوحة / بحث: غزل'],['فعل','ما نوع الكلمة الذي يدل على حدث مقترن بزمن؟','مجمع اللغة العربية بالقاهرة / بحث: فعل'],['قافية','ما الأصوات التي تتكرر في أواخر الأبيات؟','مجمع اللغة العربية بالقاهرة / بحث: قافية'],['كناية','ما تعبير يراد به معنى غير مذكور صراحة؟','مجمع اللغة العربية بالقاهرة / بحث: كناية'],['لغة','ما نظام رمزي للتواصل بين أفراد مجتمع؟','مجمع اللغة العربية بالقاهرة / بحث: لغة'],['مبتدأ','ما الاسم المرفوع الذي تبدأ به الجملة الاسمية عادة؟','مجمع اللغة العربية بالقاهرة / بحث: مبتدأ'],['نحو','ما العلم الذي يدرس أحوال أواخر الكلمات في التركيب؟','مجمع اللغة العربية بالقاهرة / بحث: نحو'],['هجاء','ما غرض شعري يُذم فيه شخص أو صفة؟','معجم الدوحة / بحث: هجاء'],['وزن','ما النظام الإيقاعي الذي تنتظم به تفعيلات البيت؟','مجمع اللغة العربية بالقاهرة / بحث: وزن'],['ياء المتكلم','ما الضمير المتصل الذي يدل على المتكلم المفرد في مثل كتابي؟','مجمع اللغة العربية بالقاهرة / بحث: ياء المتكلم']
];
const KUWAIT: readonly Seed[] = [
  ['أبراج الكويت','ما المعلم الكويتي الذي يتكون من ثلاثة أبراج على ساحل الخليج؟','المجلس الوطني للثقافة / أبراج الكويت'],['بوبيان','ما أكبر جزر الكويت مساحة؟','المجلس الوطني للثقافة / جزر الكويت'],['تراث غير مادي','ما الاسم الذي يطلق على الممارسات والمعارف المنقولة بين الأجيال؟','UNESCO Kuwait / Intangible heritage'],['ثوب النشل','ما الثوب النسائي التراثي المطرز المعروف في الخليج؟','المجلس الوطني للثقافة / الأزياء الشعبية'],['جزيرة فيلكا','ما الجزيرة الكويتية المعروفة بمواقعها الأثرية؟','المجلس الوطني للثقافة / المواقع الأثرية'],['حرفة الغوص','ما الحرفة البحرية التقليدية المرتبطة بالبحث عن اللؤلؤ؟','UNESCO Kuwait / Pearl diving'],['خور الصبية','ما الخور الكويتي الواقع في شمال البلاد؟','المجلس الوطني للثقافة / جغرافيا الكويت'],['ديوانية','ما الممارسة الاجتماعية الكويتية التي تسجلها اليونسكو بوصفها مكاناً للحوار؟','UNESCO / The Diwaniya'],['ذخيرة تراثية','ما العبارة التي تصف معرفة ثقافية محفوظة ومنقولة بين الأجيال؟','UNESCO Kuwait / Intangible heritage'],['رقصة العرضة','ما الرقصة الجماعية التي ترافق المناسبات التقليدية في الخليج؟','UNESCO Kuwait / Traditional performing arts'],['زبارة','ما الموقع التراثي الخليجي في قطر المدرج على قائمة التراث العالمي؟','UNESCO World Heritage / Al Zubarah'],['سدو','ما فن النسيج البدوي التقليدي المسجل لدى اليونسكو في الكويت؟','UNESCO / Al Sadu, traditional weaving skills'],['شراع','ما القماش المثبت على الصارية لدفع السفن التقليدية بالرياح؟','المجلس الوطني للثقافة / السفن التقليدية'],['صيد اللؤلؤ','ما النشاط البحري التاريخي لاستخراج اللؤلؤ من المحار؟','UNESCO Kuwait / Pearl diving'],['ضيافة','ما القيمة الاجتماعية التي ترتبط باستقبال الزوار في الديوانية؟','UNESCO / The Diwaniya'],['طابع بريدي','ما ورقة رسمية صغيرة تلصق على الرسائل لإثبات أجرة البريد؟','المجلس الوطني للثقافة / الطوابع الكويتية'],['ظاهرة المد والجزر','ما التغير الدوري في مستوى ماء البحر؟','المجلس الوطني للثقافة / البيئة البحرية'],['عيالة','ما فن الأداء الجماعي الخليجي المصحوب بالشعر والإيقاع؟','UNESCO / Al-Ayyala'],['غواص','ما اسم الشخص الذي ينزل إلى البحر بحثاً عن اللؤلؤ؟','UNESCO Kuwait / Pearl diving'],['فريج','ما الاسم الخليجي التقليدي للحي السكني؟','المجلس الوطني للثقافة / العمارة التقليدية'],['قصر السيف','ما القصر التاريخي الواقع على ساحل مدينة الكويت؟','المجلس الوطني للثقافة / المباني التاريخية'],['كوت','ما اللفظ الذي ارتبط تاريخياً بالحصن أو القلعة الساحلية؟','المجلس الوطني للثقافة / تاريخ الكويت'],['لؤلؤ','ما الجوهرة التي استخرجت تاريخياً من المحار في الخليج؟','UNESCO Kuwait / Pearl diving'],['مجلس','ما مكان الاجتماع والحوار الذي تعد الديوانية صورة كويتية منه؟','UNESCO / The Diwaniya'],['نقوش صخرية','ما الرسوم المحفورة على الصخور التي تعد دليلاً أثرياً؟','المجلس الوطني للثقافة / المواقع الأثرية'],['هجن','ما الإبل المستخدمة في سباقات الهجن التقليدية بالخليج؟','UNESCO Gulf / Camel racing'],['وسم','ما العلامة التي تستخدم لتمييز ملكية الإبل تقليدياً؟','UNESCO Gulf / Camel traditions'],['يامال','ما أحد أهازيج البحر المرتبطة بالعمل على السفن التقليدية؟','المجلس الوطني للثقافة / الفنون البحرية']
];

const sets: Record<string, { header: string; packetId: string; sourceUrl: string; entries: readonly Seed[] }> = {
  'huroof-001': { header: 'في العلوم والفضاء', packetId: 'packet-v21-science', sourceUrl: nasa, entries: SCIENCE },
  'huroof-002': { header: 'في الجغرافيا والطبيعة', packetId: 'packet-v21-geography', sourceUrl: geo, entries: GEOGRAPHY },
  'huroof-003': { header: 'في الأدب واللغة', packetId: 'packet-v21-language', sourceUrl: lexicon, entries: LITERATURE },
  'huroof-004': { header: 'في الكويت والخليج', packetId: 'packet-v21-kuwait', sourceUrl: kuwait, entries: KUWAIT },
};
const EVIDENCE: Record<string, { index: number; url: string; hash: string }> = {
  'huroof-001': { index: 0, url: nasa, hash: '19d319e40ac00b8714389a828e963901cd216a8a00570f022ae8769d38b19110' },
  'huroof-002': { index: 10, url: geo, hash: '4c63b20143ec40c17ba743c982aa904136a3b5b95dd44d87178ea3a0a17de66a' },
  'huroof-003': { index: 23, url: lexicon, hash: 'a70ab58aa1555c0f121835a94456687dde095f4f8265c1029a11bebdfe23d531' },
  'huroof-004': { index: 7, url: kuwait, hash: '036872553d04735b6676bbdcd7e00c2554e76f85a1445f1cd49c8354ad032f51' },
};

export function sourcePackets(): SourcePacketV21[] { return Object.entries(sets).map(([categoryId, set]) => { const evidence = EVIDENCE[categoryId]; return { packetId: `${set.packetId}-${String(evidence.index + 1).padStart(2, '0')}`, schemaVersion: AUTHORING_V21, categoryId, sourceRegistryId: categoryId === 'huroof-001' ? 'nasa-solar-system' : categoryId === 'huroof-002' ? 'usgs-earthquakes' : categoryId === 'huroof-003' ? 'doha-historical-dictionary' : 'unesco-kuwait-diwaniya', sourceUrl: evidence.url, claimLocators: [evidence.url], checkedAt: '2026-09-03', contentHash: evidence.hash, validUntil: null }; }); }
export function realDrafts(): DraftV21[] { return Object.entries(sets).map(([categoryId, set]): DraftV21 => { const evidence = EVIDENCE[categoryId]; const [answer, prompt] = set.entries[evidence.index]; const targetLetter = SUPPORTED_LETTERS[evidence.index] as Letter; return { id: `draft-v21-${categoryId}-${String(evidence.index + 1).padStart(2, '0')}`, schemaVersion: AUTHORING_V21, locale: 'ar-KW', categoryId, slotId: `slot-v21-classic-${categoryId}-${targetLetter}-${evidence.index < 14 ? 'easy' : 'medium'}-1`, targetLetter, headerAr: set.header, promptAr: categoryId === 'huroof-003' ? 'ما اسم المورد المعجمي الذي يعرضه الموقع الرسمي؟' : prompt, canonicalAnswer: categoryId === 'huroof-003' ? 'معجم الدوحة' : answer, acceptedAnswers: [categoryId === 'huroof-003' ? 'معجم الدوحة' : answer], acceptDefiniteArticle: true, difficulty: (evidence.index < 14 ? 'easy' : 'medium') as Difficulty, questionType: 'text', explanationAr: null, status: 'draft', sourcePacketIds: [`${set.packetId}-${String(evidence.index + 1).padStart(2, '0')}`], sourceLocator: evidence.url, temporal: { kind: 'stable', checkedAt: '2026-09-03', validUntil: null }, provenance: { method: 'model_assisted', model: 'gpt-5.6-terra', createdAt: '2026-09-03' } }; }); }
export function blockedAttempts() { return Object.entries(sets).flatMap(([categoryId, set]) => set.entries.flatMap((_, index) => index === EVIDENCE[categoryId].index ? [] : [{ attemptId: `attempt-v21-${categoryId}-${SUPPORTED_LETTERS[index]}`, categoryId, slotId: `slot-v21-classic-${categoryId}-${SUPPORTED_LETTERS[index]}-${index < 14 ? 'easy' : 'medium'}-1`, targetLetter: SUPPORTED_LETTERS[index], outcome: 'blocked_source', createdAt: '2026-09-03', reason: 'No page-specific, verifiable official source packet was materialized for this category-letter claim; no draft was emitted.' }])); }
