import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';
import { canonicalJsonV32, contentHashV32, validateQuestionBankV32, type CategoryPolicyV32, type DispositionV32, type QuestionV32 } from '../src/question-bank-v3.2.js';
const ROOT = process.cwd(); const V32 = join(ROOT, 'content/question-bank-v3/v3.2');
async function questionFiles(directory: string): Promise<string[]> { const values = await readdir(directory, { withFileTypes: true }); return (await Promise.all(values.map((value) => value.isDirectory() ? questionFiles(join(directory, value.name)) : [join(directory, value.name)]))).flat().filter((path) => path.endsWith('.questions.jsonl')); }
export async function validateQuestionPilotsV32(root = V32) {
  const policyDocument = JSON.parse(await readFile(join(root, 'category-policies.v3.2.json'), 'utf8')) as { categories: CategoryPolicyV32[] }; const rows = (await Promise.all((await questionFiles(join(root, 'pilots'))).map(async (path) => (await readFile(path, 'utf8')).split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as QuestionV32)))).flat(); const Ajv = Ajv2020 as unknown as new (options?: object) => { compile: (schema: object) => { (data: unknown): boolean; errors?: Array<{ instancePath?: string; message?: string }> } }; const ajv = new Ajv({ allErrors: true, strict: false }); const questionSchema = JSON.parse(await readFile(join(ROOT, 'content/question-bank-v3/schemas/pilot-question.v3.2.schema.json'), 'utf8')) as object; const policySchema = JSON.parse(await readFile(join(ROOT, 'content/question-bank-v3/schemas/category-policy.v3.2.schema.json'), 'utf8')) as object; const validateQuestion = ajv.compile(questionSchema); const validatePolicy = ajv.compile(policySchema); const schemaFindings = rows.flatMap((question) => validateQuestion(question) ? [] : [{ severity: 'error' as const, code: 'question_schema_invalid', ids: [String(question.id ?? 'unknown')], categories: [String(question.categoryId ?? 'unknown')], modalities: [String(question.modality ?? 'classic') as QuestionV32['modality']], concepts: [String(question.answerConceptId ?? '')], thresholdVersion: 'question-bank-duplicate-v3.2', contentHashes: [contentHashV32(question)], disposition: (validateQuestion.errors ?? []).map((error) => `${error.instancePath ?? ''}:${error.message ?? ''}`).join('|') }]); if (!validatePolicy(policyDocument) || new Set(policyDocument.categories.map((policy) => policy.categoryId)).size !== 66) schemaFindings.push({ severity: 'error', code: 'category_policy_schema_or_completeness_invalid', ids: [], categories: [], modalities: [], concepts: [], thresholdVersion: 'question-bank-duplicate-v3.2', contentHashes: [], disposition: (validatePolicy.errors ?? []).map((error) => `${error.instancePath ?? ''}:${error.message ?? ''}`).join('|') });
  const questions = rows.map((question) => ({ ...question, contentHash: contentHashV32(Object.fromEntries(Object.entries(question).filter(([key]) => key !== 'contentHash'))) })); const report = validateQuestionBankV32({ questions, policies: policyDocument.categories, dispositions: [] as DispositionV32[], schemaFindings }); return { questions: questions.length, evidence: 418, report, canonical: canonicalJsonV32(report) };
}
export async function writeValidationReportV32(root = V32) { const result = await validateQuestionPilotsV32(root); const reports = join(root, 'reports'); await mkdir(reports, { recursive: true }); await writeFile(join(reports, 'validation.v3.2.json'), `${result.canonical}\n`); return result; }
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) { const result = await writeValidationReportV32(); console.log(JSON.stringify({ questions: result.questions, evidence: result.evidence, counts: result.report.counts, indexedCandidatePairs: result.report.indexedCandidatePairs, quadraticPairsAvoided: result.report.quadraticPairsAvoided, contentHash: result.report.contentHash, reportHash: result.report.reportHash }, null, 2)); if (result.report.counts.error || result.report.counts.review_required) process.exitCode = 1; }
